### ISSUE TITLE
Bug: DOS attempt to use DOS_GetMemory() while changing floppy

### ISSUE THREAD

**Issue by maxpat78** [joncampbell123/dosbox-x#4557] opened 2023-10-26 07:10 UTC
### Describe the bug

A fatal error occurs if you:

- boot MS-DOS 6.22 floppy no. 1
- exit setup
- use DOS menu to change floppy

at this point, it fires an `E_Exit: DOS:Attempt to use DOS_GetMemory() when private area was unmapped by BOOT` error.

### Steps to reproduce the behaviour

See above.

### Expected behavior

Floppies can get changed.

### What operating system(s) this bug have occurred on?

Windows 11 x64 22H2

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment] 2023-10-27 03:05
I can't reproduce what you said.

boot PC-DOS 6.3 floppy no. 1 (Does MS-DOS matter?)
exit setup
use DOS menu to change floppy

Tested on 2023.10.06 release (VS SDL1 x64)
![change_floppy](https://github.com/joncampbell123/dosbox-x/assets/68574602/23c5ceac-d396-43fe-83bc-dfe82f5499a7)

**Comment by maxpat78** [comment] 2023-10-27 05:45
@maron2000 mmm... Now I can't reproduce it myself! But it occurred 3 times when I've opened the bug report.
Actually, only #4556 happens on reboot.

**Comment by maron2000** [comment] 2023-10-27 08:07
Okay, so you can close this issue for the time being, and of course re-open it when you find out how to reproduce it.
There should be some additional conditions to reproduce your issue.

**Closed** 2023-10-27 13:01 UTC
Labels: bug
