### ISSUE TITLE
The "Capture => Load state" command successfully loads only one day old saved states files. On the rest saved states files older than one day, the "Capture => Load state" command both simply and just causes dosbox-x to crash both instantly and immediately.

### ISSUE THREAD

**Issue by buruto** [joncampbell123/dosbox-x#1986] opened 2020-11-07 12:08 UTC
**Describe the bug**

The title/caption/header describes the bug issue both clearly and concisely and says everything about the bug issue and what the bug issue is.

**To Reproduce**

Firstly start playing any dos video game with dosbox-x emulator for about 5 minutes.
Then go to the "Capture" menu and then click on the "Save state" command and then enter any remark.
Then continue playing for another about 5 minutes and then go again to the "Capture" menu and then click on the "Load state" command.
You should see that the "Capture => Load state" commands works properly.
Then both close and exit dosbox-x emulator and then wait at least 24 hours.
After 24 hours launch again dosbox-x and try to load the same saved state that you did 24 hours ago again by going to the "Capture" menu and then clicking on the "Load state" command.
Now you should see that dosbox-x emulator is crashing. 

**Expected behavior**

"Capture => Load state" command supposes to work always, no matter when the command was done and no matter how much old the saved state file that the "Capture => Load state" command should read from.

**Screenshots**

No screenshot is needed. Just do all the steps above to reproduce the bug issue and you will see it yourself even if you will have to wait at least 24 hours to see it.

**Environment (please complete the following information):**
 - Operating system
 - DOSBox-X release version or commit SHA1 this issue occurred on
 - Used configuration, e.g. ```dosbox-x.conf```

Operating system: Windows 10 Enterprise Edition 64 bit version 2004
This bug issue happens with DOSBox-X SDL2 x64 release version 0.83.7
This bug also happens with all the **non** SDL2 versions and also with all the x86 versions too.
I also noticed that there are ARM and ARM64 versions, but those two versions I can't test at all, because I have x64 CPU only (I have neither ARM nor ARM64 CPU), so to know if this bug issue also happens on ARM and ARM64, some user that has ARM64 CPU has to do all the steps above to reproduce the bug issue even if he or she will have to wait at least 24 hours.

**Additional context**

No additional context is needed, because all the text above **Additional context" says everything and pretty enough to understand the bug issue and to fix it.

If you still have any question about the bug issue that I did not say anything about, forgot to mention or explain yet after reading all the text above then please so simply just and don't hesitate at all to ask me that question and I will try my best to answer it.

**Comment by Wengier** [comment] 2020-11-08 04:25
@buruto The save state feature will never check for when the states were actually saved for the save files, although DOSBox-X will indeed save a lot of internal structures. But as long as the save files and the DOSBox-X binary remain intact, the save files should be loaded fine. So either the save files are modified since they were saved, or the DOSBox-X binary itself has been modified. Indeed, DOSBox-X does not granrantee that it will always load saved files saved by another version/build of DOSBox-X, and I think this is likely the cause of the problem. Please check it out.

**Comment by buruto** [comment] 2020-11-08 15:24
Recently I downloaded tenebrae setup, then ran that setup of course and then the setup created some folder that contains tenebrae.exe, Tenebrae_launch.exe and a folder called "tenebrae".
Next to "tenebrae" folder, I created "id1" folder and then I put both pak0.pak and pak1.pak of vanilla quake inside the "id1" folder and then I ran tenebrae.exe directly through Windows File Explorer first time as normal user (not administrator) and second time as administrator.
In both times a black window appeared. I remember that I saw the word "tenebrae" written on the title/caption bar of the window, but few seconds after launch the window disappeared. Also I did not see tenebrae in the task bar too.

Then I ran tenebrae.exe directly again with Windows File Explorer but now in all compatibility modes starting from Windows 8.1 to Windows 95, but the result is the same (saw a black tenebrae window for a few seconds and then disappeared).

I also used the Tenebrae_launch.exe again without and with all possible compatibility modes without and with "Run as administrator", but in all runs, Tenebrae_launch.exe shows me a window with graphical user interface that allows me to configure tenebrae. I used it to configure tenebrae to the settings that I wanted to and then clicked the button to start tenebrae and again I saw a black tenebrae window for a few seconds and then that window disappeared. Then tried all other possible configurations but to no avail!

I don't succeed to run tenebrae properly on my system and my machine and I don't know why tenebrae is not just playing! Please help me! I surfaced some websites in the internet and saw a few amazing screenshots of tenebrae. From all the screenshots that I saw I have gotten the impression that tenebrae is even more nicer than both darkplaces and FTE QuakeWorld!

I read that tenebrae is based on the new Doom engine graphics.

> @buruto The save state feature will never check for when the states were actually saved for the save files, although DOSBox-X will indeed save a lot of internal structures. But as long as the save files and the DOSBox-X binary remain intact, the save files should be loaded fine. So either the save files are modified since they were saved, or the DOSBox-X binary itself has been modified. Indeed, DOSBox-X does not guarantee that it will always load saved files saved by another version/build of DOSBox-X, and I think this is likely the cause of the problem. Please check it out.

I don't modify saved state files that were created by DOSBox-X and I am always using the both most recent, latest and newest x64 SDL2 version of DOSBox-X, so as long as I don't know or not aware that there is newer x64 SDL2 version of DOSBox-X then I am continuing to use the both most recent, latest and newest x64 SDL2 version of DOSBox-X that is installed on my machine and system. So I don't change the version of DOSBox-X too. According to what you are telling me, all saved state files that were created yesterday by DOSBox-X should load properly today, but this is not the case, because if this was the case then I wouldn't open this bug issue at all, but I did open this bug issue so this is the case that DOSBox-X does not load saved state files that were created yesterday, but only those that were created today.

I am not blind person, I know what I am seeing. I will never open a new bug issue if I did not find any bug issue.

**Comment by Wengier** [comment] 2020-11-09 08:03
@buruto I want to ask a question: by "most recent, latest and newest version" do you mean the latest official DOSBox-X x64 SDL2 version (0.83.7), or the latest x64 SDL2 code you built with Visual Studio yourself? If you use the latest x64 SDL2 code with Visual Studio yourself, did you rebuild the code with Visual Studio and then try to load the saved states saved by the earlier x64 SDL2 binary? If so, I think I saw this earlier too - in such case the x64 SDL2 binary is not exactly the same, but it is something worth to be address too of course.

**Comment by buruto** [comment] 2020-11-09 15:42
> @buruto I want to ask a question: by "most recent, latest and newest version" do you mean the latest official DOSBox-X x64 SDL2 version (0.83.7), or the latest x64 SDL2 code you built with Visual Studio yourself? If you use the latest x64 SDL2 code with Visual Studio yourself, did you rebuild the code with Visual Studio and then try to load the saved states saved by the earlier x64 SDL2 binary (built for example two days ago)? If so, I think I saw this previously also - in such case the x64 SDL2 binary is not exactly the same, but it is something worth to be address too of course.

I don't have any Visual Studio software installed on my system, machine and computer at all, so I could not modify the source code and then compile it to create new binaries of this DOSBox-X emulator.
But I did use the Visual Studio build of x64 SDL2 DOSBox-X version 0.83.7.

There is also MinGW builds, but I did not use any of these builds at all.
Do you think that the issue is with the Visual Studio builds and I should use any MinGW build instead?

**Comment by MX9000** [comment] 2020-11-09 17:23
@Wengier, If it can help you, I'm having the same issue: a few minutes ago I tried to load a save state created shortly after midnight on November 9th (under 24h) and the emulator crashed suddenly.
Last night the save state was working.
It happens with both SDL1 and SDL2 versions of the latest release.
Thank you.

**Comment by buruto** [comment] 2020-11-09 17:59
> @Wengier, If it can help you, I'm having the same issue: a few minutes ago I tried to load a save state created shortly after midnight on November 9th (under 24h) and the emulator crashed suddenly.
> Last night the save state was working.
> It happens with both SDL1 and SDL2 versions of the latest release.
> Thank you.

@Wengier you see? I am not exaggerating! I am not blind person! I know what I am seeing! I opened this bug issue because I know what I am seeing!

**Comment by Wengier** [comment] 2020-11-09 21:26
@buruto I did not say that the issue reported was wrong. It is simply that it looks somewhat strange, so I was thinking of the possible causes of the problem. Since the issue cannot be reproduced right after the save, I will wait after midnight and see whether the issue will occur on my computer (simply changing the system does not seem to trigger the issue here).. Thanks for reporting it!

**Comment by buruto** [comment] 2020-11-09 23:07
> @buruto I did not say that the issue reported was wrong. It is simply that it looks somewhat strange, so I was thinking of the possible causes of the problem. Since the issue cannot be reproduced right after the save, I will wait after midnight and see whether the issue will occur on my computer (simply changing the system clock does not seem to trigger the issue here).. Thanks for reporting it!

I know @Wengier for one hour old saved state files that were created one hour ago the DOSBox-X emulator does load them properly, but not one day old saved state files that were created one day ago.

I suggest to wait at least 24 hours and then try to load the saved state files again.
Don't forget to both close, exit and terminate the DOSBox-X emulator process before the 24 hours wait!

I both think and believe that the DOSBox-X emulator uses variables that were initialized by the operating system when the process was started when saving state and the "Load state" function needs that the variables in the process memory are equal to these written in the saved state file.

When you launch DOSBox-X emulator again later the memory of the process is different than the previous process and this fails the "Load state" function, because now the variables in memory of the process (initialized by the operating system when the process was created) is different than the variables written in the saved state file.

Think about it. This can explain the sudden crash.

Maybe the data, stack and code segments in the memory of the process are different than these written in the saved state file and "Load state" function assumes that they are not different and it succeeds only if they are not different.

**Comment by Wengier** [comment] 2020-11-11 08:42
Strange that I have not yet been able to trigger the issue here by loading the states I saved yesterday. I am testing with the Visual Studio SDL1 build. Since the crash has not happened yet I am not sure what the exact cause of the problem as you reported is.

**Comment by davy171** [comment] 2020-11-11 15:03
I too, have the same issue. I am using version 0.83.7 SDL1 64bit, Build date Oct 31, 2020 11:52:47pm. I use dosbox to play PC98 games.

**Comment by buruto** [comment] 2020-11-11 17:52
Another user @davy171 reports the same bug issue as both @MX9000 and me.
@Wengier I suggest to wait a little longer and neither modify the time zone nor the clock of your operating system.
Bote make sure, ensure and verify by viewing "Date created" of the saved state files that at least 24 hours has been passed since the time that these saved state files have been created and then attempt to load them all.
Also both make sure, ensure and verify that you did close, exit and terminate DOSBox-X before you started waiting.
Don't let the process of DOSBox-X to live for more than 5 minutes.
The process of DOSBox-X should be terminated after 5 minutes once the saved state files have been created.
I think that the problem is that the memory of the process is reset after you terminate it and then recreate it after 24 hours and with reset memory the "Load state" command fails because the memory of the process is different than the contents of the saved state files that the "Load state" commands has to read from.

**Comment by Wengier** [comment] 2020-11-12 08:30
@buruto According to the current reports I am sure there is some bug in the code, just that it is kind of sneaky (according to your description for example you have to wait for at least 24 hours, and the DOSBox-X process should no live for more than 5 minutes, etc). I think your thesis is possible of course, but we cannot exclude other possibilities either. I will try my best to trigger the bug on my system.

By the way, could you upload the config file you are currently using, just in case it may help to trigger the bug here more easily?

**Comment by buruto** [comment] 2020-11-12 12:12
> @buruto According to the current reports I am sure there is some bug in the code, just that it is kind of sneaky (according to your description for example you have to wait for at least 24 hours, and the DOSBox-X process should no live for more than 5 minutes, etc). I think your thesis is possible of course, but we cannot exclude other possibilities either. I will try my best to trigger the bug on my system.
> 
> By the way, could you upload the config file you are currently using, just in case it may help to trigger the bug here more easily?

Both of course and surely that I can do this!

[x64 Release SDL2](https://pastebin.pl/view/88d55e44)
[x64 Release](https://pastebin.pl/view/8dbc43b6)
[Win32 Release SDL2](https://pastebin.pl/view/694d3c14)
[Win32 Release](https://pastebin.pl/view/8d156f72)

**Comment by buruto** [comment] 2020-11-19 23:51
@Wengier  Did you give up?

**Comment by Wengier** [comment] 2020-11-20 07:05
@buruto No (of course). I have been busy with other features, but I will be back on this.

**Comment by buruto** [comment] 2020-11-21 12:36
> @buruto No (of course). I have been busy with other features, but I will be back on this.

Understood.

**Comment by buruto** [comment] 2020-11-21 23:20
@Wengier By the way, have you read all the pastebins texts that my links refer to already?

**Comment by buruto** [comment] 2020-12-01 23:27
@Wengier How's going?

**Comment by Wengier** [comment] 2020-12-02 09:46
@buruto DOSBox-X 0.83.8 was just released. Enjoy it for now and then get back to do further investigations.

**Comment by buruto** [comment] 2020-12-02 21:07
> @buruto DOSBox-X 0.83.8 was just released. Enjoy it for now and then get back to do further investigations.

Thanks! I am going to try this one!

**Comment by MX9000** [comment] 2021-01-29 09:46
@Wengier, I ran some tests about this bug on Windows 10: I left the computer running for 2 days closing and reopening the emulator several times and loading a save file older than 24 hours and it always worked.
The save file also works after the computer wakes up from standby.
However the emulator crash on loading always occurs after hibernation, reboot or complete shutdown.
The bug seems to be related to the shutdown of the host operating system and not to the time elapsed since the last save.
I hope this information can help to pinpoint the root cause of the issue.
Thanks to all.

**Comment by Wengier** [comment] 2021-01-29 20:45
Great find, @MX9000! I think you are using a 64-bit Visual Studio build. Can you please try MinGW build or 32-bit Visual Studio build and see if the issue also occurs? Thanks!

**Comment by Wengier** [comment] 2021-01-29 20:48
@buruto I believe it has nothing to do with the time elapsed since the last save either, but something else, which was why I was never able to make the issue occur by just waiting for a few days without ever restarting the computer.

**Comment by MX9000** [comment] 2021-01-29 22:05
@Wengier, Yes, I usually run the 64-bit Visual Studio build.
I am downloading the 32/64-bit MinGW and 32-bit Visual Studio builds right now.
Starting tomorrow I will repeat the tests and give you feedback as soon as possible.
Thank you.

**Comment by MX9000** [comment] 2021-01-31 22:39
@Wengier, I just completed the tests you asked for.
You can find the results in the attached file.
By the way, I used the Dangerous Dave game to do the tests.
Thank you.
[Save state crash tests.xlsx](https://github.com/joncampbell123/dosbox-x/files/5900885/Save.state.crash.tests.xlsx)

**Comment by Wengier** [comment] 2021-01-31 23:01
@MX9000 Thanks for the result. So basically the conclusion is that save states in Visual Studio 32-bit SDL1 build and ALL MinGW builds work fine, even after a restart or shutdown. On the other hand, they may not work properly in Visual Studio 64-bit builds or Visual Studio 32-bit SDL2 build.

@buruto I would suggest you to use the Visual Studio 32-bit SDL1 build or any of the MinGW builds, since save states in these builds work without such issues.

**Comment by n-rook** [comment] 2021-08-20 23:33
I can provide supporting evidence for Wengier's theory. I was running "Touhou: Mystic Square" (a PC-98 game) and the 64-bit VS SDL1 build couldn't load old save states. But I have seen no such problems with the 32-bit build.

**Comment by n-rook** [comment] 2021-08-21 03:15
Whoops, just kidding. I'm seeing the same problem with the 32-bit build as well. I'll try the MinGW build next.

**Comment by n-rook** [comment] 2021-09-24 04:03
I've seen this for MinGW as well.

**Comment by yetmorecode** [comment] 2021-12-21 18:44
This is clearly related to #3144. Hard to tell if those crashes reported here are also from saving "render.scale" or from another saved structure. 

Afaik windows randomizes the memory layout on reboot or once a day, thus dosbox will see the same memory layout across restarts for about a day and load old states fine. But after a day the dosbox will get another memory base from windows and save states will corrupt internal pointers on load (as it was with ```render.scale.cacherRead``` in #3144).

In #3144 only the ```render``` part of the state was fixed. I guess I'm gonna give the other parts a look as well.

@Wengier

**Comment by yetmorecode** [comment] 2021-12-21 19:11
A little list where state is saved to track progress:

- [ ]  cpu 
- [ ]  dos
- [ ]  dosbox
- [ ]  gui/midi
- [ ]  gui/render (#3144)
- [ ]  hardware/dma
- [ ]  hardware/memory
- [ ]  hardware/mixer
- [ ]  hardware/pic
- [ ]  hardware/vga
- [ ]  int10
- [ ]  mouse

**Comment by Wengier** [comment] 2021-12-21 23:47
@yetmorecode Great to hear that you have found the cause of the issue, and the progress made so far. You appear to be familiar with the internal structure for the saved states, so please feel free to fix the issues so that the save state feature works even better. I really appreciate it.

**Comment by yetmorecode** [comment] 2021-12-30 09:49
@Wengier @joncampbell123 Ok, I finally finished looking over all the different places where state is saved, and at the moment I can't see anything obvious beyond what we already fixed.

The tickets I referenced above all seem alike or lack further detail to tell if they are different. I would suggest closing them and wait if people keep reporting new issues when loading old states.

**Closed** 2021-12-30 10:06 UTC
Labels: bug, task

**Comment by MX9000** [comment] 2022-01-03 16:08
I have re-tested the game Dangerous Dave with DOSBox-X 0.83.21 and I can confirm that the save state now loads correctly even after restarting or shutting down the computer.
Thanks to all.

**Comment by ChrisNonyminus** [comment] 2022-01-03 22:24
I'm not sure what was changed. I'm on the latest upstream and saving and loading states crashes as usual, with no changes.

**Comment by ChrisNonyminus** [comment] 2022-01-03 22:31
For example, loading states in DOOM crashes the game into this screen: 
![image](https://user-images.githubusercontent.com/50080567/147987487-d71556c1-dfd6-4677-a42a-13408e935383.png)

**Comment by yetmorecode** [comment] 2022-01-04 11:46
@ChrisNonyminus I tried to replicate this with with a doom19 shareware version I found. But so far saving and loading states works for me. Can you provide some more details on how to reproduce this?

Plus, it's not a crash in dosbox itself but in the game. Doesn't mean there isn't a bug, but it'S progress ;)

**Comment by ChrisNonyminus** [comment] 2022-01-04 16:42
> @ChrisNonyminus I tried to replicate this with with a doom19 shareware version I found. But so far saving and loading states works for me. Can you provide some more details on how to reproduce this?
> 
> Plus, it's not a crash in dosbox itself but in the game. Doesn't mean there isn't a bug, but it's progress :)

Just save a state in the title screen, and load it, and then the game crashes as soon as the state loads.

**Comment by superblobster** [comment] 2022-03-10 22:41
Why was this ticket closed? The bug never got fixed. In my case, I'm playing Grand Theft Auto. Yesterday I was using save states just fine. Today, all my previous states cause a hard crash. This happened on previous days as well. I think it only happens if you restart or shut down your computer, which I do every night.
