### ISSUE TITLE
Cannot install Windows 98 on release 2023-10-06

### ISSUE THREAD

**Issue by blindphoneman** [joncampbell123/dosbox-x#4668] opened 2023-12-11 18:26 UTC
### Describe the bug

System hangs when installing Windows 98 on release 2023-10-06.  Tried on release 2023-09-01 and worked properly.

### Steps to reproduce the behaviour

Attempt to install Windows 98 on build 2023-10-06.  After initial file copy and reboot, system hangs on booting drive C: to continue.
![hang](https://github.com/joncampbell123/dosbox-x/assets/45212938/001e48d1-aadc-42b7-8c0f-714a51d97b6a)

### Expected behavior

System should ask for name, company, and serial.
![success](https://github.com/joncampbell123/dosbox-x/assets/45212938/9500dd8a-bf03-4fe6-9c6f-d142aa37599b)

### What operating system(s) this bug have occurred on?

Windows 10

### What version(s) of DOSBox-X have this bug?

2023-10-06

### Used configuration

```ini
[sdl]
autolock=true

[dosbox]
title=Windows 98
memsize=128

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment] 2023-12-11 21:06
Duplicate of #4577.
Close this and refer to the said issue.

**Closed** 2023-12-31 05:11 UTC
Labels: bug
