### ISSUE TITLE
Error in compilation (Arch Linux aarch64)

### ISSUE THREAD

**Issue by sthanduther** [joncampbell123/dosbox-x#5069] opened 2024-06-26 14:56 UTC
I'm trying to compile with "build-debug-sdl2" or "build-sdl2" and after several minutes, I have this error:

```
      |                        ^~~~                                                                      11:36:21 [81/1893]
      |                        |
      |                        spx_word16_t * {aka short int *}
speexdsp/fftwrap.c:102:45: note: expected ‘float *’ but argument is of type ‘spx_word16_t *’ {aka ‘short int *’}
  102 | void spx_fft(void *table, float *in, float *out)
      |                                      ~~~~~~~^~~
speexdsp/fftwrap.c: In function ‘spx_ifft_float’:
speexdsp/fftwrap.c:424:20: error: passing argument 2 of ‘spx_ifft’ from incompatible pointer type [-Wincompatible-pointer-t
ypes]
  424 |    spx_ifft(table, _in, _out);
      |                    ^~~
      |                    |
      |                    spx_word16_t * {aka short int *}
speexdsp/fftwrap.c:120:35: note: expected ‘float *’ but argument is of type ‘spx_word16_t *’ {aka ‘short int *’}
  120 | void spx_ifft(void *table, float *in, float *out)
      |                            ~~~~~~~^~
speexdsp/fftwrap.c:424:25: error: passing argument 3 of ‘spx_ifft’ from incompatible pointer type [-Wincompatible-pointer-t
ypes]
  424 |    spx_ifft(table, _in, _out);
      |                         ^~~~
      |                         |
      |                         spx_word16_t * {aka short int *}
speexdsp/fftwrap.c:120:46: note: expected ‘float *’ but argument is of type ‘spx_word16_t *’ {aka ‘short int *’}
  120 | void spx_ifft(void *table, float *in, float *out)
      |                                       ~~~~~~~^~~
```

and compilation crashes.

**Comment by maron2000** [comment] 2024-06-26 22:01
Duplicate of #4865

**Comment by sthanduther** [comment] 2024-06-27 00:21
Solved.

https://github.com/joncampbell123/dosbox-x/issues/4865

**Comment by maron2000** [comment] 2024-06-27 03:45
That's good news.
You can close solved issues.

**Closed** 2024-09-10 02:37 UTC
