### ISSUE TITLE
GLSL shaders - aspect ratio not being enforced [in full-screen mode]

### ISSUE THREAD

**Issue by almeath** [joncampbell123/dosbox-x#1945] opened 2020-10-12 12:49 UTC
In macOS I can get any SVN compatible GLSL shader to work, but none of them will enforce a 4:3 aspect ratio. 

In either windowed or full screen mode, in any resolution, setting aspect ratio to ‘true‘ is ignored, or is somehow being overridden. 

If I then set the glshader to ‘none’, the 4:3 ratio will be enforced again. 

I tried the pre-compiled 0.83.6 and compiled my own 0.83.7 with the same results, building with either SDL1 or 2.

**Comment by Wengier** [comment] 2020-10-13 19:17
I do not have macOS to test at this time, but in Windows at least setting the following does keep the aspect ratio:

```dosbox-x -set aspect=true -set output=opengl -set glshader=sharp```

**Comment by RuhtraX** [comment] 2020-10-18 23:30
I'm having the same issue on Linux.

Compiled my own 0.83.7 and in both SDL1 and 2 the 4:3 aspect ratio isn't enforced when using a GLSL shader.

Running `dosbox-x -set aspect=true -set output=opengl -set glshader=sharp` didn't work either.

**Comment by Wengier** [comment] 2020-10-20 05:10
Below is the screenshot when I run ```dosbox-x -set output=opengl -set glshader=sharp -set aspect=true -set "title=Aspect ON"``` in Windows:

![image](https://user-images.githubusercontent.com/8216923/96542816-e86c9780-1270-11eb-8b99-86073704edb7.png)

And the screenshot when I run ```dosbox-x -set output=opengl -set glshader=sharp -set aspect=false -set "title=Aspect OFF"```:

![image](https://user-images.githubusercontent.com/8216923/96542846-f7534a00-1270-11eb-9165-02e5348a91dc.png)

Not sure if the issue is platform-specific.

**Comment by rderooy** [comment] 2020-10-20 06:19
From Linux. Note the title bar is missing when you use glshaders.

**SDL1** Aspect true
![Screenshot from 2020-10-20 08-14-53](https://user-images.githubusercontent.com/17701098/96547640-bd079e00-12ac-11eb-9152-82434c652ed9.png)
**SDL1** Aspect false
![Screenshot from 2020-10-20 08-15-39](https://user-images.githubusercontent.com/17701098/96547645-bf69f800-12ac-11eb-9359-acb5becfaefe.png)
**SDL2** Aspect true
![Screenshot from 2020-10-20 08-16-14](https://user-images.githubusercontent.com/17701098/96547648-c133bb80-12ac-11eb-91d3-755b334b50bd.png)
**SDL2** Aspect false
![Screenshot from 2020-10-20 08-16-49](https://user-images.githubusercontent.com/17701098/96547655-c3961580-12ac-11eb-968a-36e882a6ae94.png)

**Comment by RuhtraX** [comment] 2020-10-20 12:41
Well, I just realized I didn't mention a very important information 😅

This problem happens when going fullscreen.

**Comment by rderooy** [comment] 2020-10-20 14:04
It seems you right, here is what I get on Linux Wayland with the SDL1 binary with aspect=true

![Screenshot from 2020-10-20 15-46-46](https://user-images.githubusercontent.com/17701098/96596063-9b2e0b80-12ec-11eb-96f0-95ed85342608.png)

And with Aspect=false
![Screenshot from 2020-10-20 15-47-47](https://user-images.githubusercontent.com/17701098/96596087-a2551980-12ec-11eb-9f1a-d4156c38f765.png)

Basically the dosbox-x screen gets stretched to my host pc screen size, ignoring the aspect ratio.

In addition there is an input focus problem. My keyboard input is still going to the terminal from where I launched dosbox-x. So I cannot type anything in dosbox-x. Pressing Ctrl-C will terminate dosbox-x, since input was still at the terminal.

With the SDL2 binary, things are not better. When starting dosbox-x, I get a momentary flash, which I think is supposed to be the dosbox-x loading animation, but not recognisable. And after that, all I get is a black screen. Ctrl-C will not kill the process, but I can Alt-Tab to another window. dosbox-x is really hanging at this point, as even at the originating console, pressing CTRL-C (SIGTERM) does nothing. Sending a SIGKILL however does the trick.

**Comment by almeath** [comment] 2020-10-20 20:30
In macOS the 4:3 ratio will be enforced in windowed mode. It is only in fullscreen that `-set aspect=false` has no effect.

**Comment by almeath** [comment] 2020-10-20 20:43
I am having other problems with SDL though. My desktop resolution is 5120x2880. My configuration is:

```
-set fullscreen=true
-set aspect=false
-set output=openglnb
-set glshader=sharp
```

As mentioned above, setting `aspect` to either true or false has no effect when using a shader setting other than none.

Despite my native desktop resolution, I see the following in the terminal output:

```
LOG: DOSBox-X version 0.83.6 (macOS SDL1)
LOG: macOS EXE path: /Users/almeath/Desktop/DOSBox-X wrapper.app/Contents/Resources/dosbox/DosBox
LOG: macOS Resource path: 
LOG: macOS: NSTouchBar support detected in system
LOG: Host keyboard layout is now us (US English)
LOG: Mapper keyboard layout is now us (US English)
LOG: SDL1 auto-detected desktop as 2560 x 1440
LOG: The default output for the video system: opengl
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (599.300 x 340.242 mm) (23.594 x 13.395 in) (108.500 x 107.500 DPI)
LOG: ISA BCLK: 8333333.333Hz (25000000/3)
LOG: monopal: green, 
LOG: Active save slot: 1 [Empty]
LOG: USING AVI+ZMBV
LOG: Max 3670016 sz 16384
LOG: Final 16384
LOG: MIDI:Opened device:coreaudio
LOG: Pentium CMPXCHG8B emulation is enabled
LOG: VOODOO LFB now at d0000000
LOG: MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
LOG: Screen report: Method 'CoreGraphics' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (599.300 x 340.242 mm) (23.594 x 13.395 in) (108.500 x 107.500 DPI)
LOG: Allocated APM BIOS pm entry point at f000:e86c
LOG: Writing code to fe86c
LOG: Screen report: Method 'CoreGraphics' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (599.300 x 340.242 mm) (23.594 x 13.395 in) (108.500 x 107.500 DPI)
LOG: ISA Plug & Play BIOS enabled
LOG: VGA ROM BIOS init callback
LOG: pixratio 1.000, dw false, dh false
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (599.300 x 340.242 mm) (23.594 x 13.395 in) (108.500 x 107.500 DPI)
LOG: Screen report: Method 'CoreGraphics' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (599.300 x 340.242 mm) (23.594 x 13.395 in) (108.500 x 107.500 DPI)
LOG:    2863299 ERROR BIOS:Keyboard layout file auto not found
LOG:    2863299 ERROR BIOS:Keyboard layout file auto not found
LOG: XMS: 50 handles allocated for use by the DOS environment
LOG: EMS page frame at 0xe000-0xefff
LOG: COMMAND.COM env size:             720 bytes
LOG: COMMAND.COM environment block:    0x0701 sz=0x002d
LOG: COMMAND.COM main body (PSP):      0x072f sz=0x009a
LOG: COMMAND.COM stack:                0x0749
LOG: pixratio 1.350, dw false, dh false
LOG: Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
Unable to obtain graphics context for NSWindow (Mojave behavior)
LOG: Screen report: Method 'CoreGraphics' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (599.300 x 340.242 mm) (23.594 x 13.395 in) (108.500 x 107.500 DPI)
LOG: Screen report: Method 'CoreGraphics' (2560.000 x 1440.000 pixels) at (0.000 x 0.000) (599.300 x 340.242 mm) (23.594 x 13.395 in) (108.500 x 107.500 DPI)

```

**Comment by rderooy** [comment] 2020-10-20 21:03
This should have nothing to do with the aspect ration. But regarding the resolution, DOSBox-X is reporting half your true resolution. There are others that have reported DPI problems with macOS. There is a ``dpi aware`` setting that you may want to test with.

**Comment by Wengier** [comment] 2020-10-21 03:43
I think I can confirm the aspect ratio issue in full-screen mode. Will add it to todo list.

On the other hand, I cannot reproduce the input focus problem on my Windows machine or Linux VM so far, which I believe is likely unrelated to the aspect ratio issue by the way.

**Comment by almeath** [comment] 2020-10-21 04:26
OK, I might lodge a separate report for that issue. I tried changing dpi aware to on, off and auto, and every time I get the same output in macOS terminal that indicates only half my native resolution is being detected. I have not tested this in SDL2 yet.

**Comment by psoma** [comment] 2020-10-23 04:58
Getting the same issue here on latest Windows build - 1920x1080 desktop resolution, openglnb, fullscreen, apect=true.... screen is stretched horizontally. Not a Mac or Linux specific bug.

**Comment by Wengier** [comment] 2020-10-23 20:10
@psoma Yes, I can confirm it in Windows too, but only in full-screen mode. The title has been updated accordingly to mention "in full-screen mode".

**Comment by Wengier** [comment] 2020-10-23 20:11
@almeath Sure, you can make a separate report for that issue.

**Comment by Wengier** [comment] 2020-10-26 03:51
I think it is hopefully fixed in the latest code. Thanks everyone for reporting it.

**Comment by RuhtraX** [comment] 2020-10-26 12:26
I can confirm it's working now.
Here's a screenshot on Linux SDL2 
```
-set fullscreen=true
-set aspect=true
-set output=openglnb
-set glshader=crt-lottes-fast.subtle+gain
```
![crt-lottes-fast](https://user-images.githubusercontent.com/12171146/97171797-eed5a480-1785-11eb-817a-792fc4ca5b75.png)

**Comment by Wengier** [comment] 2020-10-26 22:45
@RuhtraX I am glad to hear that.

**Comment by almeath** [comment] 2020-10-27 05:28
Happy to report that it is also working properly in macOS, with both SDL1 and SDL2. Thanks @Wengier for your quick response.

**Closed** 2020-10-27 17:40 UTC
Labels: bug, task, topic: video
