### ISSUE TITLE
'Packed file is corrupt' error

### ISSUE THREAD

**Issue by CriusMacOldenly** [joncampbell123/dosbox-x#416] opened 2017-12-27 06:25 UTC
When trying to run many games, I get an error 'Packed file is corrupt'. This is not a new problem with dosbox-x, however, dosbox runs the games perfectly, so it is a problem with some change that dosbox-x has compared to the original dosbox.

**Comment by CriusMacOldenly** [comment] 2017-12-27 06:32
This problem may be the same problem as referenced in https://github.com/joncampbell123/dosbox-x/issues/7 .

**Comment by joncampbell123** [comment] 2017-12-27 06:39
This is a duplicate of #7. This happens when the game is loaded too low in memory, which can also be the case on real systems running MS-DOS 5.0 and higher.

**Closed by joncampbell123** 2017-12-27 06:39 UTC
