### ISSUE TITLE
Direct3d Pixel Shaders & Scaler won´t work

### ISSUE THREAD

**Issue by Starfoxfs** [joncampbell123/dosbox-x#3316] opened 2022-03-06 10:25 UTC
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 11 21H2

### What version(s) of DOSBox-X have this bug?

Dosbox-X 0.83.23 SDL2 Visual Studio Win64

### Describe the bug

The Direct3D Pixel Shaders and the Scaler will not work in Dosbox-X 0.83.23 SDL2 64bit Visual Studio Build.

### Expected behavior

OpenGL and OpenGL Shaders work.

Scaler have no effect
Direct3d Pixel Shader have no effect

### Steps to reproduce the behaviour

1. Start Dosbox-X
2. Pixel Shaders stored in shaders Directory
3. Select Direct3D as Output in Video Menue
4. Select D3D Pixel Shader in Video Menue

### Used configuration

```ini
Output = direct3d


frameskip      = 0
aspect         = false
char9          = true
euro           = -1
doublescan     = true
scaler         = normal2x
glshader       = none
pixelshader    = none
autofit        = true
monochrome_pal = green

and 

frameskip      = 0
aspect         = false
char9          = true
euro           = -1
doublescan     = true
scaler         = normal2x
glshader       = none
pixelshader    = ColorSketch.fx
autofit        = true
monochrome_pal = green
```

**Comment by Starfoxfs** [comment] 2022-03-09 08:18
Update: Shaders works if Doublescan is disabled, but Direct3d Pixel Shaders still don't work.

**Comment by maron2000** [comment] 2022-03-09 13:23
According to the source code, it uses `D3DXCreateEffectCompilerFromFile` function [(link).](https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dxcreateeffectcompilerfromfile)
It requires d3dx9 library so I think you need to install Direct X9 runtime to work on Windows10 and 11. 

```cpp
// cited from ScalingEffect.cpp
// First create an effect compiler
    HRESULT hr = D3DXCreateEffectCompilerFromFile(filename, NULL, NULL, 0,
						&lpEffectCompiler, &lpErrors);
```
Shaders work fine on my Windows8.1 PC. 
This issue is a duplicate of https://github.com/joncampbell123/dosbox-x/issues/2884

**Comment by Starfoxfs** [comment] 2022-03-09 13:59
Hi,
ok thanks for the Info. I don´t know that it needs Directx9

**Closed** 2022-04-29 01:28 UTC
Labels: bug
