### ISSUE TITLE
NWT 1.3 ("NewWadTool", a utility for Doom) can not play music

### ISSUE THREAD

**Issue by Dwedit** [joncampbell123/dosbox-x#3361] opened 2022-03-27 20:49 UTC
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 (Version 10.0.19043.1586)

### What version(s) of DOSBox-X have this bug?

0.83.23

### Describe the bug

NWT.EXE - NewWadTool 1.3 (1995) - is a historical tool for editing Doom.  Among its features is a music player, which will play the music files of Doom.

But if you attempt to play the music on DosBox, it only plays the first note, and does not proceed past that point.

It does work correctly on other PC emulation software, such as PCEM.

### Expected behavior

Music should play correctly, but it doesn't.  It gets stuck on the first note and doesn't proceed.

### Steps to reproduce the behaviour

NWT is available from https://www.doomworld.com/idgames/utils/graphics_edit/nwt103, and it requires a full version of Doom, Doom 2, or Heretic.
It will not work on the shareware version of Doom.

Steps:

* Install Doom/Doom 2/Heretic
* Put NWT.EXE in the same directory
* Run NWT
* Within NWT, type "genmidi" so its search feature will find it
* Press F2 to Export RAW, save the file as "genmidi.op2".  NWT's music player requires this file to play music.
* Erase your search query by hitting backspace a bunch of times
* Type "D_" so it will be at a song, then pick a song to play
* Press Enter to attempt to play the song

**Comment by grapeli** [comment] 2022-03-27 21:46
I confirm.
It just has to be a regression. Because in dosbox-x 0.83.17, it plays as it should. In version 0.83.21, not anymore.

**Comment by grapeli** [comment] 2022-03-27 23:15
After making this code change 7c6d04bf CMOS timing improvements, nwt stops playing music.
A few commits after dosbox-x 0.83.18 was released.

**Comment by Wengier** [comment] 2022-03-28 04:14
I think @Allofich may want to look at this.

**Comment by maron2000** [comment] 2022-03-28 09:19
Hi, it seems that resetting the Status Register C after reading it is not working as intended.
(although the data sheet of MC146818A mentions that it will be reset)

I put a test fix in my repository 039920574a06fed1d8234ac1494e75a0b7c65c47, skipping the reset of the said register plus some minor fixes.
May be helpful to fix this issue. 
(Apologies for the not well arranged fix such as lots of logs, I just played around rather than preparing a PR)

You can find the automated builds below.
https://github.com/maron2000/dosbox-x-1/actions?query=branch%3Acmos+is%3Asuccess

**Comment by grapeli** [comment] 2022-03-28 09:52
@maron2000
I tested your fix and confirm it fixes the mentioned sound problems in NWT.

**Comment by grapeli** [comment] 2022-03-28 13:16
@maron2000 
I would wait for the opinion of the author of this change. Hope he's still interested in this code.

**Comment by Wengier** [comment] 2022-03-29 04:48
It is hopefully fixed by #3364.

**Comment by Allofich** [comment] 2022-03-29 06:03
> @maron2000
> I would wait for the opinion of the author of this change. Hope he's still interested in this code.

I am fine with it if it fixes this issue. I am not an expert on CMOS timing or anything like that, I just referred to the data sheet.

**Comment by Allofich** [comment] 2022-03-29 06:36
Trying @maron2000's build above, it looks like this it undoes a possible fix of the code changes I made, which was to slow down the temp of music in the game "Contraption Zack".

I don't actually know what speed the music of Contraption Zack is supposed to play at, as I don't have real hardware to test on. Subjectively, it seemed too fast before my changes (see https://github.com/joncampbell123/dosbox-x/pull/2959 for the comparison) and in @maron2000's build above, it has returned to that faster tempo.

Another game that had its music timing affected by my code change was "Beverly Hillbillies". I haven't tried it with @maron2000's build but I expect it is also back to the earlier, faster tempo.

Anyway, I'm still OK with this change, if it fixes the NWT 1.3 issue.

**Comment by maron2000** [comment] 2022-03-29 06:40
@Allofich Thanks for your comments
I haven't tested yet, but it seems that @cimarronm 's patch is the minimum to be happy enough. 
We have to confirm whether there are side effects, as you mentioned.

**Comment by Allofich** [comment] 2022-03-29 06:49
"Contraption Zack" also came out for Amiga. At the time of https://github.com/joncampbell123/dosbox-x/pull/2959 I couldn't find any videos of the Amiga version, but there has since been a YouTube video of the Amiga version put out. https://www.youtube.com/watch?v=uw6grSLhaF4
In the video, the tempo matches the faster tempo seen in DOSBox, so maybe that was the correct one after all. Although, the title music of the Amiga version sounds rather goofed up, so I think it's playing on an emulator, and there is also the issue of NTSC and PAL with the Amiga (games playing too fast or too slow if not played with the correct timing).

**Comment by Allofich** [comment] 2022-03-29 06:52
> I haven't tested yet, but it seems that @cimarronm 's patch is the minimum to be happy enough rather than changing so much as in mine.

Oh, I thought your build and @cimarronm's patch were with the same code. I haven't tested @cimarronm's patch. Regardless, whether or not the tempo changes with @cimarronm's patch, I've no problem with it if it fixes this or other issues.

**Closed** 2022-03-29 08:08 UTC
Labels: bug
