### ISSUE TITLE
SmartKey 6.0g "Supershift" key not working in 0.83.16

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#2770] opened 2021-08-06 23:56 UTC
**UPDATE: Problem does _not_ exist if I use SDL2.**

I run DOSBox-X SDL1 on a 32-bit Dell Windows 7 Pro computer.

I have long used the 1990 keyboard-macro program SmartKey 6.0g from FBN Software. It features a user-definable "Supershift" key that can be used to precede any other keyboard key (alphanumeric, function key, cursor key, etc.) to turn the second key into a separate macro.

My Supershift key is the backtick or single open quote (`), so that typing, for instance, `e (backtick, e) inserts i (e-accent-grave). This worked flawlessly through DOSBox-X release 0.83.15 (July 2021), but something has changed in 0.83.16 (August 2021). Now, the first and only the first invocation of a Supershift-prefixed macro works; after that, the Supershift key either repeats endlessly (```````` ...) or simply becomes a dead key, doing nothing. (In fact, the shift state of the key does nothing, either: neither backtick nor tilde, which is shift-backtick, do anything.)

It makes no difference what key I select for my Supershift key (that is, this is not a backtick-specific problem); it makes no difference whether I use LOADHIGH with Smartkey or allow it or not to use EMS.

My DOSBox-X.config file is attached as DOSBox-X.config.txt; also attached is a ZIP file with the SmartKey program and utilities.

I love DOSBox-X, and thank you VERY much for all your hard work!

Robert J. Sawyer, Toronto

[dosbox-x.conf.txt](https://github.com/joncampbell123/dosbox-x/files/6948293/dosbox-x.conf.txt)

[SmartKey.zip](https://github.com/joncampbell123/dosbox-x/files/6948301/SmartKey.zip)

**Comment by maron2000** [comment] 2021-08-07 03:00
I don't know from when but it seems that SDL1 doesnt return KEYUP event when grave key is pressed (and released).
I check the log by adding a line to SDLmapper.cpp, and the event->type was 2 (KEYDOWN) twice when I pressed grave key. (I changed my keyboard settings from JP to US beforehand)
Other keys returns 2 and then 3 (KEYDOWN, and then KEYUP), which is as expected.
So maybe SmartKey doesn't affect this issue.
I couldn't build in the latest commit with VS2019, so I reverted to dcc7c9891cd4311fb16155d7dc70002da92933ed to test.

Adding a line in CheckEvent() function.
```
 LOG_MSG("event->type=%x", event->type);   // <-- Add this line
 if (event->type==SDL_KEYDOWN) ActivateBindList(&lists[key],0x7fff,true);
 else DeactivateBindList(&lists[key],true);
 return 0;
```

**Comment by maron2000** [comment] 2021-08-08 13:05
@RobertJSawyer I guess I found where it forces the KEYDOWN event. (Around Line 8290 of `sdlmain.cpp`)
If you can build by your own, can you try it?

@Wengier @nanshiki I don't know if the fix below will affect IME support. Would you please check it?
```
#if defined(WIN32) && !defined(HX_DOS) && defined(SDL_DOSBOX_X_SPECIAL)
            if(event.key.keysym.scancode == 0x70 || event.key.keysym.scancode == 0x94 || event.key.keysym.scancode == 0x29) {
                if((event.key.keysym.scancode == 0x94 || event.key.keysym.scancode == 0x29) && dos.im_enable_flag) {
                    break;
                }
                //event.type = SDL_KEYDOWN;  //<-- Comment out this line (Temporary fix, not thoroughly tested)
            }
#endif
```

**Comment by RobertJSawyer** [comment] 2021-08-08 17:05
@maron2000, thank you so much! Building my own version is beyond my capabilities; I'm just a writer. ;)  But I look forward to seeing if the next official build addresses this. Thank you again!

**Comment by nanshiki** [comment] 2021-08-09 01:57
This process was a countermeasure for the fact that IME-related key events (SDL_KEYUP/SDL_KEYDOWN) are different from normal.
The above phenomenon seems to be caused by the fact that the Hankaku/Zenkaku key and the Super Shift key have the same scancode.
Can you please fix it so that this process is executed only when the IME is enabled, as shown below?
``` cpp
#if defined(WIN32) && !defined(HX_DOS) && defined(SDL_DOSBOX_X_SPECIAL)
    if(dos.im_enable_flag) {
        if(event.key.keysym.scancode == 0x94 || event.key.keysym.scancode == 0x29) {
            break;
        } else if(event.key.keysym.scancode == 0x70) {
            event.type = SDL_KEYDOWN;
        }
    }
#endif
```

**Comment by nanshiki** [comment] 2021-08-21 06:19
@RobertJSawyer  @maron2000 
#2822 to fix it.
The problem of multiple backtick key when IME is not used has been confirmed, and it has been fixed after this fix.

**Comment by RobertJSawyer** [comment] 2021-08-21 18:56
This is wonderful! Thank you SO much!

**Comment by Wengier** [comment] 2021-11-07 03:53
Closing since it had been fixed.

**Closed by Wengier** 2021-11-07 03:53 UTC
