### ISSUE TITLE
Scaling does not work

### ISSUE THREAD

**Issue by feklee** [joncampbell123/dosbox-x#96] opened 2015-06-12 17:00 UTC
sdl configuration:

```
fullscreen=false
fulldouble=true
fullresolution=original
windowresolution=1600x1200
output=opengl
autolock=false
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74.map
usescancodes=true
```

For `output` I also tried `overlay` and `openglnb`, to no avail: Scaling doesn't work. Scaling works with the current official stable DOSBox, but that has other issues.

`uname -a`: `Linux t550 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux`

**Comment by willstdueswissen** [comment] 2015-10-20 07:54
Its also not work on:
Microsoft Windows 10 Pro
10.0.10240 Build 10240

**Comment by Lordmau5** [comment] 2016-02-16 13:27
Can confirm this problem still exists on Windows 7 x64.
Whatever output mode I set, it's not stretching it to the whole screen when in fullscreen mode.

**Comment by joncampbell123** [comment] 2016-02-16 16:52
I'm not familiar with the fullscreen and stretching code, especially where Windows is concerned.

**Comment by Lordmau5** [comment] 2016-02-16 17:02
Oh, alright...
I strongly wonder why it would work in the original DOSBox though and not in this one :( ?

**Comment by joncampbell123** [comment] 2016-02-16 17:06
I'm not going to close this issue, I'm just pointing out I'm not likely to fix it soon because I'm not familiar enough to work on it without possibly breaking it further.

**Comment by aybe** [comment] 2016-05-06 21:17
Scaling does work when specified in config but cannot be changed while running.

It happens in RENDER_Init but not sure what it takes to trigger this again and how it should be done (it's only called once in main())

**Comment by GuestComment** [comment] 2017-08-20 14:41
I just want to re-confirm that scaling doesn't work with DOSBox-X, while it does work in DOSBox 0.74.

I can also add that the DOS-window is actually being scaled initially, but once a game is launched, the window is resized to original size instead of the scaled size. I hope this might help in determining where the bug has been introduced.

**Comment by aybe** [comment] 2017-08-20 18:29
By debugging it a bit, I think I've found the cause but I'm unable to fix it because of lack of VGA knowledge ...

Here this will not be hit when what I think a program uses doublescan (Prince of Persia, 320x400, isn't the game 320x200 ?):
https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/render.cpp#L337

Here this block has been added compared to original DOSBOX, but removing it breaks the whole thing:
https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/render.cpp#L638

Here it's radically different from original DOSBOX in the sense that doubling is passed here VS computed locally:
https://github.com/joncampbell123/dosbox-x/blob/master/src/hardware/vga_draw.cpp#L1561

Original DOSBOX reference:
https://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/trunk/src/gui/render.cpp#l260
https://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/trunk/src/gui/render.cpp#l516
https://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/trunk/src/hardware/vga_draw.cpp#l1033

IMO the problem stems from a more subtle topic: feature creep

As people keep on piling things up without really caring, this is how you end up over time : a total mess. The real issue (IMO) in DOSBOX is the lack of communication between coders, resulting in a big, hard if not impossible to maintain code base.

If you look closely, there are many parts where laziness won in favor of clarity, cleanliness : copy/paste, hacks below some code just for not cleaning up what's above and so on ...

Quite some time ago, I rolled out what I think was [a good patch for joysticks esp. for XBOX360 controller](https://github.com/joncampbell123/dosbox-x/blob/joystick/README.joystick), guess what, never got a reply and obviously it's never been merged. It was off by default (non-intrusive) so didn't affect original behavior, it just had to be merged, now it's almost ~300 commits behind and won't merge.

So (IMO) the communication part is really what affects the advancement of the project and bug-fixing, e.g. the original DOSBOX hasn't seen a release in 7 years, yet they are piling things up in SVN, I mean what are these persons, can't they communicate with each other ?

Sorry about that, I love DOSBOX but lost faith in it when I started contributing, today I simply launch the good old Daum release and enjoy a good old game instead !

**Comment by joncampbell123** [comment] 2017-08-21 23:42
I agree the code is a mess. I do try to spend some DOSBox-X dev time cleaning it up over time, which is why much of the code now differs from DOSBox SVN now, but there's still a lot of mess over time.

I can put some effort into the Linux side of scaling bugs, but I'm going to need someone to take on the Windows side of development. I'll stay in communication for that phase. Interested?

**Comment by joncampbell123** [comment] 2017-08-21 23:43
It's not just feature creep that's the problem, it's the often crude hacks that have been added over time to add features. If the code was more organized, adding features wouldn't weaken the stability any.

**Comment by aybe** [comment] 2017-08-23 21:38
If it's for ensuring that Windows builds then why not, IMO if OpenGL could become the default output, then a bunch of code could be simply deleted as most scalers are already available as shaders (Retroarch).

Other than that I'm wondering why people are not sticking to simply be a branch of the original version ? You would get all the updates and eventually have a chance to merge your additions. Or are the devs in the original project benevolent dictators ? :)

Life is not perfect I know but what is the point of forking when there are too many of them, at best it just becomes confusing for end-users.

**Comment by Jarvik7** [comment] 2017-08-24 00:25
Basically, mainline refuses to accept most patches, particularly if they do not directly improve gaming (such as patches that improve booting windows). Considering how stagnant mainline is, -X should be considered the new mainline.

**Comment by aybe** [comment] 2017-08-24 03:17
That's what I concluded ... anyway, started improved Windows things a bit (sorry for the anarchic commits) and hopefully we'll advance a bit on the other topics -> opening another topic for this.

**Comment by joncampbell123** [comment] 2017-08-24 03:32
Patches are welcome. I won't be able to work on DOSBox-X for the next week or so because of my professional programming job and a big client.

@aybe I'm all for OpenGL by default since everything these days has some sort of GPU in it. But I want to make sure the code can always fall back to a non-OpenGL renderer to accomplish display and resizing. I have a good RGB bitmap scaler routine (with bilinear interpolation) on hand that can also work with MMX, SSE, and AVX to render quickly. I'm always hesitant to make OpenGL a requirement for the code because that's a rather large dependency to attach the emulator to, especially on Linux where OpenGL is provided by the massive MesaGL library.

I've envisioned making the code easily compatible with both if rendering were done with a very simple layout engine that translates to either OpenGL or software rendering.

**Comment by aybe** [comment] 2017-08-24 03:52
Sounds good,

I'm too busy with daily things, maybe the best we can do until is *discuss* about things and see what emerges then -> https://github.com/joncampbell123/dosbox-x/issues/286

**Comment by sikthehedgehog** [comment] 2017-08-24 08:57
Late but

> Other than that I'm wondering why people are not sticking to simply be a branch of the original version ? You would get all the updates and eventually have a chance to merge your additions. Or are the devs in the original project benevolent dictators ? :)

> Basically, mainline refuses to accept most patches, particularly if they do not directly improve gaming (such as patches that improve booting windows). Considering how stagnant mainline is, -X should be considered the new mainline.

Yeah, DOSBox is _still_ stuck in 0.74, and the last update in the site is from 2013 too. It pretty much screams of dead project to me :/ I pretty much already consider DOSBox-X to be the new main branch (especially since it's focusing on accuracy which seems to match the path emulators for older consoles have been going)

**Comment by GuestComment** [comment] 2017-08-24 09:04
I'm sorry that I can't contribute, but I do want to express my appreciation and gratitude for all of you taking a fresh look at this. Thanks everyone! :-)

**Comment by aybe** [comment] 2017-08-24 17:24
It's being updated actually : https://sourceforge.net/p/dosbox/code-0/commit_browser but I've read somewhere they don't plan another public release, go figure why.

This is a recurrent problem in OSS, most leads become so rigid over time that you can barely discuss with them if you're a newcomer.

Reminds me of a eduke32 fork I made for correct XInput and shared in a forum thread, thing hasn't been fixed in 10 years, yet the guy found nothing better than talking about my tabs and spaces, OTOH users were happy because they could finally enjoy playing with their x360 controller. i.e. it's all about politics in the end ...

**Comment by martinlindhe** [comment] 2017-09-11 12:16
Scaling was fixed in https://github.com/joncampbell123/dosbox-x/pull/254

**Comment by GuestComment** [comment] 2017-09-11 12:40
I don't think #254 fixes scaling in windowed mode too. But maybe the solution can provide clues as to what is needed to get scaling working in windowed mode.

**Comment by martinlindhe** [comment] 2017-09-11 14:17
@GuestComment you might be right! I only used it in fullscreen

**Comment by aybe** [comment] 2017-09-14 10:07
What is happening is a bunch of conditions for programs using doublescan, they are all defaulted to the  scaler that implements it:

https://github.com/joncampbell123/dosbox-x/blob/0512852b1668bb4d29dc9ea978ddffe395d20f38/src/gui/render.cpp#L337

Like the DOS prompt will work fine with any scaler but not Prince of Persia which while it's 320x200 requests 320x400 mode ... Since it would be silly to extend scalers with double width/height flavors, I'm waiting for the new renderer, or alternatively a shader approach which would considerably simplify the whole thing.

**Comment by joncampbell123** [comment] 2018-08-31 20:06
The scaler system will not trigger unless something triggers doubling the screen, or you force the scaler.

The xBRZ scaler does not have this limitation.

One way to trigger the doubling case is to disable "doublescan" mode and then run a game that uses 320x200 graphics modes.

**Closed by joncampbell123** 2018-08-31 20:06 UTC
Labels: bug, topic: video
