### ISSUE TITLE
MMCMP 1.30 crashes DOSBox-X

### ISSUE THREAD

**Issue by sagamusix** [joncampbell123/dosbox-x#2549] opened 2021-05-24 16:28 UTC
**Describe the bug**
Trying to compress or uncompress a module file with [MMCMP 1.30](https://files.scene.org/view/resources/music/utils/mmcmp130.zip) crashes DOSBox-X (and also vanilla DOSBox).

**To Reproduce**
1. Download [a module file](https://modarchive.org/module.php?60395)
2. Run `mmcmp.exe 2nd_pm.s3m`
3. Observe that DOSBox-X crashes.

**Expected behavior**
File should be processed as expected, and definitely not crash the emulator.

**Environment (please complete the following information):**
 - Operating system : Windows
 - DOSBox-X release version: 0.83.12

**Additional context**
MMCMP 1.34 doesn't crash in DOSBox. But I need to run this specific version to test something. Of course it's possible that the program is generally faulty, but either way it should not result in DOSBox crashing.

**Comment by Wengier** [comment] 2021-05-24 20:35
I can confirm the crash with MMCMP 1.30:

![image](https://user-images.githubusercontent.com/8216923/119404281-962fa100-bcad-11eb-8aac-41acf8524701.png)

When the program runs the CPU goes to the protected mode, but the gate type 1 is not supported by the CPU_Interrupt() function. On the other hand, MMCMP 1.34 works fine as you said.

**Comment by sagamusix** [comment] 2021-05-24 20:36
I can also confirm that MMCMP 1.30 runs fine on Windows XP 32-bit (inside a VM).

**Comment by Wengier** [comment] 2021-05-24 22:33
It does works in a real MS-DOS system, and the issue is related to the CPU code. @joncampbell123 may know the best (and most accurate) way to solve this.

**Comment by joncampbell123** [comment] 2021-05-26 07:05
Why is INT 21h a 286 Task State Segment, then?

![image](https://user-images.githubusercontent.com/6245486/119616957-1b9e7880-bdb6-11eb-9f29-23ce678fa3db.png)

**Comment by joncampbell123** [comment] 2021-05-26 07:46
So, here's about where the problems lie.

Not 100% sure but it might be flawed code that uses protected mode only to try to set up "flat real mode", or at least set FS and GS to 4GB segment limits in real mode.

    0823:00000993 0F01E2              smsw dx
    0823:00000996 F7C20100            test dx,0001
    0823:0000099A 7529                jne  000009C5 ($+29)        (no jmp)
    0823:0000099C 6633C0              xor  eax,eax
    0823:0000099F 8CD8                mov  ax,ds
    0823:000009A1 66C1E004            shl  eax,04
    0823:000009A5 660106A400          add  [00A4],eax             ds:[00A4]=000000A8
    0823:000009AA 0F0116A200          lgdt word [00A2]            ds:[00A2]=000F
    0823:000009AF 66678D4201          lea  eax,[edx+0001]         [illegal]
    0823:000009B4 0F01F0              lmsw ax
    0823:000009B7 EB00                jmp  short 000009B9 ($+0)   (down)
    0823:000009B9 B80800              mov  ax,0008
    0823:000009BC 8EE0                mov  fs,ax
    0823:000009BE 8EE8                mov  gs,ax
    0823:000009C0 0F01F2              lmsw dx
    0823:000009C3 EB00                jmp  short 000009C5 ($+0)   (down)
    0823:000009C5 C3                  ret

**Comment by joncampbell123** [comment] 2021-05-26 07:49
It's obvious the program is storing the machine status word (which is the same as the low 16 bits of CR0), then loading it to enter 16-bit protected mode, load FS and GS, then loading the original machine status word to reenter real mode.

As far as I can tell in the debugger, DOSBox-X still thinks it's 16-bit protected mode even though LMSW DX loads a DX value with bit 0 cleared which SHOULD exit protected mode.

**Comment by joncampbell123** [comment] 2021-05-26 07:51
So then... at some point, Intel allowed LMSW to clear the bit, or maybe the program was written for non-Intel x86 processors. Perhaps 486 and Pentium systems allowed it (I noticed the program executable has a date within the year 1996).

**Comment by joncampbell123** [comment] 2021-05-26 07:56
DOSLIB task: https://github.com/joncampbell123/doslib/issues/54

**Comment by joncampbell123** [comment] 2021-05-26 08:13
Here's a workaround:

MMCMP has code to detect if the CPU is in Virtual 8086 mode, and it will skip the "flat real mode" code if it detects it.

Try adding this to your dosbox.conf:

[dos]
ems=emm386
emm386 startup active=true

Expanded (EMS) memory emulation runs in a manner similar to EMM386.EXE. The "emm386 startup active" option tells EMS emulation to run the whole DOS environment under Virtual 8086 mode. There is even an incomplete VCPI implementation in place (that most DOS extenders are not happy with yet).

**Comment by joncampbell123** [comment] 2021-05-26 17:06
According to the Intel 386 Programmer's Reference Manual, LMSW is not supposed to let you exit protected mode.

https://nas.jmc/jmcs/docs/browse/Computer/Platform/PC%2c%20IBM%20compatible/CPU/80386/Intel/Intel%2080386%20Programmer%27s%20Reference%20Manual%20%281986%29%2etxt

![Firefox_Screenshot_2021-05-26T17-05-52 676Z](https://user-images.githubusercontent.com/6245486/119702190-094e2a00-be0a-11eb-8369-636659335f67.png)

**Comment by joncampbell123** [comment] 2021-05-26 17:14
But.... I don't see any such remarks in the 486DX programmer's guide. Maybe Intel dropped the set-only behavior for the PE bit starting with the 486. Maybe not.

![Firefox_Screenshot_2021-05-26T17-13-27 472Z](https://user-images.githubusercontent.com/6245486/119703240-32bb8580-be0b-11eb-841e-d8aaf7a04092.png)
![Firefox_Screenshot_2021-05-26T17-13-11 005Z](https://user-images.githubusercontent.com/6245486/119703246-33ecb280-be0b-11eb-93e3-c38758c28651.png)

**Comment by sagamusix** [comment] 2021-05-26 17:17
I guess it wouldn't be too unlikely that the program was indeed never able to run on 386s. Version 1.0 was also released in 1996, most people probably were on 486s or Pentiums at that point.

**Comment by joncampbell123** [comment] 2021-05-26 22:57
The latest commit adds an option to allow/disallow LMSW to clear the PE bit, or "Auto" to pick based on CPU type (486 or higher). The commit at this stage is an educated guess, but it allows MMCMP.EXE to run without crashing.

**Comment by Wengier** [comment] 2021-05-26 23:09
I can confirm that MMCMP 1.30 works fine with the least code. The Windows binaries based on the latest code are available below in case @sagamusix wants to test the latest pre-compiled builds:

* Visual Studio SDL1 build: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Visual Studio SDL2 build: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by sagamusix** [comment] 2021-05-27 18:05
Thanks, I can confirm that it runs fine now.

**Comment by Wengier** [comment] 2021-05-28 02:36
Great! Closing.

**Closed by Wengier** 2021-05-28 02:36 UTC
Labels: DOS applications, topic: CPU

**Comment by sagamusix** [comment] 2024-09-26 21:13
Oh wow, great to see you here, @zirco77! Do you still have the code to any of the MMCMP version, and have you ever thought about open-sourcing it? By now probably nobody cares anymore if it is professional or not, but it is an important bit of tracking scene history that deserved to be preserved.

**Comment by sagamusix** [comment] 2024-09-26 21:16
>  I'm genuinely surprised to see new references to my "software" as of today!

I even had to disassemble parts of it a while ago, see https://github.com/temisu/ancient/issues/32 ;)

**Comment by zirco77** [comment] 2024-09-26 21:40
> > I'm genuinely surprised to see new references to my "software" as of today!
> 
> I even had to disassemble parts of it a while ago, see [temisu/ancient#32](https://github.com/temisu/ancient/issues/32) ;)

Well, (de)compression routines were written in assembly, so that's the source code already ;)  Rest was in C.

**Comment by sagamusix** [comment] 2024-09-26 21:59
Ah, sorry to hear about the data loss! At least the released executables (most of them, anyway) are backed up here: https://ftp.modland.com/pub/software/utilities/DOS/MMCMP/
