### ISSUE TITLE
Disk swap counting bug

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1495] opened 2020-04-29 08:56 UTC
**Describe the bug**
If you imgmount a couple of disk images, then do a "Reset guest system" (which looses the mount), and do the same mount again, it adds to the original count.

So if the first time I did an imgmount, I mounted 2 disks, then did the reset, and mount the 2 disks again it counts in the log to 4. And cycling through the disks, it does cycle back to 1 and you can read the disk, so apparently the pointer to the disk image is still valid.

**To Reproduce**
* Start dosbox-x
* imgmount a disk1.img disk2.img
* re-dos
* imgmount a disk1.img disk2.img

**Expected behavior**
Count to start at 1, not at where it left of.

**Screenshots**

**Environment (please complete the following information):**
 - Fedora 31
- DOSBox-X 0.83.1-git (todays build)

**Additional context**
LOG: Identified 'Disk1.img' as C/H/S 80/2/18 512 bytes/sector
LOG: FAT: BPB says 18 sectors/track 2 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT12 with 2847 clusters
LOG: Identified 'Disk2.img' as C/H/S 80/2/18 512 bytes/sector
LOG: FAT: BPB says 18 sectors/track 2 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT12 with 2847 clusters
LOG: Identified 'Disk3.img' as C/H/S 80/2/18 512 bytes/sector
LOG: FAT: BPB says 18 sectors/track 2 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT12 with 2847 clusters
LOG: Identified 'Disk4.img' as C/H/S 80/2/18 512 bytes/sector
LOG: FAT: BPB says 18 sectors/track 2 heads 512 bytes/sector
LOG: Mounted FAT volume is FAT12 with 2847 clusters
LOG: Drive A: disk 5 of 8 now active
LOG: Drive A: disk 6 of 8 now active
LOG: Diskcaching reset for floppy drives.
LOG: Drive A: disk 7 of 8 now active
LOG: Diskcaching reset for floppy drives.
LOG: Drive A: disk 8 of 8 now active
LOG: Diskcaching reset for floppy drives.
LOG: Drive A: disk 1 of 8 now active
LOG: Diskcaching reset for floppy drives.

**Comment by Wengier** [comment] 2020-04-29 16:27
@rderooy This issue has been fixed in the patch I posted in pull request #1496.

**Comment by rderooy** [comment] 2020-04-29 16:38
@Wengier Thanks!

**Comment by rderooy** [comment] 2020-04-29 19:44
@Wengier Your fix solves it for the re-dos case, but not for any other case.

- Selecting Main -> Reset guest system
- Selecting Main -> Send Key -> Ctrl+Alt+Delete (actually that does not do anything?)
- Any DOS program that triggers a reboot

**Comment by Wengier** [comment] 2020-04-29 20:05
@rderooy I fixed it specifically for the RE-DOS command indeed, because that is what you mentioned on how to reproduce it in your first post, and I wanted to make my patch as small as possible before the end of the month. If it also happens when you restart the system in other ways, I will look at the issue in general then.

**Comment by Wengier** [comment] 2020-04-30 00:07
@rderooy I have modified the fix in my pull request #1498. This should cover the other ways to restart the guest system too.

**Closed** 2020-05-05 15:15 UTC
