### ISSUE TITLE
Some image files can't be mounted

### ISSUE THREAD

**Issue by leoxxx** [joncampbell123/dosbox-x#4820] opened 2024-02-13 03:35 UTC
### Question

Some .fdi and .hdi files can't be mounted, but they can be mounted by anex86, T98-Next and Neko Project 21/W.

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment] 2024-02-13 05:55
You can show an example, can't you?

**Comment by leoxxx** [comment] 2024-02-13 09:16
> You can show an example, can't you?

[D.O. Doki Doki Disk 8.hdi.zip](https://github.com/joncampbell123/dosbox-x/files/14258544/D.O.Doki.Doki.Disk.8.hdi.zip)

**Comment by joncampbell123** [comment] 2024-02-13 18:22
The HDI image is so small, that IMGMOUNT doesn't consider it a hard disk image, because anything smaller than 2880 sectors (2.88MB) is assumed to be a floppy disk.

**Comment by leoxxx** [comment] 2024-02-14 14:20
@joncampbell123 
[boot.zip](https://github.com/joncampbell123/dosbox-x/files/14280666/boot.zip)
It's a can't be mounted .fdi.

**Comment by maron2000** [comment] 2024-02-15 22:40
I think problem of hdi & fdi images are fixed by #4825.
Please check.

**Comment by leoxxx** [comment] 2024-02-16 01:54
Does it fix the .nfd? Where is the release? I want to test it.

**Comment by maron2000** [comment] 2024-02-16 02:00
It's not released yet, but you can try the latest nightly build.
I haven't checked your nfd sample yet, but I tested hdi & fdi images myself.

**Comment by maron2000** [comment] 2024-02-16 02:31
Your provided nfd image seems not a MS-DOS formatted disk. It can't be read on MS-DOS running on np21 as well. 
```
IMGMOUNT 0 [.nfd file]
boot a:
```
seems to work.

![nfd2](https://github.com/joncampbell123/dosbox-x/assets/68574602/b8c40d52-5dcc-415a-91ce-8119a4fa8892)

**Comment by leoxxx** [comment] 2024-02-16 03:05
21/W not 21. 21/W is O.K. 
https://simk98.github.io/np21w/
Please try this one.

**Comment by maron2000** [comment] 2024-02-16 03:36
You didn't carefully read my comment.
Boot MS-DOS on np21/w and type the commands I did before complaining.
Also, the procedure you showed in the video doesn't follow my instructions.
Very dissapointing.

**Comment by leoxxx** [comment] 2024-02-16 04:13
![GIF 2024-2-16 12-12-05](https://github.com/joncampbell123/dosbox-x/assets/5364709/f3548514-e388-4886-bb7c-dd353f5effad)

Can't boot. Black screen.

**Comment by maron2000** [comment] 2024-02-16 04:39
Yes, you can't `IMGMOUNT a:` an image when it is not MS-DOS formatted.

And for the blank screen, it is very strange. As I already uploaded the screenshot, it is working for me.
I tried on VS x64 SDL2 nightly build and old 2023.09.01 VS x64 SDL1 release (the screenshot below).
Since I can't reproduce, we have to see what other differences are there.

![nfd4](https://github.com/joncampbell123/dosbox-x/assets/68574602/115cef84-c14d-4f09-a491-a08a83699eb2)

**Comment by leoxxx** [comment] 2024-02-16 04:47
Something about NFD r0 
https://www.pc98.org/project/doc/nfdr0.html

**Comment by leoxxx** [comment] 2024-02-17 01:13
Add .hdm.
[O.K.hdm.zip](https://github.com/joncampbell123/dosbox-x/files/14317232/O.K.hdm.zip)
[error.1.hdm.zip](https://github.com/joncampbell123/dosbox-x/files/14317233/error.1.hdm.zip)

https://dosbox-x.com/wiki/Guide:Managing-image-files-in-DOSBox‐X
I don't find .hdm from this url, so I also upload the O.K. one.

**Comment by maron2000** [comment] 2024-02-17 07:40
You can try the latest nightly for the unmountable hdm file.
Also, you can boot the image by `imgmount 0` even with the current release.

**Comment by leoxxx** [comment] 2024-02-17 09:48
2023.10 version imgmount 0 and boot a: no effect.
I'll try later.

**Comment by maron2000** [comment] 2024-02-17 11:18
Very strange. The hdm boots fine on 2023.10.06 release.
![hdm](https://github.com/joncampbell123/dosbox-x/assets/68574602/503717fb-2cec-436d-a6bb-471d0a4fe9b4)

Anyway, you can find nightly builds quite easily.
![nightly](https://github.com/joncampbell123/dosbox-x/assets/68574602/7bd64035-518f-474d-994c-2c6a9b1f9716)

**Comment by leoxxx** [comment] 2024-02-17 11:25
![2024-02-17_192323](https://github.com/joncampbell123/dosbox-x/assets/5364709/5ca420a0-06af-4e8e-a26b-b1bc020c2c6c)
If boot a: will force close.
I see.
Another question, how do I swap disk if `imgmount 0`?

**Comment by maron2000** [comment] 2024-02-17 13:10
You can change the image to load from the dropdown menu.
Consult the wiki for details, the address is what you mentioned above.

boot.fdi you provided successfully mounts as well.

And your question about lng file, I have no idea since I usually don't use translations myself.
Does it matter with mounting the images?

![change](https://github.com/joncampbell123/dosbox-x/assets/68574602/ff83d111-3892-4a4e-9376-38a64ed4c425)

![boot](https://github.com/joncampbell123/dosbox-x/assets/68574602/3b94f387-b884-4493-9cc7-095ab1421498)

**Comment by leoxxx** [comment] 2024-02-17 13:51
Garbled characters will make me can't understand the command wether it succeed. I remain US, JP, zh_CN and zh_tw, then no garbled characters.
Thank your reply

**Comment by leoxxx** [comment] 2024-02-17 14:46
@joncampbell123 @maron2000 
Really, the .fdi bug only in the MingGW build, VS bulid is O.K. But .nfd still black screen in VS bulid.

**Comment by maron2000** [comment] 2024-02-18 06:31
We have to check what's going on in MinGW builds.
The blank screen problem is another issue, I think mounting itself is okay.

**Comment by joncampbell123** [comment] 2024-02-18 08:18
> @joncampbell123 @maron2000 Really, the .fdi bug only in the MingGW build, VS bulid is O.K. But .nfd still black screen in VS bulid.

Can you check if it has something to do with whether or not "rb" is needed for fopen() or O_BINARY is needed for open()?

Remember that on DOS/Windows systems, functions like open()/read()/write() by default have that translation mode to convert between \r\n and \n and back and that can screw with binary formats if you're unaware.

**Comment by maron2000** [comment] 2024-02-18 12:00
I currently work on Visual Studio to fix and test, so if I have some time I will try MinGW as well, ofcourse considering your advise.
Whether the fixes are working on Linux and/or mac, may matter on where and how to fix.

**Comment by maron2000** [comment] 2024-02-20 03:49
MinGW build couldn't fetch the BPB parameters at all, so currently it will not work.
We have yo see why.

**Comment by leoxxx** [comment] 2024-02-20 16:23
dosbox-x-mingw-win64-20240220143038 Failed.

**Comment by maron2000** [comment] 2024-02-20 22:45
That's too bad. I can't reproduce, so I think something is wrong in your environment.

![fdi](https://github.com/joncampbell123/dosbox-x/assets/68574602/ee675526-0abd-43d9-a7a2-d89958b09c2e)
![fdi2](https://github.com/joncampbell123/dosbox-x/assets/68574602/6955b01d-ce62-41e5-bec2-1978baf68ad1)

**Comment by maron2000** [comment] 2024-02-21 02:23
I don't have any intention to find out what is wrong in the older versions, as long as it is working with the latest nightly.
You can find out yourself.

**Comment by leoxxx** [comment] 2024-02-21 08:33
Add another can't be mounted .fdi
[Rusty.zip](https://github.com/joncampbell123/dosbox-x/files/14356558/Rusty.zip)
dosbox-x-mingw-win64-20240221033525 failed.

**Comment by maron2000** [comment] 2024-02-21 14:20
Fixed the mounting error. (Of course tested the image that failed in the current release)

![rusty](https://github.com/joncampbell123/dosbox-x/assets/68574602/ed5f4c3e-49d4-48e0-bc6b-26d9a5287cb1)

**Closed** 2024-02-22 01:44 UTC
Labels: question
