### ISSUE TITLE
slirp support missing from 2024.03.01 mingw win32 standard build

### ISSUE THREAD

**Issue by BenCollver** [joncampbell123/dosbox-x#4977] opened 2024-04-22 04:15 UTC
### Question

I am using slirp with dosbox-x in the 2023.10.07 mingw win32 standard build.

I noticed that slirp support is not available in the 2024.03.01 mingw win32 standard build.

Is this intentional?  If so, i am curious what changed.

Thanks!

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment] 2024-04-22 04:56
Yes it WAS intentional to drop libslirp support, not by the DOSBox-X devs, but the MinGW devs.
They are seeking to drop 32bit support gradually, but for the time being they decided to bring back support.
So the feature is back again in the nightly builds.

**Comment by maron2000** [comment] 2024-05-17 00:03
This issue can be closed since this is a duplicate of #4849, and more information can be found there.

**Closed** 2024-09-10 02:37 UTC
Labels: question
