### ISSUE TITLE
DOSBox-X reporting the right date but the wrong weekday (Friday instead of Saturday)

### ISSUE THREAD

**Issue by RobertJSawyer** [joncampbell123/dosbox-x#4329] opened 2023-06-10 15:15 UTC
### Describe the bug

DOSBox-X version 2023.05.01 (32-bit SDL1) reporting wrong day of the week.

Today is Saturday, June 10, 2023, but if I type "Date" at the 4DOS prompt in DOSBox-X, it reports:

`Fri  June 10, 2023 11:01:41`

Which is the correct date but not the correct **day** of the week.

The incorrect day-of-the-week information is also accessed by application programs: using WordStar 7.0's "insert date" command (^M@) likewise inserts a formatted date with the wrong day of the week.

I also have 4DOS running without DOSBox-X (under TameDOS), and there it reports the proper day of the week. And my Windows system clock also correctly reports today as Saturday, not Friday.

### Steps to reproduce the behaviour

Simply type "date" or "time" at the 4DOS system prompt and observe the output.

### What operating system(s) this bug have occurred on?

Windows 7 32-bit SP1

### What version(s) of DOSBox-X have this bug?

DOSBox-X version 2023.05.01 (32-bit SDL1)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment] 2023-06-12 01:38
You can try my fix which is yet to be merged, to confirm it works as intended.
https://github.com/joncampbell123/dosbox-x/actions/runs/5233171851

**Comment by RobertJSawyer** [comment] 2023-06-12 14:31
Thank you so much, maron2000! That does indeed fully fix the problem. Much appreciated!

**Closed** 2023-07-17 05:54 UTC
Labels: bug
