### ISSUE TITLE
Taskbar corruption Kubuntu 18.04

### ISSUE THREAD

**Issue by snhirsch** [joncampbell123/dosbox-x#4009] opened 2023-02-12 18:11 UTC
### Describe the bug

Running v2022.12.26, Linux SDL2, 64 Bit.  When dosbox-x is running it scrambles the KDE task bar completely.  The labels are offset such that you affect/select the wrong application.  Dosbox-x itself fails to appear on the task bar.  It's particularly problematic for the tray icons.

### Steps to reproduce the behaviour

Run Kubuntu 18.04 KDE desktop
Open a handful of applications such that they become tabs on the task bar.
Start DosBox-x
If you have enough tray icons, the left-most will no longer be visible, although they respond to "blind" clicks at the actual position.

### Expected behavior

I expect Dosbox-x to be a tab on the task bar and for all the other icons and tasks to remain visible and respond from the labeled location.

### What operating system(s) this bug have occurred on?

Kubuntu 18.04

### What version(s) of DOSBox-X have this bug?

v2022.12.26, Linux SDL2, 64-Bit

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment] 2023-02-13 02:19
\*shakes head\* You know... Windows 95 never had problems with over-long Window title bars. Apparently KDE has such fancy shiny titlebar code that it can't handle what Windows 95 used to effortlessly handle 25+ years ago.

**Comment by maron2000** [comment] 2023-02-17 11:02
I opened more than a dozen apps, and then ran DOSBox-X but none of the tabs disappeared.
Tried both SDL1 and SDL2.
![kubuntu](https://user-images.githubusercontent.com/68574602/219630485-1f0a84e8-e362-4a1a-88a8-02ebf5516ae2.png)

**Comment by maron2000** [comment] 2023-02-17 21:52
Good to hear that the issue is gone.
So you can close this issue.

**Closed** 2023-02-17 22:02 UTC
Labels: bug
