### ISSUE TITLE
opengl mode has greenish garbled graphics

### ISSUE THREAD

**Issue by Jkapp76** [joncampbell123/dosbox-x#2883] opened 2021-09-05 06:13 UTC
**Describe the bug**
any time I set the emulator to opengl mode I get a garbled green mess.

**To Reproduce**
This happens on both of my home computers. both have different nvidia geforce cards.

**Expected behavior**
A nice perfect image.

**Screenshots**
When I take a screen shot the screen shot looks perfect. But it looks bad when I use it. To get this screen shot I put dosbox in a window and used screen snip. the internal screen shot made a perfect image.
![Screenshot 2021-09-05 021000](https://user-images.githubusercontent.com/89743985/132117369-a5ff7235-f668-46ee-9ccb-8859cfddd0a3.png)

**Environment (please complete the following information):**
 - Operating system
 Windows 10
 - DOSBox-X release version or commit SHA1 this issue occurred on
Every version of DOSBox I tried did this. probably about a year or so worth.

**Additional context**
I used opengl to try the opengl shaders. since opengl won't work I tried Direct3D and those shaders work fine.

**Comment by Jkapp76** [comment] 2021-09-05 17:09
I have adjusted the settings in my Nvidia control panel and set the scaler option in the render settings to "none."

This fixed the graphics and also allowed the opengl shaders to work. Setting scaler to none fixed the shaders.

**Comment by Wengier** [comment] 2021-12-29 03:12
Closing since I believe the issue is considered either solved or outside the scope.

**Closed** 2021-12-29 03:12 UTC
Labels: topic: video
