### ISSUE TITLE
Crash in macOSVentura

### ISSUE THREAD

**Issue by gustavopi** [joncampbell123/dosbox-x#4600] opened 2023-11-13 01:57 UTC
### Describe the bug

Tried to run the 2023.10.06 version for Intel Mac and crashed at once.

My machine: Macbook Pro mid 2012, macOSVentura 13.6 under OpenCore 1.0.1.

### Steps to reproduce the behaviour

Download, unpack, unlock, run... CRASH!

Also I have copied it to Applications folder and wasn't needed to add application attribute.

### Expected behavior

Never saw this awesome running, hope to see it some sunny day!

### What operating system(s) this bug have occurred on?

macOSVentura 13.6

### What version(s) of DOSBox-X have this bug?

2023.10.06

### Output log

```text
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               dosbox-x [13441]
Path:                  /Applications/dosbox-x.app/Contents/MacOS/dosbox-x
Identifier:            com.dosbox-x
Version:               2023.10.06 (2023.10.06)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-12 22:48:09.8025 -0300
OS Version:            macOS 13.6 (22G120)
Report Version:        12
Anonymous UUID:        A358F088-BAD8-94F6-FF13-16A4C3772DDC

Sleep/Wake UUID:       8A7F0787-B606-4167-B5AE-6D1E36A87C2A

Time Awake Since Boot: 800000 seconds
Time Since Wake:       141939 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/arm64/libavcodec.60.dylib
Referenced from: <1CCA865A-7A92-3A3A-BC45-173011993719> /Applications/dosbox-x.app/Contents/MacOS/dosbox-x
Reason: tried: '/Applications/dosbox-x.app/Contents/MacOS/arm64/libavcodec.60.dylib' (no such file), '/usr/local/lib/libavcodec.60.dylib' (no such file), '/usr/lib/libavcodec.60.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff81514ac52 __abort_with_payload + 10
1   dyld                          	    0x7ff815164fd7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff815165009 abort_with_payload + 9
3   dyld                          	    0x7ff8150e98f0 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff8150e6b71 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4526
5   dyld                          	    0x7ff8150e53bd start + 1805


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b84f2458  rdx: 0x00007ff7b84f28c0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b84f24a0  rsp: 0x00007ff7b84f2458
   r8: 0x00007ff7b84f24c0   r9: 0x0000000000000000  r10: 0x0000000000000072  r11: 0x0000000000000246
  r12: 0x0000000000000072  r13: 0x00007ff7b84f28c0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff81514ac52  rfl: 0x0000000000000246  cr2: 0x000000010cfbb000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
       0x107a0c000 -        0x108a5afff com.dosbox-x (2023.10.06) <1cca865a-7a92-3a3a-bc45-173011993719> /Applications/dosbox-x.app/Contents/MacOS/dosbox-x
    0x7ff8150df000 -     0x7ff8151775ef dyld (*) <3df96f32-b9c9-3566-a6b7-4daebc6d6563> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=190.0M resident=0K(0%) swapped_out_or_unallocated=190.0M(100%)
Writable regions: Total=74.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=74.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                            67.1M        3 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       173.1M        3 
__TEXT                            16.9M        2 
dyld private memory                260K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            321.4M       17 



-----------
Full Report
-----------

{"app_name":"dosbox-x","timestamp":"2023-11-12 22:48:09.00 -0300","app_version":"2023.10.06","slice_uuid":"1cca865a-7a92-3a3a-bc45-173011993719","build_version":"2023.10.06","platform":1,"bundleID":"com.dosbox-x","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.6 (22G120)","roots_installed":0,"name":"dosbox-x","incident_id":"D91CF956-FE1E-4A74-B670-7A3B54662BE1"}
{
  "uptime" : 800000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro9,2",
  "coalitionID" : 95875,
  "osVersion" : {
    "train" : "macOS 13.6",
    "build" : "22G120",
    "releaseType" : "User"
  },
  "captureTime" : "2023-11-12 22:48:09.8025 -0300",
  "incident" : "D91CF956-FE1E-4A74-B670-7A3B54662BE1",
  "pid" : 13441,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-11-12 22:48:09.7544 -0300",
  "procStartAbsTime" : 800509254529515,
  "procExitAbsTime" : 800509282749125,
  "procName" : "dosbox-x",
  "procPath" : "\/Applications\/dosbox-x.app\/Contents\/MacOS\/dosbox-x",
  "bundleInfo" : {"CFBundleShortVersionString":"2023.10.06","CFBundleVersion":"2023.10.06","CFBundleIdentifier":"com.dosbox-x"},
  "storeInfo" : {"deviceIdentifierForVendor":"6D221C58-058F-5B24-9E59-E97C0BA08E26","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.dosbox-x",
  "crashReporterKey" : "A358F088-BAD8-94F6-FF13-16A4C3772DDC",
  "codeSigningID" : "com.dosbox-x",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425345,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 141939,
  "sleepWakeUUID" : "8A7F0787-B606-4167-B5AE-6D1E36A87C2A",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @executable_path\/arm64\/libavcodec.60.dylib","Referenced from: <1CCA865A-7A92-3A3A-BC45-173011993719> \/Applications\/dosbox-x.app\/Contents\/MacOS\/dosbox-x","Reason: tried: '\/Applications\/dosbox-x.app\/Contents\/MacOS\/arm64\/libavcodec.60.dylib' (no such file), '\/usr\/local\/lib\/libavcodec.60.dylib' (no such file), '\/usr\/lib\/libavcodec.60.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":13083503,"threadState":{"r13":{"value":140701925845184},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701925844160},"cr2":{"value":4512788480},"rdx":{"value":140701925845184},"r10":{"value":114},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703482293330,"matchesCrashFrame":1},"rbp":{"value":140701925844128},"rsp":{"value":140701925844056},"r12":{"value":114},"rcx":{"value":140701925844056},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":441426,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":1},{"imageOffset":548823,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":548873,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":43248,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":31601,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4526,"imageIndex":1},{"imageOffset":25533,"symbol":"start","symbolLocation":1805,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4422942720,
    "CFBundleShortVersionString" : "2023.10.06",
    "CFBundleIdentifier" : "com.dosbox-x",
    "size" : 17100800,
    "uuid" : "1cca865a-7a92-3a3a-bc45-173011993719",
    "path" : "\/Applications\/dosbox-x.app\/Contents\/MacOS\/dosbox-x",
    "name" : "dosbox-x",
    "CFBundleVersion" : "2023.10.06"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703481851904,
    "size" : 624112,
    "uuid" : "3df96f32-b9c9-3566-a6b7-4daebc6d6563",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703481233408,
  "size" : 21474836480,
  "uuid" : "75dd4664-3ce0-3cee-8a6f-327db863e105"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=190.0M resident=0K(0%) swapped_out_or_unallocated=190.0M(100%)\nWritable regions: Total=74.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=74.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                            67.1M        3 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       173.1M        3 \n__TEXT                            16.9M        2 \ndyld private memory                260K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            321.4M       17 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "8249ba41cfe8f1ac91a72ec313a69fba6b3beeeb",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "61675b89201f677a9a4cbd65",
      "factorPackIds" : {
        "HEALTH_FEATURE_AVAILABILITY" : "64d14f3e1008ca2fac17a163"
      },
      "deploymentId" : 240000064
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro9,2, BootROM 421.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2,5 GHz, 16 GB, SMC 2.2f44
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Display: Color LCD, 1280 x 800, Main, MirrorOff, Online
Display: L1760TQ, 1280 x 1024 (SXGA - Super eXtended Graphics Array), MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500,11 GB
Serial ATA Device: APPLE HDD HTS547550A9E384, 500,11 GB
USB Device: USB20Bus
USB Device: hub_device
USB Device: hub_device
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB20Bus
USB Device: hub_device
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB30Bus
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment] 2023-11-13 04:25
The issue is fixed in the recent nightly builds. Refer to issue #4438 for details.

**Closed** 2024-01-05 23:52 UTC
Labels: bug, platform: Mac
