### ISSUE TITLE
DosBox-X 2023 fails to launch executable under macOS Ventura 

### ISSUE THREAD

**Issue by ezathashim** [joncampbell123/dosbox-x#4378] opened 2023-07-19 11:32 UTC
### Describe the bug

I was running DosBox under macOS 12 without any issues. However, after updating to macOS 13 (Ventura), it can no longer launch the dos executable (with error 255).

I suspect that it has something to do with file permissions since Apple is slowly locking down access to more files with each OS. I have not found a way to get the executable to launch. The app I use a strictly a DOS based accounting program with no high level graphics.

Any help would be appreciated. 

### Steps to reproduce the behaviour

- I would have to send a copy of the executable. It is an application called NewViews (the DOS version).

### Expected behavior

- just launch without error

### What operating system(s) this bug have occurred on?

macOS Ventura (macOS 13)

### What version(s) of DOSBox-X have this bug?

2023.05

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment] 2023-07-19 12:13
If you are using the downloaded Release version, it is built on macOS 12 (Monterey) so that maybe the cause.
You can try building the binary on Ventura yourself.

**Comment by ezathashim** [comment] 2023-07-19 17:16
I just ran a build on macOS Ventura and the problem persists.

- Ezat

**Comment by ezathashim** [comment] 2023-07-19 18:23
In my explanation I said it did not run the executable. What I should have said was that the DOS app executable runs, but it fails to open any file archives for the app.

**Comment by maron2000** [comment] 2023-07-20 01:14
If so, is this issue a duplicate of #2176, which the author is you?
Or the proposed workaround works on Monterey only?
On Windows, the proposed workaround seems to work.

**Comment by ezathashim** [comment] 2023-07-20 01:27
Yes, the author is me. I have all the configurations suggested in that thread and it fails on Ventura. I’ll poke around a bit more.On Jul 19, 2023, at 9:14 PM, maron2000 ***@***.***> wrote:﻿
If so, is this issue a duplicate of #2176, which the author is you?
Or the proposed workaround works on Monterey only?
On Windows, the proposed workaround seems to work.

**Comment by ezathashim** [comment] 2023-08-08 18:57
I just tried 'Boxer' on my Mac (which is a DosBox wrapper) and the most recent beta opens the files properly (https://boxer.thec0de.com). Do you think that the shared files from DosBox need to be updated in DosBox-X? I'm not sure how closely DosBox is followed.

**Comment by ezathashim** [comment] 2023-12-11 14:31
I finally fixed the issue. It was a setting on the .conf file that was not propagated. The solution was previously presented here:

https://github.com/joncampbell123/dosbox-x/issues/2176

Great!

**Closed** 2023-12-11 14:31 UTC
Labels: bug, platform: Mac
