### ISSUE TITLE
Remove DirectDraw output

### ISSUE THREAD

**Issue by vandenk** [joncampbell123/dosbox-x#332] opened 2017-12-05 08:05 UTC
Hello,

With DOSBox-X I can not activate the output ddraw (it works with the official version) even if I put the line "output = ddraw" in dosbox.conf!
DOSBox-X puts the output in "surface"

Why ?

**Comment by joncampbell123** [comment] 2017-12-05 08:42
Which binary are you using?

**Comment by vandenk** [comment] 2017-12-05 08:44
dosbox-x-windows-20171128.zip

**Comment by vandenk** [comment] 2017-12-05 08:45
same result on x86 and x64

**Comment by joncampbell123** [comment] 2017-12-05 08:49
It may be that in compiling for Windows I forgot to enable DirectX support. A recent patch I accepted makes it conditional, and if selected, uses the DirectX SDK paths.

**Comment by vandenk** [comment] 2017-12-05 09:02
This is the last version of DOSBox-X I use (previous post corrected)
Which version would not be impacted by this problem ?

**Comment by vandenk** [comment] 2017-12-05 09:15
I have d3dx9_43.dll and d3dx9_43_x64.dll in DOSBox-X directory

**Comment by joncampbell123** [comment] 2017-12-05 17:13
What I mean is that apparently I forgot to compile DirectX support into the DOSBox-X binary itself. I'll see if I can remedy that in the next Windows binary release.

**Comment by vandenk** [comment] 2017-12-05 23:40
OK, thanks

**Comment by joncampbell123** [comment] 2017-12-06 04:49
I'm seeing DOSBox-X complain that DDRAW output cannot be done because it cannot create ddraw surface.

Debugging shows that it *can* create a ddraw surface, but it's not a hardware surface, so it considers that a failure. I didn't add that code, so I don't know why anyone would add that.

By the way, I like how merely debugging a program in VS 2017 in Windows 10 makes keyboard input everywhere really slow. Like "hunt and peck" slow, even ALT+TAB. Hilarious.

**Comment by joncampbell123** [comment] 2017-12-06 05:03
Okay.......... so................ 15............ slow............ keyboard.......... inputs............. later............................ it...........seems.........that.......the.......code.......requires.........a.........hardware............surface..............because................it.............pokes..............into..............SDL.............internal..............state............to............access...........IDirectDraw..........surface..........objects..............and............it..........uses.........the..........hwdata.........member.........which.........is.........only........non-null..........if.........the.........surface.........is............in..........hardware.

I'm sorry but VS2017's debugger making UI input that slow is fucking hilarious. I thought VS2005 on Windows XP was bad, holy cow.

**Comment by joncampbell123** [comment] 2017-12-06 05:06
Okay, well, hold on, I have a theory about the slow input that I'll try. I just remembered DOSBox-X uses a low level keyboard hook to help match the num/caps/scroll lock LEDs to guest state that might be the problem.

**Comment by joncampbell123** [comment] 2017-12-06 05:10
I deleted my previous comments. It's my fault, not VS2017. The slow keyboard input is caused by DOSBox-X having a low level keyboard hook. I guess Windows isn't smart enough to know that it shouldn't call the hook proc of a program that's being debugged and stopped at a breakpoint, so it makes keyboard input really slow trying and failing to call it.

The strange thing is that the hook proc shouldn't be set unless you capture the mouse in DOSBox-X.

**Comment by joncampbell123** [comment] 2017-12-06 05:11
The fault is that it's creating a ddraw surface, but it sees that the surface is not a hardware surface, so it releases it and considers it a failure.

Apparently in Windows 10 DirectDraw programs cannot obtain a hardware surface.

**Comment by joncampbell123** [comment] 2017-12-06 05:17
Okay, so maybe it's not the low level hook, it only happens if I debug break during the SDL surface setup.

**Comment by joncampbell123** [comment] 2017-12-06 05:24
So on my system, I cannot use the ddraw output, but direct3d and opengl seem to work.

The aspect ratio correction menu item appears to be broken, so I'll see if I can fix that.

**Comment by vandenk** [comment] 2017-12-06 23:26
I have done tests with several versions of DOSBox (official, ECE, SVN Daum, DOSBox-x), I use Windows 3.11 as guest OS.
With DOSBox-x can not have a mouse that works well ... can not have DirectDraw and OpenGL, no pixel shaders with Direct3D ...

Here are the results :

- DOSBox SVN DAUM (r3894) :
Surface : Mouse OK / No Resize
Overlay : Mouse OK / No Resize
DirectDraw : Mouse OK / Resize Nearest-neighbor only
Direct3D : Mouse **KO** / Resize Pixel Shader (Alway resize even when original size selected)
OpenGL : Mouse OK / Resize (by other hradware ? / unchangeable)
OpenGL_NB : Mouse OK / Resize Nearest-neighbor only
OpenGL_HQ : **exit DOSBox-x instantly**


- DOSBox-x 20171205-2228 :
Surface : Mouse **KO** / No Resize
Overlay : Mouse **KO** / No Resize
DirectDraw : **switch to surface**
Direct3D : Mouse **KO** / Resize Nearest-neighbor only
OpenGL : **exit DOSBox-x instantly** 
OpenGL_NB : **exit DOSBox-x instantly** 
OpenGL_HQ : **exit DOSBox-x instantly**


- DOSBox O.74 Oficial :
Surface : Mouse OK / No Resize
Overlay : Mouse OK / Resize Nearest-neighbor in windowresolution / Resize by other hradware ? (unchangeable) in fullresolution
DirectDraw : Mouse OK / Resize Nearest-neighbor only
OpenGL : Mouse OK / Resize (by other hradware ? / unchangeable)
OpenGL_NB : Mouse OK / Resize Nearest-neighbor only


- DOSBox ECE (r4065) :
Surface : Mouse OK / No Resize
Surfacepp : Mouse OK / No Resize
Surfacenp : Mouse **KO** / Resize (by scaler ? / unchangeable ?)
Surfacenb : Mouse OK / Resize Nearest-neighbor only
Overlay : Mouse **KO** / Resize Nearest-neighbor in windowresolution / Resize by other hradware ? (unchangeable) in fullresolution
DirectDraw : Mouse OK / Resize Nearest-neighbor only
OpenGL : Mouse OK / Resize (by other hradware ? / unchangeable)
OpenGL_NB : Mouse OK / Resize Nearest-neighbor only

Mouse KO = jerks, displacement wrong, lag ...

**Comment by joncampbell123** [comment] 2017-12-06 23:40
Is this the latest binary of DOSBox-X? I just fixed the OpenGL crash on startup. SDL corrupts the format pointer when the OpenGL code quits then re-initializes the video subsystem.

**Comment by vandenk** [comment] 2017-12-06 23:53
no it's 201711292213, I'll test with the new version.

**Comment by vandenk** [comment] 2017-12-07 00:10
- DOSBox-x 20171205-2228 x64 :
Surface : Mouse KO / No Resize
Overlay : Mouse KO / No Resize
DirectDraw : **switch to surface**
Direct3D : Mouse **KO** / Resize Nearest-neighbor only
OpenGL : Mouse **KO** / Resize (by other hradware ? / unchangeable)
OpenGL_NB : Mouse **KO** / Resize Nearest-neighbor only
OpenGL_HQ : **exit DOSBox-x instantly**

**Comment by joncampbell123** [comment] 2017-12-07 00:22
Sounds about right. I admit the output code is messy and needs work. What I inherited from DOSBox is a good chunk of hacks on hacks including code that pokes a little too deeply into internal SDL state to accomplish the desired goal.

On Linux, a combination of DOSBox-X + SDL bugs results in a window that you can resize, but DOSBox-X stops responding to resize events after the first time.

Last month's "sprint" was basic NEC PC-98 emulation, so perhaps for this month or two I'll cleanup the output code.

Fair warning: My cleanup process may break the scaler functions (such as hq2x) for awhile.

**Comment by vandenk** [comment] 2017-12-16 14:50
I confirm that the mouse problems are solved with the latest version (x64 SDL1 20171215-0823).
However, the x86 version still bug with Windows 3.11.

**Comment by joncampbell123** [comment] 2017-12-16 16:03
I'll have a new binary up soon.

**Comment by joncampbell123** [comment] 2017-12-16 17:43
Binary is up.

**Comment by joncampbell123** [comment] 2017-12-23 08:46
So even going back to Windows XP I do not have the means to test and develop DOSBox-X vs DirectDraw because none of the systems I have will allow the DirectDraw support to work. I have no way to maintain the code.

If anyone else here wants to take on maintaining that code and submitting patches, go right ahead. DirectDraw I understand would be idea for Windows 9x systems where Direct3D is not available.

However if nobody has any interest, I would be more than happy to remove DirectDraw support from DOSBox-X.

**Comment by vandenk** [comment] 2018-01-01 11:34
Ok, it is true that on recent operating systems (if opengl and direct3d work properly) ddraw does not have much interest ...

**Comment by joncampbell123** [comment] 2018-01-01 18:05
@vandenk Exactly. DirectDraw is more useful on Windows 9x/ME than anything past XP.

Perhaps then, I should remove it. If anyone needs it, they can rewrite it to add it back. Hopefully when they do, they'll write it to tolerate hardware/software surfaces this time.

**Comment by joncampbell123** [comment] 2018-01-02 05:04
I will remove it then, in the next binary release.

**Comment by vandenk** [comment] 2018-01-02 10:29
Ok I close this issue

**Comment by joncampbell123** [comment] 2018-01-02 12:40
@vandenk Not yet, let me remove it first, then I will close the issue!

**Closed** 2018-01-07 03:10 UTC
Labels: SDL1, enhancement, platform: Windows

**Comment by joncampbell123** [comment] 2018-01-07 03:11
It's done. One more issue to fix: If you start up DOSBox-X with output=ddraw the window pops up and disappears.

**Comment by joncampbell123** [comment] 2018-01-07 03:30
Done

**Comment by joncampbell123** [comment] 2018-01-07 03:30
Also found a segfault that can happen if you startup in surface or OpenGL and use the menu to switch to Direct3D output.
