### ISSUE TITLE
Crash when running 320x200 programs with no scaler and Surface output

### ISSUE THREAD

**Issue by foone** [joncampbell123/dosbox-x#3348] opened 2022-03-22 00:56 UTC
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 10 10.0.19044.1586 (x64)

### What version(s) of DOSBox-X have this bug?

Dosbox-X 0.83.23 (portable, msvc, SDL2)

### Describe the bug

Crash when switching into graphical mode:
```Assertion failed!

Program: ...ub\erot\dosbox-x\bin\x64\Release SDL2\dosbox-x.exe
File: C:\Downloads\DOSSoft\dosbox\dosbox-...\output_...dl2.cpp
Line: 188

Expression: sdl.surface->h >= (sdl.clip.y+sdl.clip.h)```



### Expected behavior

It not crashing :) 

### Steps to reproduce the behaviour

1. set scaler to None, Force scaler, and output to Surface. 
2. run a program that runs at 320x200. (I used Duke Nukem 1 shareware for a test)

Note: turning off the menu causes it to work again. I think the menu is forcing a minimal size and this doesn't work with a smaller DOS window 

### Used configuration

```ini
[sdl]
output            = surface

[render]
doublescan     = false
scaler         = none forced
```

### Emulator log

```text
LOG: pixratio 1.200, dw true, dh true
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: surface consider=320x200 final=320x200
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: surface consider=320x200 final=320x200
LOG: Screen report: Method 'Win98base' (1920.000 x 1080.000 pixels) at (0.000 x 0.000) (508.000 x 285.750 mm) (20.000 x 11.250 in) (96.000 x 96.000 DPI)
LOG: Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
LOG: surface consider=320x200 final=320x200
```

**Comment by joncampbell123** [comment] 2022-03-22 06:26
I'm not able to reproduce your exact crash on Linux, but resizing the window right at the minimum here on Linux eventually triggers an assertion that says DOSBox-X computed the display region with at least one pixel outside the width and height of the SDL surface returned by SDL2.

**Comment by grapeli** [comment] 2022-03-23 14:38
I can't reproduce this error under Linux (latest SDL2).
Although, as far as I remember, I have come across it before.
It is very possible that it depends on the SDL2 version.

https://user-images.githubusercontent.com/452325/159724726-166175f6-ba7f-4460-bda0-67dbd4f50fd7.mp4

**Comment by joncampbell123** [comment] 2022-06-03 22:02
This issue has been addressed in the latest commit.

**Closed by joncampbell123** 2022-06-03 22:02 UTC
Labels: bug
