### ISSUE TITLE
Printing reproducibly crashes on Windows 11

### ISSUE THREAD

**Issue by dajhorn** [joncampbell123/dosbox-x#3089] opened 2021-11-19 02:03 UTC
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Windows 11 Version 21H2 Build 22000.318

### What version(s) of DOSBox-X have this bug?

0.83.19 SDL1

### Describe the bug

Printing to any backend reproducibly crashes the Windows build.

eg: `printoutput = png` or `printoutput = printer`

### Expected behavior

DOSBox-X doesn't crash while handling a print job on Windows 11.

### Steps to reproduce the behaviour

1. Start Windows 3.11 in DOSBox-X.
2. Install an Epson LQ-570 ESC/P 2 instance on LPT1. 
3. Open Notepad.exe
4. Make the text document non-empty.
5. Click File -> Print
6. Host application crashes and exits without logging anything about the print job.

### Used configuration

```ini
[video]
vmemsize                = 8

[cpu]
core       = dynamic

[ttf]
ptsize       = 12

[serial]
serial1       = dummy
serial2       = disabled

[printer]
printer     = true
printoutput = png

[ipx]
# ipx: Enable ipx over UDP/IP emulation.
ipx = false

[ne2000]
ne2000  = true
nicbase = 300
nicirq  = 3
macaddr = AC:DE:48:88:99:AB
backend = auto

[ethernet, pcap]
realnic = 02
timeout = default

[config]
break       = off
numlock     = 
shell       = 
dos         = high, umb
fcbs        = 100
files       = 200
country     = 
lastdrive   = a
set path    = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL;C:\WINDOWS
set prompt  = $P$G
set temp    = C:\TEMP
install     = 
installhigh = 
device      = 
devicehigh  = 

[log]
#     logfile: file where the log messages will be saved to
# debuggerrun: The run mode when the DOSBox-X Debugger starts.
#                Possible values: debugger, normal, watch.
#
# Advanced options (see full configuration reference file [dosbox-x.reference.full.conf] for more details):
# -> vga; vgagfx; vgamisc; int10; sblaster; dma_control; fpu; cpu; paging; fcb; files; ioctl; exec; dosmisc; pit; keyboard; pic; mouse; bios; gui; misc; io; pci; sst; int21; fileio
#
logfile     = Snowball.log
debuggerrun = debugger

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
MOUNT C .\C -freesize 128 -label HDD
C:
```

### Emulator log

```text
Logging: opened logfile 'Snowball.log' successfully. All further logging will go to this file.
Win32 EnumDisplayDevices #0: name=\\.\DISPLAY1 string=NVIDIA GeForce GTX 1050
Win32 EnumDisplayDevices #1: name=\\.\DISPLAY2 string=NVIDIA GeForce GTX 1050
Win32 EnumDisplayDevices #2: name=\\.\DISPLAY3 string=NVIDIA GeForce GTX 1050
Win32 EnumDisplayDevices #3: name=\\.\DISPLAY4 string=NVIDIA GeForce GTX 1050
DOSBox-X version 0.83.19 (Windows SDL1)
Windows keyboard layout ID is 0x0409
Host keyboard layout is now us (US English)
Mapper keyboard layout is now us (US English)
The default output for the video system: direct3d
Configured windowposition: 
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
ISA BCLK: 8333333.333Hz (25000000/3)
monopal: green, 
Active save slot: 1 [Empty]
USING AVI+ZMBV
Max 3670016 sz 16384
Final 16384
MIDI:Opened device:win32
Pentium CMPXCHG8B emulation is enabled
One joystick reported, initializing with 4axis
Using joystick Controller (Xbox One For Windows) with 5 axes, 16 buttons and 1 hat(s)
VOODOO LFB now at d0000000
Serial1: BASE 3f8h
Parallel1: BASE 378h
MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Allocated APM BIOS pm entry point at f000:ce20
Writing code to fce20
ETHERNET: NE2000 Ethernet emulation backend selected: pcap
Using Network interface:
rpcap://\Device\NPF_{9DA45A9D-3392-4278-A6F0-C4EC493193C3}
(Network adapter 'Microsoft' on local host)
NE2000: Base=0x300 irq=3
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Windows: IID_ITaskbarList3 is available
ISA Plug & Play BIOS enabled
VGA ROM BIOS init callback
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
pixratio 1.000, dw false, dh false
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
XMS: 50 handles allocated for use by the DOS environment
EMS page frame at 0xe000-0xefff
COMMAND.COM env size:             720 bytes
COMMAND.COM environment block:    0x0701 sz=0x002d
COMMAND.COM main body (PSP):      0x072f sz=0x009a
COMMAND.COM stack:                0x0749
pixratio 1.350, dw false, dh false
Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
 134783976 ERROR INT10:Function 6F00 not supported
pixratio 1.000, dw false, dh false
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
DEBUG: INT 2Fh Windows 286/386 DOSX init broadcast issued (ES:BX=0000:0000 DS:SI=0000:0000 CX=0000 DX=0000 DI=030b(aka version 3.11))
 [Enhanced mode]

 145043055 ERROR CPU:Illegal Unhandled Interrupt Called 68
 145494267 ERROR INT10:Function 6F00 not supported
 145495260 ERROR INT10:Function 12:Call  6 not handled
 145635778 ERROR CPU:Illegal Unhandled Interrupt Called 5C
 145636131 ERROR CPU:Illegal Unhandled Interrupt Called 5C
 145636452 ERROR CPU:Illegal Unhandled Interrupt Called 5C
 145636645 ERROR CPU:Illegal Unhandled Interrupt Called 5C
 145636838 ERROR CPU:Illegal Unhandled Interrupt Called 5C
 145636999 ERROR CPU:Illegal Unhandled Interrupt Called 5C
 145637192 ERROR CPU:Illegal Unhandled Interrupt Called 5C
 145637385 ERROR CPU:Illegal Unhandled Interrupt Called 5C
DEBUG: INT 2Fh Windows virtual device 'PAGEFILE' callout (BX(deviceID)=0x0021 CX(function)=0x0000)
DOSBox-X has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox-X's options.
DEBUG: INT 2Fh Windows virtual device 'VMD' callout (BX(deviceID)=0x000c CX(function)=0x0001)
INT 15h mouse initialized to 3-byte protocol
INT 15h mouse reset
INT 15h reporting mouse device ID 0x00
DEBUG: INT 2Fh Windows virtual device 'VNETBIOS' callout (BX(deviceID)=0x0014 CX(function)=0x0000)
DEBUG: INT 2Fh Windows virtual device 'DOSMGR' callout (BX(deviceID)=0x0015 CX(function)=0x0000)
DEBUG: INT 2Fh Windows virtual device 'DOSMGR' callout (BX(deviceID)=0x0015 CX(function)=0x0004)
DEBUG: INT 2Fh Windows virtual device 'DOSMGR' callout (BX(deviceID)=0x0015 CX(function)=0x0001)
DEBUG: INT 2Fh Windows virtual device 'DOSMGR' callout (BX(deviceID)=0x0015 CX(function)=0x0003)
DEBUG: INT 2Fh Windows virtual device 'DOSMGR' callout (BX(deviceID)=0x0015 CX(function)=0x0005)
DEBUG: INT 2Fh Windows virtual device 'PAGEFILE' callout (BX(deviceID)=0x0021 CX(function)=0x0000)
DEBUG: INT 2Fh Windows virtual device 'V86MMGR' callout (BX(deviceID)=0x0006 CX(function)=0x0000)
DEBUG: INT 2Fh Windows virtual device 'VMD' callout (BX(deviceID)=0x000c CX(function)=0x0000)
pixratio 1.000, dw false, dh false
Aspect ratio: 800 x 600  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
 161819773 ERROR MOUSE:Unhandled videomode 6A on reset
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
Aspect ratio: 800 x 600  xToY=1.333 yToX=0.750
Screen report: Method 'Win98base' (1280.000 x 1024.000 pixels) at (0.000 x 0.000) (338.667 x 270.933 mm) (13.333 x 10.667 in) (96.000 x 96.000 DPI)
```

### Additional context

Not reproducible on a Linux host.  The print job is handled as expected.

**Comment by Wengier** [comment] 2021-11-19 03:36
It is likely the issue is due to the same problem as issue #2908, which is already fixed in the current development code. Can you try the latest Windows builds and see if they work as expected?

* Windows SDL1: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* Windows SDL2: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

Hope this helps.

**Comment by dajhorn** [comment] 2021-11-20 17:05
Yes, this Windows build behaves correctly like the Linux build. Thanks.

**Closed** 2021-11-22 10:30 UTC
Labels: bug, topic: printing
