### ISSUE TITLE
Documentation: Windows 95 dos box and vesa mode with hardware mouse

### ISSUE THREAD

**Issue by ghoul8765** [joncampbell123/dosbox-x#148] opened 2016-01-26 05:16 UTC
Noted screen corruption in 95 dos box while running Quake at 640x480 with the directx mouse acceleration active (via graphics performance slider set to maximum and directx6 installed). If the software cursor is instead active (by turning down slider one notch), then the screen corruption is not present. The corruption is just a stationary, small black box.

Warcraft 2 has same issue but it appears fixed by disabling "fast rom emulation" in the dos box properties.

**Comment by joncampbell123** [comment] 2016-01-26 06:53
Does this screen corruption happen with Windows 95 OSR2, Windows 98, Windows ME?

I'm aware of the bug where under Windows 95 (the original version) bringing up a DOS prompt with the S3 driver causes minor screen corruption until you reset the video mode. It doesn't happen under any other version of Windows.

**Comment by ghoul8765** [comment] 2016-01-26 06:58
I only tested in Windows 95 OSR2, but I just found that changing the color depth from high colors to 256 colors fixes this narrow issue. It certainly seems like it would occur in real hardware given that it is specific to the directx mouse acceleration and it is fixed by a 256 color display.

The corruption is a small black box and could be where the mouse should be.

**Comment by sikthehedgehog** [comment] 2016-01-27 08:58
What bug do you talk about regarding S3 cards? I remember there being a bug where occasionally the arrow/hourglass (alongside a screen-high column of garbage pixels) would show up overlayed on top of text mode (the bug was rare so I really never spotted a pattern to it - switching to windowed and back to fullscreen fixed it). This was on real harwdare running Windows 98 SE btw.

Maybe it's a completely different thing I'm talking about, but if you ever see a bug like that... it's not a bug, that's how real hardware works.

**Comment by joncampbell123** [comment] 2016-01-27 12:13
I went ahead and opened a new issue describing the bug: #150 
It's not related to your issue.

**Comment by ghoul8765** [comment] 2016-01-29 03:05
The "black box" screen corruption under Windows 95b dos box (vesa mode >=640H, directx acceleration full, and 16-bit color desktop) goes away with loading a bios along with a patch to make it compatible (I made a few corrections to this experimental patch): http://www.vogons.org/viewtopic.php?f=31&t=36579.

I tried many 95 s3 drivers without effect on the issue.

Note that disabling the directx mouse acceleration or running vesa mode <640H or setting a 256 color desktop also fixes the issue.

I wonder whether the 95b dos box is missing bios data or if a change in this part of vga_draw.cpp provides any clues:
<pre lang=""><code>	case M_LIN8:
		if (vga.crtc.mode_control & 0x8)
			width >>=1;
		else if (svgaCard == SVGA_S3Trio && !(vga.s3.reg_3a&0x10)) {
			doublewidth=true;
			width >>=1;
		}
		// fall-through
	case M_LIN32:
		width<<=3;
		if (vga.crtc.mode_control & 0x8)
 			doublewidth = true;
		/* Use HW mouse cursor drawer if enabled */
		VGA_ActivateHardwareCursor();
		break;
	case M_LIN15:
 	case M_LIN16:
		// 15/16 bpp modes double the horizontal values
		width<<=2;
		if ((vga.crtc.mode_control & 0x8) || (svgaCard == SVGA_S3Trio && (vga.s3.pll.cmd & 0x10)))
			doublewidth = true;
		/* Use HW mouse cursor drawer if enabled */
		VGA_ActivateHardwareCursor();
		break;
</code></pre>

**Comment by ghoul8765** [comment] 2016-01-29 03:19
It seems to be related to this function in that the directx acceleration is calling it: VGA_ActivateHardwareCursor. If this function is disabled via its register, then the mouse cursor is invisible and the cursor may be restored be disabling the directx mouse acceleration.

**Comment by ghoul8765** [comment] 2016-01-29 03:33
If I modify the function VGA_Draw_LIN16_Line_HWMouse from this:
memcpy(TempLine, &vga.mem.linear[ vidstart ], vga.draw.width*2);
to this:
memcpy(TempLine, &vga.mem.linear[ vidstart ], vga.draw.width);

Then the corruption goes away in the dos box; however, the mouse cursor is attached to a rectangular box before or after use of the dos box.

**Comment by ghoul8765** [comment] 2016-01-29 04:54
Is the hardware mouse not virtualized properly in the dos box; and the working cases a fallback to a software mouse?

**Comment by ghoul8765** [comment] 2016-01-29 05:04
Would this workaround work:
<pre lang=""><code>--- int10_modes-ORIG.cpp	2016-01-29 00:02:35 -0500
+++ int10_modes.cpp	2016-01-29 00:02:04 -0500
@@ -914,6 +914,9 @@ bool INT10_SetVideoMode(Bit16u mode) {
 	if (svgaCard != SVGA_S3Trio)
 		vga.config.compatible_chain4 = true; // this may be changed by SVGA chipset emulation
 
+	if (svgaCard == SVGA_S3Trio)
+		vga.s3.hgc.curmode = 0;
</code></pre>

**Comment by joncampbell123** [comment] 2016-01-29 06:12
I'll try that patch. What I'm concerned is whether or not Windows 95 is able to bring the cursor back if you exit fullscreen from the DOS box.

**Comment by joncampbell123** [comment] 2016-01-29 06:22
Sorry, I can't verify if it fixes the cursor in Quake but I see that it kills the mouse cursor when you bring up a DOS box.

Windows 95 relies on INT 10h communicating through I/O ports so that it can trap and virtualize them per VM. So if INT 10h is to clear the cursor, it needs to do it by writing I/O ports, not by directly modifying VGA state.

**Comment by joncampbell123** [comment] 2016-01-29 06:30
Look at CRTC register 0x45, "Hardware Graphics Cursor Mode Register" (HGC_MODE).

If you want to set hgc.curmode = 0 try adding this to INT10_SetVideoMode():

    if (svgaCard == SVGA_S3Trio)
        IO_Write(crtc_base,0x45); IO_Write(crtc_base+1,0x00);

**Comment by joncampbell123** [comment] 2016-01-29 06:48
I just confirmed that when you switch Quake into 640x480x256 mode, the cursor shows up as a garbled version of what's on screen, and that the change I mentioned in the previous post prevents the garbled cursor from appearing.

**Comment by joncampbell123** [comment] 2016-01-29 06:53
Check the latest commit. Does it fix the issue? I test-ran Quake in a Windows 95 DOS box as you described and my change seems to fix the issue. If it does fix it on your end I will close this issue.

**Comment by ghoul8765** [comment] 2016-01-29 07:09
Your commit works great, thank you! Tested in Warcraft 2, too. :)

**Closed** 2016-01-29 07:10 UTC
