### ISSUE TITLE
bCAD crashes dosbox-x INT gate selector type 10 problem

### ISSUE THREAD

**Issue by SkybuckFlying** [joncampbell123/dosbox-x#4021] opened 2023-02-18 04:02 UTC
### Describe the bug

bCAD crashes dosbox-x.

I have uploaded three different versions of bcad here for you to try out and see for yourself:

http://www.skybuck.org/msdos/bcad/

I have no idea what bCAD is, except that it is some ancient computer aided design program and I would like to try it out to see what it is.

Can you fix dosbox-x so that it doesn't crash anymore ?

### Steps to reproduce the behaviour

start bcad.exe

### Expected behavior

No crash.

### What operating system(s) this bug have occurred on?

Windows 7 home edition

### What version(s) of DOSBox-X have this bug?

2022.09.0 64-bit SDL1

### Used configuration

```ini
Almost default, doesn't really matter.
```

### Output log

```text
Better produce it yourself if so desired.
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by joncampbell123** [comment] 2023-02-18 06:36
Please try LOADFIX -a before running the program.

I will test it out here on my end as well.

**Comment by joncampbell123** [comment] 2023-02-18 19:25
Duplicate of #4020

**Closed by joncampbell123** 2023-02-18 19:25 UTC
Labels: bug
