### ISSUE TITLE
Feature Request / Suggestion: Limited DMF Support

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [joncampbell123/dosbox-x#2962] opened 2021-10-04 11:45 UTC
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar feature request(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Is your feature request related to a problem? Please describe.

yes, i can't mount dmf image, but that is not issue. the issue is that even if i mount it with `-fs none` option , formatting utilities like FreeDOS Format can't read boot sector, MS-DOS Format gives error "Invalid Media or Track 0 Bad"

### What you want

support for formatting dmf disks, and mounting as drive 0 or 1 (no filesystem) / limited support for DMF

**Comment by rderooy** [comment] 2021-10-04 11:49
This is a duplicate of https://github.com/joncampbell123/dosbox-x/issues/1472

**Comment by Allofich** [comment] 2021-10-04 11:52
Yes, and I have a comment, but I'll add it there as this issue is a duplicate.

**Closed** 2021-10-04 16:03 UTC
Labels: enhancement
