### ISSUE TITLE
dosbox-x - mouse insanely fast?

### ISSUE THREAD

**Issue by toddfraser88** [joncampbell123/dosbox-x#139] opened 2016-01-19 21:12 UTC
i just noticed, after successfully installing win98 in dosbox, my mouse insanely fast

I checked normal DOS games and the speed problem is present is normal dosbox environment too
It's impossible to click on anything.

I've set sensitivity to 1 in dosbox.conf, but is still very fast and is difficult to click on anything

I tried debugging to find what the mouse does, i only found this

LOG: 1026298335       KEYBOARD:AUX reset
LOG: 1026298600       KEYBOARD:PS/2 mouse sample rate set to 200
LOG: 1026298863       KEYBOARD:PS/2 mouse sample rate set to 100
LOG: 1026299126       KEYBOARD:PS/2 mouse sample rate set to 80
LOG: 1026299126       KEYBOARD:Intellimouse mode enabled
LOG: INT 15h reporting mouse device ID 0x03
LOG: 1026299660       KEYBOARD:PS/2 mouse resolution set to 8
LOG: 1026300312       KEYBOARD:PS/2 mouse scaling 1:1
LOG: 1026300575       KEYBOARD:PS/2 mouse sample rate set to 40
LOG: 1026302023       KEYBOARD:Activated
LOG: 1026390501       KEYBOARD:De-Activated
LOG: 1026390583       KEYBOARD:Activated

I probably missed something else, but this is what i could find

**Comment by sikthehedgehog** [comment] 2016-01-20 02:32
I noticed the mouse going too fast to be usable in System Shock using vanilla DOSBox too (didn't check if DOSBox-X suffered from this). It only happened in windowed mode though, with the mouse working fine in fullscreen ¯\(º_o)/¯ Can you check if that happens for you too? (to make sure if it's or not the same problem)

In my case this was 64-bit Ubuntu, in case anybody wonders.

**Comment by ghoul8765** [comment] 2016-01-20 03:28
Unable to reproduce the user error.

**Comment by ghoul8765** [comment] 2016-01-20 03:30
Unable to reproduce this issue. Is this a case of user error?

**Comment by toddfraser88** [comment] 2016-01-20 08:19
I tried in full screen, but the mouse speed problem persists unfortunately.

I'm running 64-bit Lubuntu, but I am using a 32-bit version of dosbox-x I compiled.

**Comment by joncampbell123** [comment] 2016-01-20 08:24
If you set auxdevice=3button (disable intellimouse emulation) does that resolve the issue?

[keyboard]
auxdevice=3button

**Comment by toddfraser88** [comment] 2016-01-20 08:40
it's still way too fast to be usable

I'll try the windows version of dosbox-x, see if the problem is there too

**Comment by toddfraser88** [comment] 2016-01-20 09:15
mouse performs normally on windows version

so should i assume it's something to do with linux and not dosbox?

**Comment by toddfraser88** [comment] 2016-01-20 14:26
cam you see  if you can replicate this problem on Lubuntu 14.04 yourself?

**Comment by toddfraser88** [comment] 2016-01-20 18:00
my bad

it's vmware that is causing this

**Comment by toddfraser88** [comment] 2016-01-20 18:50
LOG:  576316959 ERROR MOUSE:Unhandled videomode 69 on reset

this wouldn't have anything to do with it?

**Comment by joncampbell123** [comment] 2016-01-21 06:45
@toddfraser88 that mouse error usually has nothing to do with it.

Should I close this, since VMware is at fault?

**Comment by toddfraser88** [comment] 2016-01-21 19:22
yeah, close it.

**Closed** 2016-01-21 19:48 UTC
