### ISSUE TITLE
[PC-98] No sound in Flame Zapper Kotsujin 

### ISSUE THREAD

**Issue by TheLostNinja** [joncampbell123/dosbox-x#4206] opened 2023-04-24 16:42 UTC
### Describe the bug

This game doesn't play any sound on **any** PC-98 sound device.

### Steps to reproduce the behaviour

Mount [CO2-Pro (Flame Zapper Kotsujin).hdi](https://archive.org/download/NeoKobe-NecPc-98012017-11-17/doujinHomebrew.zip/%5BDoujin%20%26%20Homebrew%5D%2FCO2-Pro%2FCO2-Pro%20%28Flame%20Zapper%20Kotsujin%29%20%5BHD%5D.zip) as C:, then enter the "C:\**c**otsujin\**c**otsujin.com" (**don't** try to auto-boot this image because it causes the crash of emulator!). Just for sure you can check the presence of this bug few times more by choosing of all 4 PC-98 FM boards.

### What operating system(s) this bug have occurred on?

Windows 10 22H2

### What version(s) of DOSBox-X have this bug?

 dosbox-x-mingw-win64-20230401023040\mingw

### Additional information

[My_PC98.conf](https://www.mirari.fr/IDBd)

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by grapeli** [comment] 2023-04-24 18:49
It works without any problems.
`dosbox-x -set machine=pc98 -c 'imgmount c "./CO2-Pro (Flame Zapper Kotsujin).hdi"' -c "boot c:"`

[dosbox-x.Flame.Zapper.Kotsujin.webm](https://user-images.githubusercontent.com/452325/234088374-8500b272-7759-4d64-802b-6bd076ffbac5.webm)

**Comment by TheLostNinja** [comment] 2023-04-25 04:41
As it turned out to be, this game just isn't friendly to the **dynarec_x86**.

**Comment by aybe** [comment] 2023-04-25 08:39
Closing as it appears the problem is solved!

**Closed by aybe** 2023-04-25 08:39 UTC
Labels: bug, topic: audio, topic: PC-98
