### ISSUE TITLE
Nesticle hangs on load with "DYNREC:Can't run code in this page"

### ISSUE THREAD

**Issue by foone** [joncampbell123/dosbox-x#1355] opened 2019-11-18 21:46 UTC
**Describe the bug**
On loading the NES emulator Nesticle in DOSBox-X, it hangs the emulator while spamming the log full of "DYNREC:Can't run code in this page" errors. 
I tested specifically with version nestc021.zip from http://metopal.com/files/emulation/nesticles/nestc021.zip (from this page listing all the versions: http://metopal.com/2012/03/15/emulate-the-emulators/) but a spot-checked a few others and it seems they all hang. 

**To Reproduce**
1. Try to load NESTICLE.EXE from nestc021 .zip
2. DOSBox-X hangs and has to be force-closed.

**Expected behavior**
Not hanging or throwing some kind of error. DOSBox 0.74-2 seems to emulate Nesticle just fine. 

**Screenshots**

**Environment (please complete the following information):**
 - Windows 10, 1903: Version 10.0.18362 Build 18362
 - dosbox-x-windows-20191031-191254-windows.zip: x64\Release SDL2
 - Tested with default config file

Additionally, the source code to Nesticle (version 0.2, I believe?) is available (cause it was stolen), which could help with debugging:
https://archive.org/details/kronksrc

**Comment by joncampbell123** [comment] 2019-11-18 22:43
Perhaps (not yet looking at the source) Nesticle is doing some kind of dynamic code generation or self modifying code in some manner for performance?

That might confuse the dynamic core.

**Comment by joncampbell123** [comment] 2019-11-18 22:49
Ref:

http://metopal.com/2012/03/15/emulate-the-emulators/

**Comment by Allofich** [comment] 2019-12-10 11:20
Changing `vesa modelist cap` from its default of 0 to something else will allow it to run. I tried 16 and 8, both worked.

There was another issue not too long ago where it turned out that this setting at 0 causes Quake to fail to run:
https://github.com/joncampbell123/dosbox-x/issues/1194

and it also causes Warcraft II to fail, as noted in the comment in the .conf file.

**Comment by joncampbell123** [comment] 2019-12-10 17:00
That would do it. DOSBox-X's VESA modelist is too long for some DOS games to handle. That's what you get for using a fixed size buffer without checking.

**Comment by joncampbell123** [comment] 2019-12-25 09:58
It sounds like the problem is just Nesticle using a fixed size buffer for VESA modes. Closing.

**Closed by joncampbell123** 2019-12-25 09:58 UTC

**Comment by Allofich** [comment] 2019-12-25 10:23
Is it a problem that DOSBox-X hangs? There's been a few different times now that people report bugs that turn out to be because of the VESA mode setting, so maybe DOSBox-X could detect when this happens and close with an error message or something.

**Comment by joncampbell123** [comment] 2019-12-25 11:08
The dynamic core is designed for well behaved code, not code that is crashing.

It's not trivial to write something that can detect whether or not a program is used a fixed sized buffer for VESA modes.
