### ISSUE TITLE
Support for CHD format

### ISSUE THREAD

**Issue by whocares0101** [joncampbell123/dosbox-x#1822] opened 2020-09-03 20:22 UTC
**Is your feature request related to a problem? Please describe.**
I just tried to mount a CHD file and it did not work also I didn't find any info if this is even supported.

**Describe the solution you'd like**
Make it possible to mount CHD files with imgmount, at least cd/dvd images should work.
A lot of emulators support CHD files already.

**Additional context**
https://github.com/mamedev/mame
https://github.com/mamedev/mame/blob/master/src/tools/chdman.cpp

standalone library
https://github.com/rtissera/libchdr

**Comment by eadmaster** [comment] 2020-10-06 05:26
See also this: https://github.com/dosbox-staging/dosbox-staging/issues/166

**Comment by Wengier** [comment] 2020-10-06 05:31
I think it is certainly a reasonable suggestion. I will add it to Todo list.

**Comment by whocares0101** [comment] 2020-11-10 11:33
So I was playing around with this and got it working.
This only needs a bit of code in `cdrom.h` and `cdrom_image.cpp` but I don't know how to properly add the static libraries so it works with all platforms and where to put the new libs.
I had to add three static libraries for it to compile and work, FLAC.lib, lzma.lib, and chdr-static.lib.

Only tested this on windows with a debug sdl2 x64 build but I installed a few games and the cd audio was also working after some debugging.
It would be great if someone else could do the rest.

This uses the standalone library
https://github.com/rtissera/libchdr
To compile libchdr on windows some small changes need to be made
https://github.com/rtissera/libchdr/issues/39
Also note cmake used /MD instead of /MT which dosbox-x uses.

And here are the modified `cdrom.h` and `cdrom_image.cpp` files
[dos.zip](https://github.com/joncampbell123/dosbox-x/files/5516900/dos.zip)

**Comment by Wengier** [comment] 2020-11-11 01:43
@whocares0101 I am glad to hear that you made the effort to get it work! But yes, as you said your approach requires external libraries such as FLAC.lib, lzma.lib, and chdr-static.lib in order to compile, which only works for specific Windows Visual Studio builds.

I decided to further improve the code in my pull request so that external libraries are no longer required - all required source files are now built-in, and I have tested it on both Windows (Visual Studio, MinGW) and Linux and could confirm it works on these platforms. But I am sure further work can still be done regarding CHD support, such as support for parent images.

@dreamer and @kcgen I see there were discussions for CHD support in DOSBox Staging issue tracker too. In case you are interested, my commit for CHD image support in DOSBox-X is here: https://github.com/joncampbell123/dosbox-x/pull/1985/commits/4215f1027b6bd49e92952cd1213f1feea89eef15.

**Comment by dreamer** [comment] 2020-11-11 06:14
@Wengier any reason why `dr_flac.h` (header-only library, that we use in `src/lib/decoders/`) was not appropriate here?

**Comment by Wengier** [comment] 2020-11-11 06:20
@dreamer It appears that FLAC (instead of dr_flac.h) is a built-in component of the libchdr library (see here: https://github.com/rtissera/libchdr/tree/master/deps/flac-1.3.3), so it is needed and used by the librchdr library. But I have indeed thought of this too so that we could possibly make the libchdr libary work with ```dr_flac.h``` instead, but it will require some amount of work of course.

**Comment by kcgen** [comment] 2020-11-11 22:11
I pulled the latest code and did some testing; but wasn't able to get it working. 

## Mode 1/2352 Test

I first too a basic BIN/CUE pair (Jones in the Fast Lane) consisting of a data track and one audio track:

```
FILE "jones.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    FLAGS DCP
    PREGAP 00:02:00
    INDEX 01 02:47:53
```

Converted that to CHD using: `chdman createcd -i jones.cue -o jones.chd`.  (_Tip: install **mame-tools** if you don't have `chdman`_).

![2020-11-11_13-44](https://user-images.githubusercontent.com/1557255/98868102-77aa3c80-2424-11eb-8bb0-bd6367fd8530.png)

However, it fails to mount:

![2020-11-11_13-49](https://user-images.githubusercontent.com/1557255/98868410-eab3b300-2424-11eb-915d-c83c74a2f1a2.png)

## MODE1/2048 Test

I decided to try a simpler CHD, this one generated from a local directory:

![2020-11-11_13-53](https://user-images.githubusercontent.com/1557255/98868674-5c8bfc80-2425-11eb-8a06-841fcdadd613.png)

I converted that to an ISO: `mkisofs -lJR -o test.iso test`, and generated a CUE for it:

```
FILE "test.iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
```

With the CUE, I could now generate a CHD: `chdman createcd -i test.cue -o test.chd`

![2020-11-11_13-43](https://user-images.githubusercontent.com/1557255/98868103-7842d300-2424-11eb-9618-6a72d2f500d1.png)

However that also failed to mount:

![2020-11-11_13-50](https://user-images.githubusercontent.com/1557255/98868408-ea1b1c80-2424-11eb-8036-5781d0a8d8d5.png)

I tried the menu -> Drive image mount:

![2020-11-11_12-02](https://user-images.githubusercontent.com/1557255/98868108-78db6980-2424-11eb-8dd5-c3236c80ea4a.png)

I noticed CHD didn't show up in the list of file types (above), so selected `*.*` and then chose the CHD:

![2020-11-11_13-41](https://user-images.githubusercontent.com/1557255/98868107-78db6980-2424-11eb-9382-d0947aa6d2e6.png)

I'm now wondering if CHD-stuff is in the code?

It cleaned my repo area (`git clean -fdx`) and grepped for it: `git grep CHD` and `git grep chd`, however there is too much binary content checked in, so I wasn't able to confirm.

@Wengier , how can I be sure I'm using the CHD code?  Were you able to verify it worked (or can with the steps above?)

I also try checking out your commit you mentioned, but can't find it:

``` text
[02:01:56@server dosbox-x] (master) git checkout 4215f1027b6bd49e92952cd1213f1feea89eef15
fatal: reference is not a tree: 4215f1027b6bd49e92952cd1213f1feea89eef15
```

**Comment by Wengier** [comment] 2020-11-11 23:53
@kcgen If menu -> Drive image mount did not show CHD at all as you mentioned, then it simply means you were not using the code with CHD support. Right now the code with CHD support is still in https://github.com/wengier/dosbox-x, not the master branch of this repository. Please check out the code at https://github.com/wengier/dosbox-x instead.

**Comment by kcgen** [comment] 2020-11-12 00:03
> Right now the code with CHD support is still in https://github.com/wengier/dosbox-x

:facepalm: My bad -- thank you for the correct pointer Wengier!

**Comment by whocares0101** [comment] 2020-11-12 00:04
I had another idea to improve the loading speed by using a prefetch thread to offload sequential reads to another core.
No idea how much this affects speed but it should help mitigate decompression times a bit.
[chd_thread_prefetch.zip](https://github.com/joncampbell123/dosbox-x/files/5527457/chd_thread_prefetch.zip)

**Comment by whocares0101** [comment] 2020-11-12 01:25
I only tested raw cd images and 2048 images did not work.
This just subtracts 16 from the read buffer offset to account for the missing sync header for 2048 sector images.
Now both 2048/2352 images should work.
[chd_skip_sync_fix.zip](https://github.com/joncampbell123/dosbox-x/files/5527665/chd_skip_sync_fix.zip)

**Comment by kcgen** [comment] 2020-11-12 01:56
> I only tested raw cd images and 2048 images did not work.

Thanks for the heads up @whocares0101!

CHD's generated from 2048-byte sector ISO+CUEs are actually perhaps the most important, because this opens up the generic scenario for users to generate a CHD from a bog-standard directory (using the above `mkisofs` as a middleman); where as CHDs from 2352-byte sector BIN+CUEs can only be strictly created from CDROM dumps, as there is no easy way to convert a directory into a BIN+CUE pair (well, besides burning it to a physical CD and then dumping it as a raw BIN+CUE). 

I would like to hold off on testing further. @Wengier , I'm guessing you'll get these in when time permits. I'll keep an eye out and be ready to test various scenarios when ready!

@whocares0101, the read-ahead is indeed a good idea (although I'm biased :-) ). This is currently in the queue for libchd: https://github.com/rtissera/libchdr/issues/34, as is an LRU cache: https://github.com/rtissera/libchdr/issues/36

The libchd team is very cooperative, and ideally those features would land there - so all applications using libchd will benefit from these performance improvements.

**Comment by Wengier** [comment] 2020-11-12 06:28
@whocares0101 Thanks for the update! Yes, as @kcgen said they are certainly good improvements. I have already incorporated the changes here: https://github.com/joncampbell123/dosbox-x/pull/1985/commits/50b098cad0873751d731bdb586d91e4f8d331ac5. I did not get the time to do additional testing yet, but I have checked the files I created earlier and they indeed worked fine. Please keep us informed when you make further progress. Thanks!

**Comment by kcgen** [comment] 2020-11-12 15:26
Tiny build fix.. 
![2020-11-12_07-20](https://user-images.githubusercontent.com/1557255/98958954-ab827200-24b7-11eb-852c-4c04b4c21ab1.png)

Problem is the flac directory on disk is capitalized:

![2020-11-12_07-22](https://user-images.githubusercontent.com/1557255/98959184-e684a580-24b7-11eb-9005-d32d8f6d0485.png)

Given `libchdr` includes uppercase FLAC, suggest we follow that in `cdrom_image.cpp`:

```
../../src/libs/libchdr/flac.h:17:10: fatal error: FLAC/all.h: No such file or directory
   17 | #include "FLAC/all.h"
      |          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by kcgen** [comment] 2020-11-12 16:53
Things are working mostly as expected:

## Mode 1/2352 Test

I first too a basic BIN/CUE pair (Jones in the Fast Lane) consisting of a data track and one audio track:

```
FILE "jones.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    FLAGS DCP
    PREGAP 00:02:00
    INDEX 01 02:47:53
```

Converted that to CHD using: `chdman createcd -i jones.cue -o jones.chd`.  (_Tip: install **mame-tools** if you don't have `chdman`_).

![2020-11-11_13-44](https://user-images.githubusercontent.com/1557255/98868102-77aa3c80-2424-11eb-8bb0-bd6367fd8530.png)

The pregap doesn't seem to be properly handled on the DOSBox side (in the above screenshot, note that tracks 2 includes 150 seconds of pregap). 

The error manifests in seeks being positioned two frames (2 * 75 seconds) further ahead than they should be. So in this case, the voice CD-DA sections jump into the middle of their sentences. The immediate work-around is to knockout the `pregap` line in the CUE before feeding it to CHDMAN (note `PREGAP:0` now):

``` text
Metadata:     Tag='CHT2'  Index=1  Length=89 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:165952 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0.
```

The CUE and pregap handling is in `cdrom_image.cpp`.  It's pretty mess.. but ideally you can re-use that "TrackAdd()" function and read the pregap values from the CHD library and mimic the same behavior as the current code does when it reads a CUE file.

Basically any pregap values "push" the position of the audio track (and all subsequent audio tracks) outward in time. 

## MODE1/2048 Test

Creating a non-CD-DA ISO image from a local directory:

![2020-11-11_13-53](https://user-images.githubusercontent.com/1557255/98868674-5c8bfc80-2425-11eb-8a06-841fcdadd613.png)

And then to an ISO: `mkisofs -lJR -o test.iso test` with CUE file:

```
FILE "test.iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
```

And then to CHD: `chdman createcd -i test.cue -o test.chd`

![2020-11-11_13-43](https://user-images.githubusercontent.com/1557255/98868103-7842d300-2424-11eb-9618-6a72d2f500d1.png)

Mounts clean and and binary data can be read; however I didn't test this extensively. 

## Nice to haves

Ideally we could use CHD to store content for further mounting, such as for C:\ and then CDROM image/iso/audio track files.  So all full DOS game could be represented inside a single CHD file.

However, right now using `mount` or `imgmount` to mount files stored inside the CHD directory doesn't work. I'm not sure what it would take to get that working.

**Comment by Wengier** [comment] 2020-11-13 04:19
@kcgen Thanks for the testing! I am glad to hear that things are working mostly as expected. And yes, performing an imgmount with an image inside an image is indeed nice to have as you said. In fact if this can be supported maybe it can be extended to other types of disk images as well.

Also, you are certainly right that the subdirectoy is an uppercased one (FLAC) instead of lowercase (flac). I have already updated the include in cdrom_image.cpp accordingly. Thanks for pointing this out!

**Comment by Torinde** [comment] 2023-02-11 14:23
@rderooy , should CHD support be mentioned in the [wiki](http://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X)?

**Comment by rderooy** [comment] 2023-02-11 14:56
Was this ever merged?

**Comment by Torinde** [comment] 2023-02-11 23:18
Not sure, but it's mentioned at https://github.com/joncampbell123/dosbox-x/blob/0a82937e03e3244ab0f927b791260a3cefcf82d4/CREDITS.md

**Comment by rderooy** [comment] 2023-02-12 09:25
I can confirm it worked. I installed 'mame-tools' from my Linux distro package manager to get 'chdman'. Then I converted a Cue/Bin set to CHD.
```bash
$ chdman createcd -i Monkey\ Island\ Madness\ \(USA\).cue -o test.chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.251 (unknown)
Output CHD:   test.chd
Input file:   Monkey Island Madness (USA).cue
Input tracks: 25
Input length: 59:48:56
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
Logical size: 659,001,600
Compression complete ... final ratio = 44.9%
```
A nice reduction in filesize...

Then I mounted the CHD in DOSBox-X as usual.
```dos
Z:\>imgmount d test.chd
MSCDEX installed.
Drive D is mounted as test.chd
```

**Comment by rderooy** [comment] 2023-02-12 10:26
I updated the draft wiki to mention CHD image support.

Too bad CHD is so niche, otherwise it would be cool to convert my cue/bin collection to them.

- No support in other DOSBox variants
- No support in 86Box or PCem
- No support in ScummVM
- No way to mount them on Linux, Windows or macOS, without first converting them back

**Comment by Torinde** [comment] 2023-02-12 15:49
I don't know where to see the draft wiki - will it appear published at release time?

**Comment by rderooy** [comment] 2023-02-12 16:36
The draft is located here: https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X

Since it also contains some other updates for VHD and QCOW2, which is yet to be merged, I will ask for it to be pulled with the next release.

**Comment by rderooy** [comment] 2023-02-12 16:48
Also, I think this issue can be closed...

**Comment by Torinde** [comment] 2023-02-13 07:12
Are HDDs also supported in CHD format - or only CD/DVD?

**Closed** 2024-09-10 02:37 UTC
Labels: feature request
