### ISSUE TITLE
Willy Beamish "Smart Start" installer doesn't work correctly.

### ISSUE THREAD

**Issue by nightson** [joncampbell123/dosbox-x#4031] opened 2023-02-22 15:15 UTC
### Describe the bug

Willy Beamish "Smart Start" installer doesn't work correctly.

### Steps to reproduce the behaviour

1.Mounted disk images to A:
2.Go to A:\ and Type INSTALL
3.Dynamix Smart Start installer runs, but the menu doesn't have the installation option.

![2023-02-22_230901](https://user-images.githubusercontent.com/843241/220664426-7134e23c-8a1e-417c-921f-e4ff097d227c.png)

### Expected behavior

Mounting the images under PCem works but it will give a disk read error once you choose the installation option.
![QQ图片20230222230632](https://user-images.githubusercontent.com/843241/220663997-f64312af-66aa-4706-8ff9-1cea5abf0863.png)
 
![QQ图片20230222230626](https://user-images.githubusercontent.com/843241/220663922-bb7c2f5b-1a8a-4f83-860e-272d672d9761.png)

### What operating system(s) this bug have occurred on?

DOS

### What version(s) of DOSBox-X have this bug?

2022.12.26

### Additional information

Disk images: https://mega.nz/file/95USSAjb#EJJTuchpXeREjFu9N9nPPriI7GhYoaJvD0mdtfTLsp8

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment] 2023-02-22 16:15
From the dosbox-x output it seems you did not mount a C: drive?

e.g., something like:
```
mount c /home/user/dosgames
```

**Comment by grapeli** [comment] 2023-02-22 18:18
This installer behaves the same in dosbox-staging and dosbox-svn. DOSBox-X is no exception.

**Comment by nightson** [comment] 2023-02-23 02:13
> @rderooy this installer bug seems similar to these two others related also to games developed by Dynamix:
> 
> * Nova 9 DOS game (Dynamix, Inc.) does not find the hard disk during the installation [Nova 9 DOS game (Dynamix, Inc.) does not find the hard disk during the installation #3187](https://github.com/joncampbell123/dosbox-x/issues/3187)
> * Stellar 7 DOS game (Dynamix, Inc.) does not find the installation floppy disk [Stellar 7 DOS game (Dynamix, Inc.) does not find the installation floppy disk #3175](https://github.com/joncampbell123/dosbox-x/issues/3175)

Looks like Nova 9 installer behaves the same as this one. Thanks for mentioning those bugs!

**Comment by nightson** [comment] 2023-02-23 02:14
> From the dosbox-x output it seems you did not mount a C: drive?
> 
> e.g., something like:
> 
> ```
> mount c /home/user/dosgames
> ```

I did mount a C: drive. It's just that the installer couldn't detect it somehow.

**Comment by Allofich** [comment] 2023-02-23 08:11
The install option does appear if you boot DOSBox-X from an MS-DOS image, rather than running from DOSBox-X's emulated DOS. This suggests DOSBox-X's emulation of the DOS environment isn't matching up with MS-DOS behavior.

**Comment by Allofich** [comment] 2023-02-23 08:30
Seems like @halcyon00 may have made some progress on these issues and opened a PR for it (https://github.com/joncampbell123/dosbox-x/pull/3274/files) but closed it with the comment "there's a bug in how DOS_MakeName assumes that it can follow filename rules even for volume labels, and it does an implicit trim to the volume's "filename" portion to remove spaces, and thus fails the comparison".

**Comment by halcyon00** [comment] 2023-02-23 09:24
There’s a lot of code that plays pretty loose with handling file names as strings within dosbox-x.  It generally does the right thing when handling filenames, but because the volume label is technically a special file entry that follows DIFFERENT rules, this code ends up munging some volume labels that, say, contain spaces between the 8 and . 3 parts.  

That’s what causes the installer media check to fail when it does a wildcard search for the volume entry.  

I didn’t see an easy way to correctly fix the problem without changing a lot of filename handling or putting in a specific hack.   Booting with real dos interrupt handlers is probably the correct choice unless someone more familiar with the code wants to make it more correct.    There’s a bunch of code for doing LFN handing and so on, so I wasn’t comfortable trying to fix it up without a bigger test suite to verify my changes against.

**Comment by Allofich** [comment] 2023-02-23 10:04
> I wasn’t comfortable trying to fix it up without a bigger test suite to verify my changes against.

Just my opinion, but I think if you want to try and can verify that the Dynamix installers and perhaps one or two other test cases work, that would be enough to send in a PR. You can see the DOSBox-X project doesn't have a lot of old, pending PRs like other projects. Seems to be more of an add in new code while it's fresh, and then fix if any issues if they come up approach. Of course if you'd rather not work on the issue for whatever reason, I think that's fine, too.

**Comment by Allofich** [comment] 2023-02-23 11:22
Looks like #3175 is a different issue. Unlike with Willy Beamish and Nova 9, the installation option does appear in the Stellar 7 installer, even when running from the DOSBox-X DOS emulation.

I just tried #3274 (by applying the changes to current code) and it does fix #3175. However, it does not fix the installation option not appearing in the Willy Beamish or Nova 9 installers.

**Comment by halcyon00** [comment] 2023-02-23 12:08
It’s actually just a lucky coincidence that STELLAR7 is 8 characters exactly, so it doesn’t get affected by the truncation issue and passes the initial check.  Then fails at a later check for the specific disk number.  

AFAIK the problems are all caused by the same root cause of improper treatment of volume label entries with 8.3 file name conventions.  Just different symptoms.

**Closed** 2023-03-07 04:31 UTC
Labels: bug, DOS: gaming
