### ISSUE TITLE
Cannot mount with Chinese/Japanese path or file name

### ISSUE THREAD

**Issue by crashGG** [joncampbell123/dosbox-x#2356] opened 2021-03-11 21:12 UTC
Cannot mount with Chinese/Japanese path or file name on dos mode ，But  can mount successfully on "pc-98" mode

**Comment by Wengier** [comment] 2021-03-12 18:07
In PC-98 mode the code page 932 is used for Japanese character support. On the other hand, in standard mode DBCS code pages are not yet supported. But thanks for reporting this, as better DBCS support is definitely desired for DOSBox-X.

**Comment by Diatonator** [comment] 2021-04-03 22:18
I really +1 on that one, as I have my game ISOs in the long Russian paths, and ISOs themselves are named in Russian. It will be pretty annoying to rename/repath each ISO I want to mount, if choosing from like 200 of them.
Should it have a separate issue for Russian for instance, or all "support for foreign characters in mount in dos mode" will be tracked here?

**Comment by Wengier** [comment] 2021-04-04 02:05
Paths with Russian characters are slightly different from paths with Chinese/Japanese characters in that they are not DBCS characters and DOSBox-X should be able to access them with the correct code page (e.g. 808/866 for Russian). It is just that MOUNT/IMGMOUNT commands were not able to handle them correctly on some platforms (e.g. Windows). If you indeed use Windows, can you try the updated Windows binary below and see how it works? Thanks.

* [dosbox-x-update.zip](https://github.com/Wengier/dosbox-x-wiki/raw/master/dosbox-x-update.zip)

P.S. Make sure to run `keyb ru` (or `keyb ru 866`) before trying to mount files/paths with Russian names.

**Comment by Diatonator** [comment] 2021-04-04 17:04
Tried the binary.
For this path:

`D:\GameStorage\Сборники3\Triada CD\Triada CD (201-220)\210. Игры для IBM 486 и Pentium I выпуск 15 (Fixed)\Игры для IBM 486 и Pentium I выпуск 15 (Fixed).iso`

I get this:

```
Z:\>keyb ru 866
Keyboard layout ru loaded for codepage 866
Z:\>IMGMOUNT F "D:\GameStorage\╨б╨▒╨╛╤А╨╜╨╕╨║╨╕3\Triada CD\Triada CD (201-220)\2
10. ╨Ш╨│╤А╤Л ╨┤╨╗╤П IBM 486 ╨╕ Pentium I ╨▓╤Л╨┐╤Г╤Б╨║ 15 (Fixed)\╨Ш╨│╤А╤Л ╨┤╨╗╤П
 IBM 486 ╨╕ Pentium I ╨▓╤Л╨┐╤Г╤Б╨║ 15 (Fixed).iso"
The image must be on a host, local or network drive.
Must specify image file(s) to mount.
Z:\>
```

Basically nothing changed.
`keyb ru 866` seems to be working overall, I can see the Russian text, type/paste it, but mounting - nope.

Shorter paths fail too if they have Russian letters in them.

**Comment by Diatonator** [comment] 2021-04-04 17:09
Actually it worked when I did it from the console manually! It just failed when I put it in the [autoexec] of the conf file.

**Comment by Wengier** [comment] 2021-04-04 19:24
@Diatonator Yes, it will work when you enter the command(s) from the DOS command-line, probably also from the "Drive" menu. On the other hand, the reason that it did not work when you put the command(s) in the [autoexec] of the config file is probably that you did not save the config file in the correct encoding. The encoding for the file is very important in this case, because DOSBox-X cannot easily know exactly which encoding the config file (as a text file) is being saved. For the Russian language, try save the config file in code page 866, and then copy and paste the command you typed in the DOS command line to the config file. I have tried myself and can confirm it will work if it is saved this way. Hope this helps.

**Comment by Diatonator** [comment] 2021-04-04 19:36
Good to know! I hope this tip will be added in the help/wiki pages as this thing may cause some head bashing for sure.

**Comment by Wengier** [comment] 2021-04-04 19:43
@Diatonator Yes, it can certainly be added to Wiki pages. Thanks for your suggestion. Since the update was made after version 0.83.12, it will probably only work for the current and future builds, instead of 0.83.12 or earlier release versions.

**Comment by Wengier** [comment] 2021-05-12 11:31
With the code in #2519 Chinese/Japanese/Korean paths can now be displayed and mounted in the standard mode using TrueType font (TTF) output (`output=ttf`), using corresponding code pages (932/936/949/950). Also, with this output and the correct code page and a suitable TTF font Chinese/Japanese/Korean DOS text-mode applications may correctly display CJK characters in DOSBox-X's TTF output as intended. Below is a screenshot of running Softscape PC Tools in DOSBox-X:

![image](https://user-images.githubusercontent.com/8216923/117966492-f4de3d80-b2f1-11eb-822b-cd08eb1bde08.png)

**Comment by Wengier** [comment] 2021-06-03 05:39
With the release of DOSBox-X 0.83.14 I believe this problem is now fully solved. Closing.

**Closed by Wengier** 2021-06-03 05:39 UTC
Labels: feature improvement, task, topic: MS-DOS
