### ISSUE TITLE
DOSBox-X Windows 95 guest crashes after using "Change current CD image..." from menu.

### ISSUE THREAD

**Issue by frank-deng** [joncampbell123/dosbox-x#2894] opened 2021-09-09 02:06 UTC
Once I use "Change current CD image..." from menu to select a CD-ROM image, system will become unstable and the emulator crashes easily. For example:

With Windows 95 guest system + `svga_s3vision864` video card, when I use this function to load a CD-ROM image then powering off Windows 95, the emulator will crash with the following message in some cases:

<img width="194" alt="unimplemented XGA MMIO" src="https://user-images.githubusercontent.com/8265668/132609963-8aa3686d-1e1e-451f-a16e-1f9cb6d3a6be.png">

Sometimes crash with garbled screen or with emulator freezed.

Also when I use "Change current CD image..." then switch to Display Settings, the emulator will freeze or crash as well.

**Comment by rderooy** [comment] 2021-09-09 06:22
FYI
All the s3 card options should, I think, be considered experimental especially with Win9x. With the exception of ``svga_s3`` which is the ``svga_s3trio64``.

**Comment by frank-deng** [comment] 2021-09-09 07:32
I changed the video adapter into `svga_s3` and used video driver `S3` under Win95 guest, the emulator still freezes either during powering off or opening display option once I used "Change current CD image..." from menu and select a CD-ROM image.

I'm not sure whether "Change current CD image..." feature will corrupt the emulator's RAM or any other things.

**Comment by frank-deng** [comment] 2021-09-09 10:51
I've analyzed the code of 0.83.17, it seems that calling `UnMount()` on an ATAPI CD-ROM drive while guest os is running caused the trouble and brought the emulator down.
<img width="590" alt="unmount trouble" src="https://user-images.githubusercontent.com/8265668/132673058-2ba9f126-ae3c-4787-b305-7f74d6efbe4e.png">

**Comment by Wengier** [comment] 2021-11-10 10:41
@frank-deng I did take a look at it, but I don't think the said issue with changing CD is caused by UnMount(), because "old" in such case is NULL (it cannot be casted to a fatDrive), so UnMount() is not executed when you change CDs. On the other hand, UnMount() is called while changing floppy images, which does not appear to cause such an issue.

**Comment by Wengier** [comment] 2021-11-11 03:57
@frank-deng It is a bit tricky, but after further investigations, I think I have fixed the problem. Please check out the updated Windows build:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by frank-deng** [comment] 2021-11-11 12:59
Thanks~ the newly updated dosbox-x no longer crashes my Windows 95 when using "Change current CD image...".

**Comment by Wengier** [comment] 2021-11-13 00:32
Glad to hear it works. Closing.

**Closed by Wengier** 2021-11-13 00:32 UTC
Labels: bug, topic: Windows, topic: storage
