### ISSUE TITLE
Hello, it has been about a year since I reported Spycraft: The Great Game crashes dosbox-x. It's weird since your version is the only one that crashes. I really like you version. It is featured-rich and small. Only 2 files needed (exe and conf). I hope one day you discover the cause. The crash occurs at the same point in the game ever time; about 80% in the game. Good luck with!  

### ISSUE THREAD

**Issue by github-fanuser** [joncampbell123/dosbox-x#1407] opened 2020-02-12 14:04 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joncampbell123** [comment] 2020-02-16 07:15
Duplicate of #923

**Closed by joncampbell123** 2020-02-16 07:15 UTC
