### ISSUE TITLE
Paste text into dosbox-x

### ISSUE THREAD

**Issue by phly95** [joncampbell123/dosbox-x#897] opened 2018-10-10 04:12 UTC
It would be extremely useful to have a paste functionality built into the Main>Send Key menu, especially when mounting files that are so deep in the HDD that typing it all out manually would be impractical. Or at least having the ability to drag an HDI file to DOSBOX-X and have it mount automatically.

**Comment by Mored1984** [comment] 2019-06-26 13:40
![image](https://user-images.githubusercontent.com/5413459/60184577-f81ccd00-9830-11e9-91fb-4de85c7b46f2.png)


Useful function if I can paste text to DOSbox-x like below

C:\Users\Mored1984\Desktop\ASTORM\astorm

**Comment by Mored1984** [comment] 2019-06-26 14:08
****
![image](https://user-images.githubusercontent.com/5413459/60186633-dd4c5780-9834-11e9-9207-8481533b4033.png)

Even after mapper editor (Paste text to DOSBox-x) not working

**Comment by emendelson** [comment] 2019-06-26 14:51
I can confirm that this isn't working. The PasteClipboard code has my name attached to it because I took it out of an early version of the dbDOS project and added it to DOSBox. It certainly worked in DOSBox-X a year or so ago, when I suggested this revision and Jon responded to it:

https://github.com/joncampbell123/dosbox-x/issues/481

I don't know when it stopped working. I build with this in sdlmain.cpp line 3371, to map Paste Clipboard to Ctrl-Alt-F4, and it used to work:

MAPPER_AddHandler(PasteClipboard,MK_f4,MMOD1|MMOD2,"paste", "Paste Clipboard");

**Comment by emendelson** [comment] 2019-06-26 15:53
And for what it's worth, it stopped working in my builds sometime between September 29, 2017 (my build pastes from the clipboard) and November 4, 2017 (my build doesn't paste from the clipboard).

Oddly, I think I got the November 4, 2017 build to paste correctly one time I tried it, but I can't repeat it.

**Comment by joncampbell123** [comment] 2019-06-26 16:44
If you use the Paste Clipboard keyboard shortcut does it light up in the mapper?

**Comment by emendelson** [comment] 2019-06-26 22:37
Do you mean "Is Paste Clipboard highlighted in the mapper?" If so, yes - see the screen shot above. But maybe that isn't what you're asking??

**Comment by joncampbell123** [comment] 2019-06-26 23:01
I mean if you type the keyboard shortcut that is assigned to "Paste Clipboard" does it light up (invert)?

**Comment by joncampbell123** [comment] 2019-06-26 23:02
For example hitting other keys on the keyboard in the mapper should make the key light up in the mapper interface. It's not a green tint, it's an inverted scheme when hilighted: black text on a white box instead of white text in a white frame.

**Comment by emendelson** [comment] 2019-06-26 23:13
Sorry, I misunderstood what you (very clearly) meant. Yes, the key lights up in the mapper interface. Here's a screen shot taken with a delay. As I said, I use Ctrl-Alt-F4 for the Paste Clipboard key.

![Capture](https://user-images.githubusercontent.com/5208505/60221125-73d54480-9846-11e9-95e6-4df443f32a79.PNG)

**Comment by emendelson** [comment] 2019-12-09 02:47
Could I ask again about this one? PasteClipboard was very good to have, and the necessary underlying code seems to be there in the SDL source. I've experimented with this, but I'm nowhere near being able to fix it.

**Comment by emendelson** [comment] 2020-04-18 12:18
@Wengier - Now that you have done such terrific work on ClipboardPaste, is it possible to make it work under SDL2 in addition to SDL1? I have some users who use non-US keyboard layouts that work best in the SDL2 builds, and I would like to make it possible for them to use ClipboardPaste. Thank you!

**Comment by Wengier** [comment] 2020-04-18 18:12
@emendelson and @joncampbell123 I have checked the code. Basically the existing PasteClipboard code was exclusively written for SDL1, and was completely disabled for SDL2, which is why it did not work on the SDL2 build at all. Thus, making the feature work on SDL2 build requires major rewriting the code for SDL2. However, I agree that it is certainly better for the feature to work in some way than completely broken as it is now in the SDL2 build, so I decided to implement it for SDL2 by using some code from my earlier mouse copy/paste patch for DOSBox (as in https://www.vogons.org/viewtopic.php?f=41&t=41179). With the patch it should work as expected, but the catch is that if you want to paste long contents from the Windows clipboard in the SDL2 build, you will need to load a keyboard buffer expansion program such as keybuf.com ([http://individual.utoronto.ca/wengier/files/keybuf.com](url)) in DOSBox-X (just once) before doing the pasting. For example, "KEYBUF.COM 1024" will expand the keyboard pasting buffer to 1024 characters (you can put this command in the [autoexec] section of dosbox.conf). Pasting in the SDL1 build is not affected so there is no need to load this program for the SDL1 build.

So I have made a patch for DOSBox-X that allows the existing PasteClipboard feature to work in the SDL2 build (instead of doing nothing). It also includes some minor cleanups such as fixing for the Issue #1477 ("Decrease IDE ATA command logging") and support for DOSLIB2's w95sysrs utility. The diff file for the latest commit c625785 is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-c625785-patch.diff

**Comment by Wengier** [comment] 2020-04-18 22:49
@joncampbell123 and @emendelson I think it would be a better idea to port the entire mouse copy/paste feature to DOSBox-X so that you can use the right mouse button to select, copy and paste text from and to DOSBox-X (when the mouse is not locked), at least for the Windows platform. So I updated the patch to support this feature. By default this feature is disabled, but you can easily enable it or change the keyboard modifier (no modifier, Alt, Left Alt, or Right Alt) with the new config option "clipboardmodifier" in Windows builds. You can set it to "none" if no keyboard modifier is desired when copying/pasting with the right mouse button.

Since it uses the current code in DOSBox-X for pasting, there is no limit on the clipboard size when pasting using right mouse button (if enabled) on SDL1 build. On the other hand, for the SDL2 build, (if enabled) it will be the same as using the updated PasteClipboard function in my previous post, so it is recommended to load a keyboard buffer expansion program like keybuf.com (as mentioned earlier) before doing the pasting.

The diff file for the latest commit c625785 is still available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-c625785-patch.diff

A pre-compiled Windows 64-bit binary (SDL1 version) is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-update.zip

And a pre-compiled Windows 64-bit binary (SDL2 version) with keybuf.com included is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-update-sdl2.zip

Note: For the purpose of easier testing, the mouse copy/paste feature is enabled in dosbox.conf that is included with the above Windows builds.

**Comment by Wengier** [comment] 2020-04-19 17:30
I made a few small cleanups for the new clipboard feature and some related code. For example, the "clip_key_modifier" config option now supports (L or R) Ctrl and (L or R) Shift as the keyboard modifier, and I moved the "dos clipboard paste speed" config option recently added by @emendelson from the [dos] section to the [sdl] section (with the new name "clip_paste_speed") because it really belongs to the latter section. Also fixed the crash at DOSBox-X startup if this option (i.e. "dos clipboard paste speed"/"clip_paste_speed") is set to 0 (it caused crash before of the division by 0 error).

I think the clipboard copy/paste feature is pretty stable by now. The latest diff file for the most recent commit 471bee7 is now available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-471bee7-patch.diff

**Comment by Wengier** [comment] 2020-04-21 19:03
I have created a draft Wiki page which explains different ways to copy to and paste from the Windows clipboard in DOSBox-X:

https://github.com/Wengier/dosbox-x-wiki/wiki/Guide%3AClipboard-support-in-DOSBox%E2%80%90X

**Comment by emendelson** [comment] 2020-04-25 14:36
@Wengier - in the current code, build in VS2019, config -set "sdl clip_paste_speed=###" doesn't seem to have any effect in either SDL1 or SDL2. I can't slow down or speed up pasting by changing the number. If I set it at (for example) 100 in the conf file, pasting will be slowed to 100, and can't be changed from the command line. 

I don't understand this at all, but my original patch for paste speed allowed changing the number from the command line. Your version is obviously more efficient and expert, but I wonder if this ability got lost?

**Comment by Wengier** [comment] 2020-04-25 21:13
@emendelson The functionality of the config -set command is currently still limited. You cannot not dynamically change all the config options at this time. But in the past a few days (or weeks) I have been adding a centralized place for dynamically changing some of the config options, such as the nocachedir and "leading colon write protect image" config options. The clip_paste_speed config option was not yet added to this place in the last patch, because I did not know you want to change  this option at runtime too. But in the most recent patch I posted in Issue #1487, I have already added freesizecap, clip_key_modifier and clip_paste_speed config options into this place too so that you can change all of them at the runtime. Hope this helps.

**Comment by emendelson** [comment] 2020-04-26 02:05
@Wengier - That sounds like an excellent solution, and better than the code that I originally offered. I'll look forward to the latest patch.

The ability to change the paste speed dynamically seems useful, because a user can experiment to find a number that works with the application they're using, and then assign that number in the conf file.

**Comment by emendelson** [comment] 2020-04-26 20:49
@Wengier - The latest code works perfectly to change paste speed under SDL1. Thank you!

**Closed** 2020-09-02 04:56 UTC
Labels: enhancement, topic: input
