### ISSUE TITLE
IMGMOUNT hangs for creating a large ram disk after merging pull request #596

### ISSUE THREAD

**Issue by yksoft1** [joncampbell123/dosbox-x#598] opened 2018-03-10 18:23 UTC
Use this command:
> imgmount c -t ram -size 128000

Then Dosbox-X hangs.
Is it only on MinGW or will occur on a VS2017 build?

**Comment by joncampbell123** [comment] 2018-03-10 18:40
That's a question for @Shane32. He may have fixed it in the latest pull request given to me.

**Comment by Shane32** [comment] 2018-03-10 19:35
Fixed in pull #599

**Comment by Shane32** [comment] 2018-03-10 23:47
Can you confirm the issue is fixed in MinGW, @yksoft1 ? I only have VS2017.

**Comment by joncampbell123** [comment] 2018-03-11 00:04
While you're waiting, there's a typo in the C++ class.

https://www.vogons.org/viewtopic.php?f=41&t=31881&p=656664#p656664

**Comment by yksoft1** [comment] 2018-03-11 05:07
Seemed that it was OK now on MinGW.
@joncampbell123

**Comment by Shane32** [comment] 2018-03-11 15:38
Fixed the type-o with #603 
Also realized my image sizing was based on ATA limits instead of BIOS/MBR limits so I fixed that
Added a bunch of logging so you can see what c/h/s it selects when creating an image

**Comment by Shane32** [comment] 2018-03-11 15:39
I tried to test it thoroughly.....but let me know if you find any issues!

**Comment by Shane32** [comment] 2018-03-12 00:00
I suggest we close this issue now.

**Comment by joncampbell123** [comment] 2018-03-12 00:19
Sounds good to me

**Closed by joncampbell123** 2018-03-12 00:19 UTC
