### ISSUE TITLE
Display glitches in game "Continuing adventures of Cyberbox"

### ISSUE THREAD

**Issue by viki-t-s** [joncampbell123/dosbox-x#3090] opened 2021-11-19 21:22 UTC
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Manjaro Linux, Windows 10

### What version(s) of DOSBox-X have this bug?

all versions since 0.83.15 (earliest one I tested on) till the latest Git

### Describe the bug

Garbled output when opening specific menu in game. Also screen artifacts after closing the same. The display alone is affected but not function. As long as the options or jump screen menu is not opened, the game runs without any weird behaviour.
Garbled options menu

![Screenshot_20211120_015402](https://user-images.githubusercontent.com/70179464/142692398-8903b844-aff3-4791-83f6-38a99e671f2f.png)
Display artifacts after closing

![Screenshot_20211120_022646](https://user-images.githubusercontent.com/70179464/142692528-0da0cec1-5ea6-452a-bea5-8d7f11b93230.png)

Compressed Game directory attached - is freeware
[cyberboxdlx.tar.gz](https://github.com/joncampbell123/dosbox-x/files/7572977/cyberboxdlx.tar.gz)

### Expected behavior

Screenshots taken from Dosbox-Staging for expected behaviour where this glitch does not happen
Options menu
![Screenshot_20211120_015618](https://user-images.githubusercontent.com/70179464/142692665-88c94a0d-d714-486f-a022-41da3bcf2095.png)
After closing
![Screenshot_20211120_022820](https://user-images.githubusercontent.com/70179464/142692703-e75c706b-0d33-418d-8692-db47c2f92cc2.png)

### Steps to reproduce the behaviour

1. Start the game CA-CYBER.exe
2. Open options menu by pressing o
3. The display will be garbled.
4. Close the menu by pressing Esc key.
5. The top portion of the game area is having display artifcats.

Same happens when you open Jump Screen menu by pressing j.

### Emulator log

```text
Early LOG Init complete
DOSBox-X's working directory: /home/vignesh
Logging init: beginning logging proper. This is the end of the early init logging
Logging: No logfile was given. All further logging will be discarded.
DOSBox-X version 0.83.20 (Linux SDL2)
Host keyboard layout is now us (US English)
Mapper keyboard layout is now us (US English)
SDL2 reports desktop display mode 1366 x 768
The default output for the video system: opengl
Configured windowposition: 
SDL:Current window pixel format: SDL_PIXELFORMAT_RGB888
SDL: You are running in 24 bpp mode, this will slow down things!
X11 main window is 640 x 400 maximized=0
X11 extension XRANDR is available
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(363,213) size=(640,400) match=(683,413)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
ISA BCLK: 8333333.333Hz (25000000/3)
monopal: green, 
Active save slot: 1 [Empty]
USING AVI+ZMBV
Max 3670016 sz 16384
Final 16384
SDLNet_TCP_Open: Couldn't connect to remote host
TiMidity: can't open control connection (host=127.0.0.1, port=7777)
MIDI:fluidsynth: Loaded SoundFont: /usr/share/soundfonts/default.sf2
MIDI:Opened device:fluidsynth
Pentium CMPXCHG8B emulation is enabled
VOODOO LFB now at d0000000
Serial1: BASE 3f8h
Serial2: BASE 2f8h
Parallel1: BASE 378h
MPU-401 Registering I/O ports as if IBM PC MPU-401 at base 330h
GetDesktopResolution reading X11 desktop resolution
Root window (ID 309) is 1366 x 768
X11 main window is 640 x 400 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(363,213) size=(640,400) match=(683,413)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
Allocated APM BIOS pm entry point at f000:ce40
Writing code to fce40
X11 main window is 640 x 400 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(363,213) size=(640,400) match=(683,413)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
ISA Plug & Play BIOS enabled
VGA ROM BIOS init callback
pixratio 1.000, dw false, dh false
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
menuScale=1
X11 main window is 640 x 497 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(363,213) size=(640,497) match=(683,461)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
font texture id=2 will make 128 x 256
X11 main window is 640 x 497 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(363,135) size=(640,497) match=(683,383)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
   2899550 ERROR BIOS:Keyboard layout file auto not found
   2899550 ERROR BIOS:Keyboard layout file auto not found
XMS: 50 handles allocated for use by the DOS environment
EMS page frame at 0xe000-0xefff
COMMAND.COM env size:             720 bytes
COMMAND.COM environment block:    0x0701 sz=0x002d
COMMAND.COM main body (PSP):      0x072f sz=0x009a
COMMAND.COM stack:                0x0749
pixratio 1.350, dw false, dh false
Aspect ratio: 720 x 540  xToY=1.333 yToX=0.750
menuScale=1
X11 main window is 720 x 417 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(363,135) size=(720,417) match=(723,343)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
font texture id=2 will make 128 x 256
X11 main window is 720 x 417 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(323,175) size=(720,417) match=(683,383)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
pixratio 1.000, dw false, dh false
Aspect ratio: 640 x 480  xToY=1.333 yToX=0.750
menuScale=1
X11 main window is 640 x 497 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(323,175) size=(640,497) match=(643,423)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
font texture id=2 will make 128 x 256
X11 main window is 640 x 497 maximized=0
XRandR CRTC 0: pos=(0,0) size=(1366,768) outputs=1
Our window lies on this CRTC display (window pos=(363,135) size=(640,497) match=(683,383)).
  Goes to output 0: name='LVDS1' size_mm=(340 x 190)
Screen report: Method 'XRandR' (1366.000 x 768.000 pixels) at (0.000 x 0.000) (340.000 x 190.000 mm) (13.386 x 7.480 in) (102.048 x 102.669 DPI)
```

**Comment by grapeli** [comment] 2021-11-19 23:10
Under the much older version dosbox-x 0.83.5 works fine. Looks like regression.

**Comment by grapeli** [comment] 2021-11-20 00:50
The graphics issues in this game occurred after these changes to the code.
https://github.com/joncampbell123/dosbox-x/pull/2576

**Comment by Wengier** [comment] 2021-11-20 06:09
It is hopefully fixed in the latest code. Please check out the updated Windows builds:

* SDL1: [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)
* SDL2: [dosbox-x-sdl2-update.zip](http://cndos.fam.cx/dosware/dosbox-x-sdl2-update.zip)

**Comment by viki-t-s** [comment] 2021-11-20 09:43
Tested out the sdl2 build. Confirming issue is resolved now. Thanks!

**Closed** 2021-11-20 11:46 UTC
Labels: bug, topic: video, DOS gaming
