### ISSUE TITLE
dosbox-x-vsbuild-win32-20221226190454.zip can't run on windows xp

### ISSUE THREAD

**Issue by leoxxx** [joncampbell123/dosbox-x#3926] opened 2023-01-10 03:57 UTC
### Describe the bug

dosbox-x-vsbuild-win32-20221226190454.zip can't run on windows xp

### Steps to reproduce the behaviour

Click the exe, then can't run.

### What operating system(s) this bug have occurred on?

windows xp

### What version(s) of DOSBox-X have this bug?

vsbuild-win32-20221226190454

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Torinde** [comment] 2023-01-10 05:42
I don't know if it matters, but you may try both SDL1 and SDL2...

**Comment by leoxxx** [comment] 2023-01-10 06:16
Try them, all can't run.

**Comment by maron2000** [comment] 2023-01-10 12:12
This is actually not a bug.
Visual Studio (2017 and after) and MinGW dropped support for Windows XP.
You can still run Visual Studio builds by applying a patch to the header.
Download the patcher and copy it to where your DOSBox-X executable is, and run it.
Remember that XP support is **obsolete and/or not recommended** and the patcher does NOT guarantee that further DOSBox-X releases can be run on XP. 

```PatchPE dosbox-x.exe```

https://github.com/joncampbell123/dosbox-x/blob/master/contrib/windows/installer/PatchPE.exe

**Comment by leoxxx** [comment] 2023-01-10 15:00
2022.08 can run on windows xp. I think you can save this version.

**Comment by BridgeHeadland** [comment] 2023-01-10 15:36
Do the patcher make dosbox-x-vsbuild-win64-20230109003356.zip\bin\x64\Release SDL2 to be run on XP? It's the only version I have right now.

**Comment by BridgeHeadland** [comment] 2023-01-10 15:38
Do the patch make the current dosbox-x-vsbuild-win32-20230110063138 to be run on XP?

**Comment by maron2000** [comment] 2023-01-10 22:08
@Torinde Before updating the documentation, did the patch work?

**Comment by Torinde** [comment] 2023-01-11 06:36
I don't have WinXP at hand now - maybe @leoxxx can test it?

**Comment by maron2000** [comment] 2023-01-11 08:13
The patch didn't work on 32-bit XP, however, 2022.09 (**not** 08) version which is possibly built with VS2017 worked.
So maybe it is due to building on VS2019/2022 since PR #3744 dated 15th Sep which broke compatibility with VS2017.
I already put a PR (#3922) to make it able to be built with VS2017, so after it is merged, we can try the latest code built on VS2017.

**Comment by maron2000** [comment] 2023-01-17 15:26
So my PR was merged, and I built the code with VS2017 and seems to work on Windows XP again.
I think it is better to make a CI workflow specific to build a executable dedicated for XP, so that we can use the latest tools for modern Windows.
Anyway, you can try a copy from my repository for the time being and see if there are any flaws.
https://github.com/maron2000/dosbox-x-1/suites/10417362911/artifacts/514838986

![xp_buildtest](https://user-images.githubusercontent.com/68574602/212938969-f4a7a366-df95-45dd-8864-eb9b8b2eb8c6.png)

**Comment by leoxxx** [comment] 2023-01-18 03:20
Test O.K.
![2023-01-18_111529](https://user-images.githubusercontent.com/5364709/213075519-9671c6c1-6378-4001-b397-03d748c00712.png)

**Comment by Torinde** [comment] 2023-01-18 06:06
Workflow for automatic building for WinXP portable executables (win32, win32-low end, win64) would be of course good to add.
What about also:
- automatic building of WinXP installers (or actually bundling those as part of the current win32 and win64 installers?) - dosbox-x.com homepage link is defined as "32-bit Setup (XP+)" @JoeBroesele
- automatic building of Windows arm32, arm64 installers (or bundling those in the current win32/win64 installers unless they are renamed x86/x64) - dosbox-x.com homepage links are defined generically as "32-bit Setup" and "64-bit Setup" (not x86 / x64) @JoeBroesele
- automatic building of macOS high sierra portable (last seen [2022.09.0](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.84.3)). If it's decided that this won't be build with every release, then INSTALL.md should link to the latest one. @Dobby233Liu
- automatic building of LOADLIN portable (last seen [0.83.25 2022-05-01](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.83.25)). If it's decided that this won't be build with every release, then INSTALL.md should link to the latest one.
- automatic building of macOS arm64 portable - it's present at [2022.12.26](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2022.12.26), but not in [nightly builds/actions artifacts](https://github.com/joncampbell123/dosbox-x/actions/runs/3937396834)
- automatic adding of Linux portable(s) to the Releases assets list? Currently the dosbox-x.com homepage and INSTALL.md are linking to Flatpack and other external repositories, while [2022.12.26](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2022.12.26) has nothing for Linux (only source packages). At the same time there is a [nightly builds/actions artifact](https://github.com/joncampbell123/dosbox-x/actions/runs/3937396827) Linux-x86-64. But not Linux x86-32. Is all of that OK for Linux users?

**Comment by JoeBroesele** [comment] 2023-01-18 20:34
> * automatic building of WinXP installers (or actually bundling those as part of the current win32 and win64 installers?) - dosbox-x.com homepage link is defined as "32-bit Setup (XP+)" @JoeBroesele
The installers *do* run under Windows XP. I tried the 32-bit version, but couldn't test the 64-bit one.

> * automatic building of Windows arm32, arm64 installers (or bundling those in the current win32/win64 installers unless they are renamed x86/x64) - dosbox-x.com homepage links are defined generically as "32-bit Setup" and "64-bit Setup" (not x86 / x64) @JoeBroesele
Looking at the script the builds the installers, it looks like the ARM binaries get also packed into the installers. I would be great if somebody with Windows on ARM could test that.

**Comment by Dobby233Liu** [comment] 2023-01-19 14:06
> * automatic building of macOS high sierra portable (last seen [2022.09.0](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v0.84.3)). If it's decided that this won't be build with every release, then INSTALL.md should link to the latest one. @Dobby233Liu

I don't know how to build this one, just hid it from the website because I didn't see it in the release. Would be nice if there's instructions left in the repo, I am going to check

**Closed** 2023-01-20 06:30 UTC
Labels: bug

**Comment by Torinde** [comment] 2023-01-20 20:24
ARM32 (both SDL1 and SDL2) appear to be in the win32 installer, yes. I don't have ARM, so I can't run them, but the files appear if I select "include all versions" during setup.
