### ISSUE TITLE
VESA 1366x768

### ISSUE THREAD

**Issue by KormaX-of-DOS** [joncampbell123/dosbox-x#1256] opened 2019-09-17 16:37 UTC
Hello!

I see that there are many many VESA modes supported in your program, far more than the main line of DOSBox supports. However, could you pleas add the 1366x768 vesamodes (381-383)? I suffer from the fact that I can not take a real screenshot of my DOS programs in these modes even though there are some supporting it. If your DOSBox-X supported these modes I could make screenshots of these programs. Also there is a screen-captire utility for DOS called VideoThief that can save the VESA frame into a file when I use a 16:9 GUI app on DOS, so if you did this favor for me, I could just load your DOSBox-X with HX (thank you for maintaining a dedicated DOS version), display the VESA frame in DOSBox-X and save its screenshot as a real image file.

Thank you!

**Comment by emendelson** [comment] 2019-09-17 16:55
Which video card that worked with DOS programs supported those video modes? They don't seem to be listed anywhere that I can find, but maybe I haven't looked hard enough. Is there any documentation out there for them?

**Comment by joncampbell123** [comment] 2019-09-17 16:56
This is a duplicate of https://github.com/joncampbell123/dosbox-x/issues/1187

Please read and post there.

**Closed by joncampbell123** 2019-09-17 16:56 UTC
