### ISSUE TITLE
Free Pascal compiler page fault

### ISSUE THREAD

**Issue by Andrew-D0** [joncampbell123/dosbox-x#2282] opened 2021-02-17 20:52 UTC
The Free Pascal compiler seems to cause DOSBox-X to crash:

>LOG: 189875082 PAGING:Recursive PageFault for 8af000 used=0
>terminate called after throwing an instance of 'GuestPageFaultException'
>what(): Guest page fault exception

This is using Free Pascal 3.2.0 DOS (GO32v2).

To reproduce:
Download the 4 mandatory files from here and put them somewhere DOSBox-X can access:
https://www.freepascal.org/down/i386/go32v2-hungary.html
In DOSBox-X, run INSTALL.EXE
Install to C:\PP
Run C:\PP\BIN\GO32V2\FPC.EXE

Tested with DOSBox-X 0.83.10 on Linux and Windows 10.

I found Free Pascal when I was trying to compile a program for DOS to call Int 21 for a previous bug report. I don't actually use Pascal but as I found the problem I thought I should report it.

**Comment by Wengier** [comment] 2021-02-17 23:28
Thanks for reporting. I think it is an issue with the recent "use dynamic core with paging on = auto" option (occuring on 64-bit builds), which I will fix soon. Meanwhile, I think you can get it work either by setting "core=normal" or using 32-bit Windows binaries.

**Comment by Wengier** [comment] 2021-02-18 02:04
@Andrew-D0 The issue is hopefully fixed in #2283.

**Comment by Andrew-D0** [comment] 2021-02-18 23:21
I have tested and it works here!

**Comment by xcelsiour** [comment] 2021-02-22 14:13
I was just about to make an issue about this. How can I see the error on windows because it doesn't show it on command prompt.

**Comment by Andrew-D0** [comment] 2021-02-22 14:58
`dosbox-x -debug -console` should do it. `dosbox-x -helpdebug` shows other possibly useful commands.
The console window might disappear before you get a chance to read it though.
I copied the error message from running in Linux because it is generally easier.

**Closed** 2021-03-03 16:06 UTC
Labels: DOS applications, bug, topic: CPU
