### ISSUE TITLE
CGA Palette values differ from expected values

### ISSUE THREAD

**Issue by BridgeHeadland** [joncampbell123/dosbox-x#3804] opened 2022-11-01 18:46 UTC
### Question

I know this is the HEX code for the entire CGA palette:
#000000
#0000AA
#00AA00
#00AAAA
#AA0000
#AA00AA
#AA5500
#AAAAAA
#555555
#5555FF
#55FF55
#55FFFF
#FF5555
#FF55FF
#FFFF55
#FFFFFF
But when I printscreen an image of an CGA game, paste it into Paint, retrieve all the 16 colors, and calculate where the RGB code is in the HEX code, I get the following result:
#000000
#0000A8
#00A800
#00A8A8
#A80000
#A800A8
#A85400
#A8A8A8
#545454
#5454FC
#54FC54
#54FCFC
#FC5454
#FC54FC
#FCFC54
#FCFCFC
What does it come from? Can someone explain?

### Have you checked that no similar question(s) exist?

- [X] I have searched and didn't find any similar question.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Jkapp76** [comment] 2022-11-01 20:26
Is it possible windows darkened your monitor in the evening with it's night-light feature, and you made the screen shots in the evening?

The colors look slightly darker to me, judging by the codes.

**Comment by BridgeHeadland** [comment] 2022-11-01 20:54
@jkapp76 If you think that it is only the monitor that makes the EGA colors look so different, then it does not mean that the actual HEX code in the hardware itself is different, as the color difference lies in the monitor.

**Comment by NebularNerd** [comment] 2022-11-02 14:04
Do you get the same issue when you use the inbuilt screen capture from DosBox-X Capture->Take Screenshot or `F11+P`?

**Comment by BridgeHeadland** [comment] 2022-11-02 19:13
@NebularNerd I don't know. Where is the image after I press F11+P? I don't know where I find it.

**Comment by NebularNerd** [comment] 2022-11-02 20:08
> @NebularNerd I don't know. Where is the image after I press F11+P? I don't know where I find it.

Typically this will be in the capture directory under your dosbox directory unless you have set another path in the .conf file. e.g.:
`C:\DOSBOX\CAPTURE`

**Comment by BridgeHeadland** [comment] 2022-11-02 22:13
@NebularNerd I pressed F11+P on Duke Nukem (the 1991 game), checked the PNG file, the issue/result is the same as when I press the Print Screen button.

**Comment by msikma** [comment] 2022-11-03 01:06
It might be that a monitor colorspace was applied to the image when you pressed printscreen. MS Paint is a very simple program so it's undoubtedly not storing colorspace information in images. For example, I believe Chrome/Firefox treat images without colorspace information as though they're sRGB—images without embedded colorspace information are unstable in how they appear on screen.

**Comment by BridgeHeadland** [comment] 2022-11-03 05:27
@msikma I am a very simple person, so it is possible that I am misunderstanding you right now.
I now answer based on how I understand your comment: in the mounted folder, where I have the games, I also have something called PictView, a program for DOS, where you can open pictures, and when I open a picture from an EGA game , with the first-mentioned HEX codes, Print-Screen it, possibly press F11+P, paste into Paint, and retrieve the colors, to see the RGB codes, the result is exactly like in the original image of the EGA game, with the the first mentioned HEX code colors. When I Print-Screener, or press F11+P during a proper EGA DOS game, running in DOSBox, paste into Paint, and retrieve the colors, the result is the second and last mentioned HEX code colors, so I therefore believe that EGA -the games actually run with the last mentioned RGB/HEX code colors for real, at least on my PC. As I said, I'm a simple person, so I don't understand what Firefox and Chrome have to do with this, but maybe you can explain it to me?

**Comment by msikma** [comment] 2022-11-04 06:14
Well, it's hard to comment on the PictView thing, because I'm not sure how that program works.

These days we have color profiles which contain information about what colors your monitor can display and can be used to finetune your monitor's exact color display. This is good because it means if I make an image on my monitor, I can be sure it'll look the exact same on your monitor.

In the old days we did not have this, and as a result things could look *very* different from monitor to monitor. Some would be a bit more blue, some a bit more yellow, some would have much lighter grays, and so on.

When you make a screenshot from your monitor, the only way this screenshot will look correctly is if the active color profile is included in the data. That's probably not happening when you copy the screen data into MS Paint. So that could cause colors to look off.

Either way, you should just use the DOSBox built in screenshot feature instead of copypasting printscreens into MS Paint, because the screenshot feature has the color profile stuff all handled perfectly.

**Comment by NebularNerd** [comment] 2022-11-04 13:24
To help this move along I have added some screenshots from CheckIt Pro's EGA Palette test, For argument's sake on DosBox-X I tried with both `machine=s3` and `machine=ega`. You can test these by downloading the images and using a color picker in your favourite paint package or something like the Powertoys Color Picker.

I'm not a coding expert but it seems that all the AA values are shifted 3 hex digits to A8, could it be something in [vga.cpp](https://github.com/joncampbell123/dosbox-x/blob/master/src/hardware/vga_attr.cpp#L30) slight offsetting the correct values?

For others to test I extracted the video test from CheckIt Pro, use `CKVID 0` to run the test suite: [CKPRO.zip](https://github.com/joncampbell123/dosbox-x/files/9938303/CKPRO.zip)

DosBox-X internal capture (png), AA values shifted to A8:
![ckvid_001](https://user-images.githubusercontent.com/8470449/199972173-eef64315-8bc0-4a84-b571-6eaaa21f6e33.png)

Win 10 Snip & Sketch Tool (jpg), AA values shifted to A8:
![Screenshot 2022-11-04 120809](https://user-images.githubusercontent.com/8470449/199972254-c179677c-1cd2-4eb0-8095-4e39ec9fc937.jpg)

DosBox-X internal capture (png) viewed in Chrome (Powertoys colour picker shows A8 value), then Win 10 Snip & Sketch Tool (jpg), AA values shifted to A8:
![Screenshot 2022-11-04 132230](https://user-images.githubusercontent.com/8470449/199982864-724cdc65-7f13-418d-969b-f55199d33ea1.jpg)


[Virtual Console DosBox SVN](https://virtualconsoles.com/online-emulators/dos/) online emulator grabbed with Win 10 Snip & Sketch Tool (jpg), values not shifted:
![Screenshot 2022-11-04 123145](https://user-images.githubusercontent.com/8470449/199975086-2e20d6b0-32c0-4ed9-bd61-7518431f1a76.jpg)

[Dosify me!](https://caiiiycuk.github.io/dosify/) online emulator grabbed with Win 10 Snip & Sketch Tool (jpg), values not shifted (Powertoys colour picker shows correct value):
![image](https://user-images.githubusercontent.com/8470449/199979121-dc416d24-8f1d-4657-819c-3d490fbf1d8a.png)

EGA Colour table from [here](https://moddingwiki.shikadi.net/wiki/File:EGA_Table_Hex.svg):
![EGA_Table_Hex](https://user-images.githubusercontent.com/8470449/199980379-bf11e0dd-dd7e-4667-a555-7cba25c4cd2f.svg)

**Comment by BridgeHeadland** [comment] 2022-11-04 17:34
@msikma You can download it by clicking http://www.pictview.com/pictview.zip -. When I opened an image from an EGA game, with the expected color codes, in PictView, with true color, the image was displayed with the expected color codes, the AA value, but when I open the same image, only with VGA colors, I get the A8 value. It appears that 15 out of 16 colors from the AA value do not belong to the VGA palette, as do 15 out of 16 colors from the A8 value, at least not the VGA palette with 4096 out of 65536 VGA colors. If a DOSBox type runs EGA games with colors from the A8 value, then it may be because the DOSBox thinks the EGA, TGA (Tandy), CGA and MGA (Monochrome) software are VGA software of any reason. I have also been told that the video card in the hardware determines which AX value the pre-VGA software shows in DOSBox-X.

**Comment by NebularNerd** [comment] 2022-11-04 18:26
Just tried pictview with my screengrab from Dosify Me above and it gives the wrong values, can you supply the EGA image you are trying in Pictview so we have a common base.

Loading one of the discolored screen grabs from above results in the same A* values.

Dosify = From the screen grab above, Pictview = Same file viewed inside DosBox
The image is quite large so it can only load in a portion at a time (you'll want to click CPU->Turbo to load it) but it does the job. the AA value is now shown as A8.
![Screenshot 2022-11-04 180012](https://user-images.githubusercontent.com/8470449/200044358-596d0e5c-0879-4e53-a1c7-d742dfd50ae6.jpg)

I've attached the .zip here as some recent browser updates no longer allow for non https connections.
[pictview.zip](https://github.com/joncampbell123/dosbox-x/files/9940930/pictview.zip)

To test further I have made a 4 colour indexed .pcx file [egatest.zip](https://github.com/joncampbell123/dosbox-x/files/9941072/egatest.zip) to remove any colour conversion issues. Again colours are wrong regardless of capture method. `machine=ega` just to make sure.
![image](https://user-images.githubusercontent.com/8470449/200047764-d212d834-9e46-4e04-8bae-838cab7b9409.png)

Displays ok in Dosify Me
![image](https://user-images.githubusercontent.com/8470449/200048118-7fa741f8-9d8c-43e1-a05b-a02e787d53c7.png)

**Comment by BridgeHeadland** [comment] 2022-11-04 19:01
![image](https://user-images.githubusercontent.com/85258509/200052916-bc77f610-424f-44b7-a7f9-853ae805c593.png)
![image](https://user-images.githubusercontent.com/85258509/200054438-104daae7-f87d-4063-8e45-5499fc16e0df.png)
I have created a palette image with all 64 EGA colors and compared the result from both the true color result (top) and the 4096 color VGA result (bottom). It appears that only the 16 regular EGA colors, which are essentially all CGA colors, change from AA value to A8 value, while the other 48 colors remain unchanged. Not only that, but the 555555/545454 color appears as 505450, for some strange reason. At least that's how it is on my PC with DOSBox-X.
It's actually the CGA palette that is changed, not the EGA palette.

**Comment by NebularNerd** [comment] 2022-11-05 10:09
Testing with [CGACAL.ZIP](https://github.com/joncampbell123/dosbox-x/files/9943506/CGACAL.ZIP) from [oldskool.org](http://www.oldskool.org/pc/cgacal) shows CGA colours have incorrect values (the program authors emulator must be off as well). Tested with `machine=cga`

From DosBox, excuse hq2x scaler makes no difference to colour reproduction (Use `y` for real hardware when asked):
![image](https://user-images.githubusercontent.com/8470449/200114128-1ee9098c-0a2b-47a1-ad1d-1e6e8027f01a.png)

From site image:
![image](https://user-images.githubusercontent.com/8470449/200114290-1a7f56f0-de3d-476d-82b9-5df464f7eb04.png)

Dosify Me!  shows correct colours (Use `n` for not real hardware when asked):
![image](https://user-images.githubusercontent.com/8470449/200114468-5b8d9a3d-49d6-4181-879b-97bfa51b607d.png)

CGA Palette from [Wikipedia](https://en.wikipedia.org/wiki/Color_Graphics_Adapter#Color_palette):
![image](https://user-images.githubusercontent.com/8470449/200114544-4172cd90-c45b-497f-afd1-28dbacd9636a.png)

**Comment by maron2000** [comment] 2022-11-05 12:24
I put a PR (#3810) to fix this issue. Please try with various video modes.

![palette](https://user-images.githubusercontent.com/68574602/200119676-fe0f43bb-9b16-402e-aee2-283696c7f1c1.png)

**Comment by NebularNerd** [comment] 2022-11-05 12:30
Will happily test once the PR goes through if I don't get a chance to compile my own before.

**Comment by maron2000** [comment] 2022-11-05 13:18
The test builds have finished successfully, so you can download the "Aritifacts" for respective platforms from the link below.
https://github.com/joncampbell123/dosbox-x/actions

**Comment by NebularNerd** [comment] 2022-11-05 14:24
@maron2000 That did the trick, colours are now spot on to what they should be.
@BridgeHeadland I think you'll be able to close this and maybe your older #3668 ticket.

CGACAL under `machine=cga`:
![image](https://user-images.githubusercontent.com/8470449/200124275-900891f7-46e2-4605-81e3-f1a38d9e14b1.png)

CKVID under VGA:
![image](https://user-images.githubusercontent.com/8470449/200124350-ad52b989-f3bb-4fc8-b174-7fa5be8a1e31.png)

My awesome test picture under PICTVIEW:
![image](https://user-images.githubusercontent.com/8470449/200124418-896f229d-4034-4af3-aa2b-788f62d6d9e7.png)

**Comment by BridgeHeadland** [comment] 2022-11-05 15:16
@maron2000 I tried out Fix 6-bit VGA to 8-bit RGB palette conversion, the colors are as they should be, but what happened to the opengl outputs?

**Comment by NebularNerd** [comment] 2022-11-05 15:28
> @maron2000 I tried out Fix 6-bit VGA to 8-bit RGB palette conversion, the colors are as they should be, but what happened to the opengl outputs?

OpenGL working ok for me with 64bit VisualStudio (VS) SDL2:

![image](https://user-images.githubusercontent.com/8470449/200127256-5dfe64c1-d8d8-455f-97be-2cc1e307ced6.png)

3DFX game running in OpenGL:

![image](https://user-images.githubusercontent.com/8470449/200127412-32426479-1bc8-4a88-a1c7-02c57ebe231f.png)

**Comment by BridgeHeadland** [comment] 2022-11-05 16:28
@NebularNerd I downloaded the MinGW version, without thinking. Now I have downloaded the Visual Studio builds version and OpenGL works for me too.

**Closed** 2022-11-05 16:29 UTC
Labels: question

**Comment by maron2000** [comment] 2022-11-06 12:04
There is a bug of build script for MinGW which always disables OpenGL. (It is also disabled before applying my PR)
I tweaked some code to force enabling OpenGL, and seems that the color palette issue is fixed as well.
So fortunately, it will be fixed in the next release.

![opengl](https://user-images.githubusercontent.com/68574602/200169038-3434790c-46dd-42ee-97bb-1d6025da1bb5.png)
