### ISSUE TITLE
Colors wrong, text invisible during windows 98 setup

### ISSUE THREAD

**Issue by RoboMWM** [joncampbell123/dosbox-x#4577] opened 2023-11-02 21:22 UTC
### Describe the bug

I'm new to running DosBox and DosBox-X, and I encounter this bug with https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2023.10.06

I'm having issues installing windows 98 (first edition) in dosbox-x. It gets past the first setup, but upon booting from harddisk and starting the second phase of the setup, the text is invisible and the cursor is very light. I've tried my own disc, as well as different isos, and second edition, sdl1 and 2, different video modes, and they all do the same thing. Things are clickable and I can input text, so it seems to be a visual-only issue. I have also tried a 2GB disk and mingw builds, still same results.

![image](https://github.com/joncampbell123/dosbox-x/assets/4625696/8329d386-49ad-4c71-9e5a-f72bc05ffa9c)
![image](https://github.com/joncampbell123/dosbox-x/assets/4625696/dff3f82d-4809-4e8e-8ba3-2a977a3293cd)

I finally tried downgrading to the prior release https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2023.09.01 and I now have no visual issues at this point; as such, it appears this bug does not appear in this prior version.

![image](https://github.com/joncampbell123/dosbox-x/assets/4625696/978bb70b-bfae-4cf7-8aab-57c0dc0a54e4)

### Steps to reproduce the behaviour

I've been following this guide to install Windows 98: https://github.com/joncampbell123/dosbox-x/wiki/Guide:Installing-Windows-98

### What operating system(s) this bug have occurred on?

Windows 11 Pro 22H2

### What version(s) of DOSBox-X have this bug?

dosbox-x-v2023.10.06

### Used configuration

```ini
[sdl]
autolock=true

[dosbox]
title=Windows 98
memsize=128

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
```

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maxpat78** [comment] 2023-11-03 06:33
I've encountered the same issue recently, during Win95 setup.
Try to set `machine=svga_s3` in your config, and, eventually, also

```
[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0
```
Perhaps Win 9x does not recognize the right video card model.

**Comment by mattcaron** [comment] 2023-11-09 00:25
I can confirm that this is not an issue for me when 77b9b7a30ed186ae0023f3beadd704184cb8d4d8 is built on Ubuntu 22.04.

**Comment by ianm111** [comment] 2023-12-09 08:20
I have the OPs problem of no text and faint cursor using Win 11 and the October release. Any solution other than an earlier release?

**Comment by maron2000** [comment] 2023-12-09 09:43
This issue found in the October release is fixed and you can try the nightly builds.
Not sure your issue is same as this one but maybe worth trying.

**Comment by ianm111** [comment] 2023-12-09 16:08
Thanks maron2000, an update using the windows installer sorted it. Unfortunately the win98 installation fails later at the System Config stage with ‘regsvr32 caused a stack fault’ and ‘unable to install java packages…not enough storage’ so I am not much further forward.

**Comment by joncampbell123** [comment] 2023-12-10 08:25
Is it possible that the VGA palette issue behind the "no text" Windows 98 problem might be some subtle data corruption within the guest if run in certain builds of DOSBox-X, especially the automated builds?

**Comment by maron2000** [comment] 2023-12-10 11:31
There was a segmentation fault bug in the October release, but I already fixed it.
The whole problem of color flaws and segmentation fault was due to a flaw in preserving palette info between TTF and nonTTF modes so I currently believe it is not corrupting memory in emulation.

**Comment by jkirwan** [comment] 2023-12-11 05:17
I just experienced this problem (or one very similar to it.) My installer is called "dosbox-x-winXP-2023.10.06-setup.exe" that was downloaded on the 9th, this month.

The following file hashes for the above-mentioned installer are handy:

```
CRC32: BB819FD0
MD5: DFACFE023E9DA1678EA8459241059060
SHA-1: E170AC1AB882965843EB5FE8CEB28C6D4BCA892C
```

After following instructions for installation from the win98se OEM ISO (which appeared to work fine and I was able to read text just fine then), I added the indicated lines under the [autoexec] section of win98.conf, saved, closed the current rebooted dosbox-x window, and then re-started from the command line. This is what I see:

![image](https://github.com/joncampbell123/dosbox-x/assets/16784891/d0847689-12cb-4273-a200-dedc47750014)

It's the same whether or not I use core=normal or core=dynamic_x86. (Tried both.)

I'm holding short of going further, preferring to just improperly shut down Win98SE for now.

I'm running Windows 10 on an i7-5820K CPU @ 3.30GHz, 6 Core(s), 12 Logical Processor(s) on an ASUS X99-A motherboard. The BIOS dates back to 2016 but is running UEFI with virtualization enabled and Hyper-V operational. (I also run WSL2 with UBUNTU.) 32GB of RAM.

I do have dual screens on an NVIDIA GeForce GTX 760 board.

My win98.conf follows:

```
[sdl]
autolock=true

[dosbox]
title=Windows 98
memsize=512

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[dos]
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[autoexec]
IMGMOUNT C cdrive.img
IMGMOUNT D Win98SE.iso
BOOT C:
```

This is my first experience with DOSBOX-X. Just wanting to try getting a few CD ROMs from Living Books running for my daughter.

Thanks for any help or thoughts to try.

**Comment by jkirwan** [comment] 2023-12-11 09:03
I am glad to hear it worked for you. (And thanks so much for your time.)

But I just used the build I mentioned and you have my results. And that build wasn't all that long ago.

Regardless, I will retry using the latest when I get a moment about 12 hours from now. I'll report back then.

**Comment by jkirwan** [comment] 2023-12-12 02:46
Yeah. But I was foolish enough to believe [this link saying it is the latest](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2023.10.06). I got pointed there from somewhere and when I click on the "latest" button there it just takes me to the same place. I'll stop being so gullible. While I wouldn't mind a direct link from you, it probably will do me some good to go find it, myself. I need the education.

**Comment by jkirwan** [comment] 2023-12-12 03:48
Thanks. I definitely remember [this page 'issues/3822'](https://github.com/joncampbell123/dosbox-x/issues/3822) and reading there. But I also chose to go back and grab the "release" instead.

I'm learning.

At some point I may 'git clone' the source. I owe a debt now and I'm curious to see if there's a way I can pay some back.

Just a cartoon of my experiences: I learned c working on the Unix v6 kernel in 1978. Rewrote a time-sharing O/S to support time-shared assembly (also wrote the symbolic assembler and linker) on the HP 2000F system in 1975. Decades of commercial assembly coding for the x86 and IBM PC hardware (motherboard, 8053/8054 PIT, CGA, EGA, protected mode, as well as working at Intel on the BX chipset -- about half the silicon bugs were with the south bridge and its attempts to support ISA on PCI.) I also was involved with Phoenix while at Intel right at the point where 64-bit was being tested for first release.

But that's for later. I may be more work than I'm worth. So I need to review the code first. And if I don't think I can be of any use, then that's that and you have my best!

Is the SDL2 subdir for the OpenGL edition?

**Comment by maron2000** [comment] 2023-12-12 05:38
OpenGL is available on Windows build regardless of SDL1/SDL2 or VS/MinGW or 32/64-bit.

**Comment by jkirwan** [comment] 2023-12-12 06:01
Hmm. That leaves me wondering about the two folders: Release and Release SDL2. Doesn't matter. I used Release and did not use Release SDL2. And it's working fine.

Here are my results.

I took down dosbox-x-vsbuild-win64-20231211024513 and looked at the ./bin/x64/Release/dosbox-x.exe there, called up the properties tab and checked details. It reports itself as "Product Version 2023.10.06". But when I run it I find that ver /r reports:

![image](https://github.com/joncampbell123/dosbox-x/assets/16784891/36f8d694-9d37-45e3-9fdc-a815c7bfca3d)

So, I guess this is still the october 6 release, but definitely a later build. After going through the same process, things worked much better. Thanks.

However, after going through the process of setting things up the first time Win98 shuts down and I get this:

![image](https://github.com/joncampbell123/dosbox-x/assets/16784891/64cbb8b7-c33b-419d-9061-9d62ab8f8832)

And at this point the window will no longer capture my mouse, nor do any of the menus operate, and I cannot even move the window around on the desktop. It's flat dead. Literally. For 20 minutes. And not even the X at the upper right corner works. But it does show up on the task manager, which shows:

![image](https://github.com/joncampbell123/dosbox-x/assets/16784891/be31ec7a-8112-4a16-8ec6-5e997d520d72)

The window busies-out the mouse icon when I wander over anywhere on the entire window (including title bar.)

Killing the process and restarting windows does get it to follow through setting up PCI and so on until I do finally get to the Win98 desktop.

I then added a MOUNT to the AUTOEXEC section so that my CDROM would be visible under Win98SE. That didn't appear to work, though Windows booted fine and still showed the Windows WIN98SE.ISO file as drive D under windows. The mount command I used was:

MOUNT E G:\ -T CDROM

When I tried that on the DOS command line it worked fine. And if I took a directory, the directory was correct. But the software present there is a windows installer and so won't run properly on DOS. So Windows needs to see the CD-ROM for that to work.

The approach I took was to burn an ISO from the CD-ROM and use the following in the Win98SE.conf file:

```
[autoexec]
IMGMOUNT C cdrive.img
IMGMOUNT D Win98SE.iso
IMGMOUNT E DW_PICKY.ISO
BOOT C:
```

Oddly, while this worked fine for me, it set up DW_PICKY on D: and Win98SE on E:

Workable. But it means I don't understand. Nothing new there.

Thanks for the work you do here!

**Comment by maron2000** [comment] 2023-12-12 06:41
Drives mounted with `MOUNT` command will not work on a booted Win98, especially floppy/CD drives.
You need to `IMGMOUNT` the hard drive/CD/Floppy images (not folders) in advance.
For the hard drives, there is an option that DOSBox-X will make images for you before booting, but not effective for CD drives.
The above explanation is rough, so you may want to take a look at the Wiki guide for details.
https://github.com/joncampbell123/dosbox-x/wiki/Guide:Installing-Windows-98#host-folder-mounts

**Comment by jkirwan** [comment] 2023-12-12 06:57
I'm good. The process for me is to first burn ISOs. Place all ISOs in the DOSBOX-X root folder. Add the IMGMOUNT to the [autoexec], then run the simlink and off it goes.

In cases where it matters to me and where the installer doesn't actually transfer all the needed files to C:, I'll hand-transfer them and set up the simlinks that I need to run. I want everything on C: when I'm done. No ISO mounts, at all, if I can have my way. Just the cdrive's IMG and that's it. (I can't remember how many drive letters Win98SE permitted. But I do go back far enough to have memories of significant limitations for a while, only later to be allowed all the way to Z. (This means I remember that Win286 and Win386 were the first "usable" versions of Windows -- Win 1 and Win 2 weren't usable -- with Win 3 and later being usable.) I usually set up on DOS and just used the win.com program to fire up windows, which when exiting would just drop me right back into DOS again, where I could pick up from where I left off.

**Comment by jkirwan** [comment] 2023-12-12 07:41
Thanks for the wonderful help and thoughts. I am in your debt.

**Comment by jkirwan** [comment] 2023-12-12 15:24
I just found that setting up an ISO on D, E, F, and G doesn't work. I can only go to F, it seems. So I think there may be a drive letter limitation, not unlike what my vague memory recalls about things in early Windows editions.

**Comment by rderooy** [comment] 2023-12-12 16:08
Mapping of drives in DOSBox-X itself, and when you boot a guest OS may not be the same. With DOSBox-X you simply tell it the drive letter you want for an image or folder mount, but it does not work like that for a guest OS. The guest OS will do a harddisk partition enumeration which may differ from DOSBox-X. Then when it comes to CD-ROM or Network drives, you normally do have some control over the letters assigned (as long as they are available).

Drive and partition enumeration for a guest OS can be influenced by the location on the IDE bus. You can try to steer this somewhat with `imgmount` option `-ide 1m`, `-ide 1s`, `-ide 2m` or `-ide 2s`.

See also the wiki page on the subject of image files
https://dosbox-x.com/wiki/Guide%3AManaging-image-files-in-DOSBox%E2%80%90X

**Comment by jkirwan** [comment] 2023-12-12 17:43
Thanks, rderooy. I'll read the page to see if it helps me understand, better. The basic idea you talk about comes across to me well. I buy the idea that DOSBox-X and the guest OS can treat things differently, as they see fit. That just means I need to understand the details better, I suppose. And that may take some time for me. Meanwhile, I'm fine with the limitations I have at this moment.

Totally changing the subject... I have to say that the responses here have been wonderful. It's not like a dead fossil where no one says anything because no one is listening. There's something vibrant here. And I want to say that I'm very much impressed by the help I've been offered in such a short time. It was not earned or deserved. But it was given freely. And I appreciate it very much. It means a great deal. My thanks to all those who've given a moment of their life's blood to help me out. I cannot hope to repay it.

I will look at the idea of steering things. I need to refresh my memory about these details, though. (And I know that there is a lot of study material available from right-clicking on the title bar, too. I'm only just beginning to see how much is there for me!)

I'll look also at the -ide options and see if I can manage something useful there for my purposes. Thanks so much for that pointer. Whether or not it makes a difference, I'll learn something from the exploration.

Thanks to all here. I'm just very happy that the responses have been present and thoughtful. I am privileged and honored.

Best wishes, and much thanks!

**Comment by jkirwan** [comment] 2023-12-13 08:46
Final notes. I'm posting them here because it's not really a request for a new feature nor is it a bug. It's just a follow-up as I am settling down and focusing on completing some tasks ahead, now that I feel more comfortable that I can achieve what I needed when I started down this path. (Again, my thanks to all!)

I finally got more time. DOSBox-X has no apparent difficulty with **-ide 3m**, for example, but Win98SE as the guest OS won't look past the secondary slave.

That fact is supported here](https://cdn.preterhuman.net/texts/computing/microsoft/Windows_98_Installation_and_Configuration/ch10/ch10.htm), saying _"Another feature of Windows 98 is its support of a second IDE controller in your computer, if your computer can support it."_

So I now have a decent "user's" understanding of the guest OS limitations and how that plays with DOSBox-X.

[That same site](https://cdn.preterhuman.net/texts/computing/microsoft/Windows_98_Installation_and_Configuration/ch10/ch10.htm) also mentions support in Win98 for _"ATAPI CD-ROM changers that have up to seven CD-ROM slots"_ and _"Windows 98 includes 32-bit disk device drivers for several Small Computer System Interface (SCSI) controllers. Some of these controllers include Adaptec, Future Domain, Trantor, and UltraStor. The SCSI interface is a sub-bus to which you can connect up to seven peripherals. The SCSI supports up to eight units, but one of the units is used to connect the adapter card to the PC, leaving seven open units. You can **attach** hard drives, **CD-ROM drives**, scanners, and other devices to a SCSI adapter."_

A quick google did spot [this](https://github.com/joncampbell123/dosbox-x/issues/585) and [this](https://github.com/joncampbell123/dosbox-x/pull/3622) and [this](https://github.com/joncampbell123/dosbox-x/issues/656) (and more in terms of code differences.) So this may mean there is some support I'm not yet aware of. But a search of the Wiki in particular really doesn't come up with anything when looking for "ATAPI" or "SCSI" (except 1 soundblaster entry.) So what I might be looking for, a ATAPI CD-ROM changers or SCSI with CD-ROMs (either with up to 7 of them) may not be working yet. (Looking at the Issues section remains a bit technical and I'll need to spend some time going between comments and documentation I read in Issues and looking over source code at a later time, when I have a moment, to see if I can recognize something useful to try.

Regardless, for now, I'm in good enough shape and moving forward.

I owe much. My profound thanks.

**Comment by joncampbell123** [comment] 2023-12-13 09:17
Try setting the option for the tertiary IDE controller to make it a Plug and Play device and enable ISA PnP emulation. Windows 9x should detect it then.

**Comment by jkirwan** [comment] 2023-12-13 21:41
I did use MOUNT --help and IMGMOUNT --help and didn't see the option expressed in a way that was clear to me about making it PnP. I believe you are saying that if I correctly use such an option, this will enable ISA PnP. (Which, memory serving, as a bit of a disaster since hardware manufacturers were 'very limited' in their support, when it happened at all.) This may be my own limitations in associating some other term I should know (but don't.)

[I did also look over the Wiki with my limited skills at this point. I also skimmed some of the source code -- which I find far more readable that I'd expected (good) -- but there's quite a lot to get my bearings on at this point and it will take time to familiarize myself with it.]

I wouldn't mind a clue here.

**Comment by mattcaron** [comment] 2023-12-13 22:03
Why mount all the disks all the time?

Why not just either:

1. Switch them with the hotkey bind in the single drive.
2. Set up a common base config and then separate ancillary configs with whatever you want mounted mounted. (This is what I do, because I generally only do one thing and then turn it off. I use DBGL to keep it all straight) 

BTW, the discussions section is likely a more appropriate venue for these types of discussions.

https://github.com/joncampbell123/dosbox-x/discussions

**Comment by jkirwan** [comment] 2023-12-14 05:01
@mattcaron 

Yeah. (2) is what I'm doing now.

The problem I'm facing is the that entire list of Living Books software has gone through hostile takeovers and as a result different arrangements. Some of the (the early versions) install themselves by copying all the necessary files to C:. Those are easy. Others, after Broderbund took them over in a hostile takeover, would require the CD-ROM to be present and would only install a minimal icon or two on the C: drive. And there were still later purchases (Microsoft, in fact, had an executive visit and attempted their own takeover -- long stories, as I personally know the CEO at the time.) In any case, I have a host of issues to deal with.

One solution approach would be to take all the ISOs, many dozens of them, and set them up as separate ISO files that are always available when Win98 fires up. That doesn't seem an option right now. But it would solve the issues.

Another solution for me is to hand-edit things to copy the ISO files over to the cdrive (which I will make large enough using FAT32, if needed) and massage the various icons and start-up directories. I've done that in the past, but it is a bit of work to do and isn't the same work for each and every version. So I have to spend time customizing and adapting to specific details in each aberrant case.

The goal is to get about 30 applications all installed and running in a single system that I can use on a tablet.

My daughter is profoundly autistic (works about like a 5 yr old, though she's almost 40) and she depends on Living Books very much. I'm trying to set up a system that we can take in to the car during trips that will keep her happy and occupied. This is very important to me. And I cannot express how much I may yet owe to everyone who has contributed here.

I do maintain a full 80386+80387 and a 80486DX system here. But these are very old computers and they don't travel in the car well. Setting up simulation is something that will work very well for her. So that's the goal.

One approach is to just ISO everything and fire up DOSBox-X, associate all the ISO files so that in the cases where the programs require the CD-ROM present it is there for them, etc. But that would require ALL of the CD-ROMs to be available at all times. She cannot figure out how to make adjustments. She's technically just a 5 yr old! And when I'm driving I cannot fix that for her. I'm stuck.

It's possible that with 7 CD-ROMs in a CD changer and with another 7 CD-ROMs as SCSI, I might just barely get all the ISOs that require CD-ROMs always present with the standard installation working for her. Maybe. But right now I think the goal is for me to install what I can onto the C drive and for the other cases to do the required work to finesse their installation to my needs, copying files around as I see fit to get things working despite their installation defaults to the contrary. That will solve the problem for me.

And thanks for the CLUE. I didn't know where to attach myself for discussions. But I did start here because of the same display problem. I'll back away from this thread at this point. I think your advice is correct. But I have a path at this moment and I am very very happy right now. Everyone responding here has been simply wonderful and I owe a great deal for that privilege. Thanks.

**Comment by maron2000** [comment] 2023-12-14 10:32
Just to be sure, is `-ide 3m` option working?
If not, check ide tertiary is enabled (`true`) in the .conf file while the default is `false`.
```
[ide, tertiary]
enable                  = false
```

**Comment by jkirwan** [comment] 2023-12-14 21:26
Well, I also added these two "on a lark" (because it was being used for the primary and secondary and I was just guessing):

```
int13fakeio=true
int13fakev86io=true

```

and that caused Win98SE to find the new controller, install software for it, and see the added G drive.

Thanks!!

**Comment by jkirwan** [comment] 2023-12-17 10:07
I was so stupid. I had access to **_dosbox-x.reference.full.conf_** and never even looked at it!! Kicking myself. I'm getting sloppy.

Since I needed eye-glasses to notice that file after installation, it's my opinion that this file should be bolded, highlighted, and thrust into the face of any newcomer reading through the documentation of DOSBox-X. Not left to be accidentally discovered by idiots like me at some later time.

I sure needed the BIG SIGN pointing to **HERE**.

The information in that file helped me a lot!

All is done and working perfectly (except for one program -- not the fault of DOSBox-X at all, purely that I want to make it work as it was not intended to work and for exactly one crash that I cannot duplicate.) I consider this a perfect record.

Meanwhile, I've had more time to peruse some more of the code and... frankly... I'm impressed.

To top it off, fast and accurate responses here when I needed them and I was more ignorant. Could not be better.

Thanks and best wishes!

**Comment by joncampbell123** [comment] 2024-02-24 00:30
I recently corrected an issue with 10h and the attribute controller that may have caused the palette issue.

**Comment by joncampbell123** [comment] 2024-12-06 03:52
It sounds like the core issue has been resolved, so I will close this issue.

**Closed by joncampbell123** 2024-12-06 03:52 UTC
Labels: bug, topic: video, topic: Windows
