### ISSUE TITLE
Request: LPT4-9

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#1307] opened 2019-11-02 14:20 UTC
Now that it's possible to save printer output to a file depending on the LPT number, I hope it might be possible (in the future) to have LPT4 through LPT9 in addition to LPT1 through LPT3. 

I'm not sure when Windows started supporting LPT4 through LPT9, but if it was in the Windows 95 era, then it may be suitable to have these available in DOSBox-X. 

The vDos emulator has built-in support for LPT1 through LPT9, and it's very useful for getting data out of the emulator and into the host system. For example, in vDos you can copy to the host clipboard by "printing" to LPT9; and it would be nice to be able to do something similar in DOSBox-X by printing to an otherwise unused LPT port and have a background process copy the output to the host clipboard. I realize that I could probably do this now with LPT1 through LPT3, but I'm already using those ports for other purposes, so it would be good to be able to use other ports.

I've spent a few hours going through the code trying to support LTP4-9 and have made changes to bios.ccp, bios.h, dos_devices.cpp, flielpt.cpp, and parport.cpp, but I'm obviously flying blind, and don't know what I'm doing, -so nothing works to create a DOS device that I can write to. If someone who knows what they're doing gives this a try, I'll be grateful.

**Comment by joncampbell123** [comment] 2019-11-02 17:04
They won't be backed by the BIOS data area or BIOS interrupts since there's only room for LPT1-LPT3 but I think that can be added.

**Comment by joncampbell123** [comment] 2019-11-02 17:05
It was more common in Windows 95 and later with add on cards or XP and later with USB devices, but there's nothing to stop a DOS driver in CONFIG.SYS from adding one as well.

**Comment by emendelson** [comment] 2019-11-02 17:47
Thank you in advance for anything you can do. I'll look around for a DOS driver that may already exist. - I messed this up by trying to add BIOS data. After struggling with this for a while, I found a 400e address for LPT4 in your documentation (BDA - BIOS Data Area - PC Memory Map.txt), but by that time I had already been trying to add LPT4-9, not just 4 and messed things up too much to recover.

**Comment by Wengier** [comment] 2020-03-08 19:06
I have modified the DOSBox-X code to add a special DOS device called "CLIP", which will communicate bidirectionally with the Windows clipboard. The code is directly ported (with small changes) from vDosPlus and will work the same as LPT4 mentioned above. For example:

"DIR >CLIP" will redirect the directory listing to the clipboard.
"TYPE CLIP" will display the content of the clipboard.
"EDIT CLIP" will open the editor with the clipboard content.
"SORT <CLIP" will sort the clipboard content.

It is currently Windows only, so the new code is inside the "#if defined(WIN32)" block. The diff file is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-clip.diff

A pre-compiled Windows x64 build is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-clip.zip

Hope you find this helpful.

**Comment by joncampbell123** [comment] 2020-03-08 23:10
Applied.

**Comment by Wengier** [comment] 2020-03-09 02:00
Thanks! I have now add an config option named "dos clipboard device" under [dos] section of dosbox.conf, which allows users to customize the DOS device name for clipboard communications. The default device name is now _CLIP instead of CLIP to avoid potential name conflict with other files, but the users can change this name with the above config option as they prefer. For example, "dos clipboard device = LPT4" will use LPT4 as the DOS device for Windows clipboard communications. Tested to ensure the building is working. The new diff file for the latest commit 7535790 is now available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-7535790-patch.diff

**Comment by rderooy** [comment] 2020-03-09 06:55
Question, should -securemode not disable CLIP?

**Comment by joncampbell123** [comment] 2020-03-09 09:45
That would be a good idea, yes.

**Comment by sikthehedgehog** [comment] 2020-03-09 15:37
Maybe `CLIP$` as a default name would be more in line with DOS conventions? (I know there was `CLOCK$`, and also `.$$$` is a common extension for temporary files, etc.)

I suppose also important would be to be able to disable the file (rather than just rename it). I wonder if keeping the name empty in the config could be used for that purpose (though you'd need to include a comment about it in the config file to make sure it becomes clear).

**Comment by joncampbell123** [comment] 2020-03-09 16:11
Since DOS devices are accessed the same as filenames, CLIP$ might be a better choice to avoid surprises in case any DOS game or program expects to read a FILE named CLIP.

Perhaps it would be safer for the empty string to disable it as well. The config file should make it clear that if the user WANTS the DOS application to fiddle with the clipboard, that this is how you enable it.

**Comment by Wengier** [comment] 2020-03-09 17:03
Thanks for all the suggestions! I have made a new diff file which will do this: the default DOS device name for accessing the clipboard is now CLIP$ as you mentioned. It is completely disabled if you put e.g. "" as the device name. It will also not work if the secure mode is enabled. These will be stated in the config file comments.

Also, when I was making this patch I noticed that the -securemode command-line option for DOSBox-X does not work ("config -securemode" works though). This happened in the official 0.83.0 version released earlier too, and this patch will make a quick fix for this. Tested to ensure the build is working.

The diff file for the latest commit (e12a7dd) is now available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-e12a7dd-patch.diff

Thanks for all the feedbacks!


By the way, I

**Comment by Wengier** [comment] 2020-03-10 00:51
@joncampbell123 I was aware of the potential file name conflict, which is the reason I changed the default name to _CLIP from CLIP earlier; the name CLIP posted in the first post was mainly for testing. But I agree with you that it is probably safer to actually DISABLE it by default, since in a normal DOS system there is no such device, but if the user wants a DOS application to communicate with the clipboard, they can easily enable it (the name CLIP$ will be used by default in this case). In order to achieve this goal, I added another config option named "dos clipboard device enable" (default: false), in addition to the existing option, which is now named "dos clipboard device name" (default: CLIP$). The comments I added are as follows:

== Comments begins ==
dos clipboard device enable: If set, a DOS device will be added for bidirectional communications with the Windows clipboard.
The default name is CLIP$, but can be changed with the "dos clipboard device name" setting below.

dos clipboard device name: Set DOS device name (up to 8 characters) for bidirectional communications with the Windows clipboard.
If unset or invalid, the default name CLIP$ will be used (e.g. \"TYPE CLIP$\" shows the clipboard contents).
It has no effect if "dos clipboard device enable" is false, and it is deactivated if the secure mode is enabled.
== Comments ends ==

So with these two options a user can easily enable or disable this feature, or change the device name if they want, or just stick with the default name, which is CLIP$. The default name (CLIP$) will also be used if an invalid name is specified, but "dos clipboard device name" will have no effect if "dos clipboard device enable" is set to false since it will be disabled in this case.

The new diff file for the latest commit e12a7dd is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-e12a7dd-patch-linux.diff

**Comment by emendelson** [comment] 2020-03-10 16:36
I tried the CLIP$ output with an executable sent me by Wengier, and I can confirm that it worked perfectly for printing, copying, etc. It would be a very useful addition to the code.

**Comment by sikthehedgehog** [comment] 2020-03-10 17:56
Eh, I'd say that having `CLIP$` allowed by default is fine, and would be useful for people who want to share their DOSBox-X specific batch files or whatever. If anything, it's a tad less likely to clash with a real filename than `_CLIP` (seriously, who uses `$` in filenames besides the `.$$$` extension?).

But yeah, ultimately being able to enable/disable it by changing the configuration is important.

PS (unrelated comment): some day somebody should implement a TSR that implements `CLIP$` on real DOS lol

**Comment by joncampbell123** [comment] 2020-03-10 18:12
I think it should be disabled by default for now, while later revisions might default to allowing the DOS program to WRITE the clipboard, but not read it (same policy that web browsers apply to client-side Javascript). Of course you can change that to full access if you wish from dosbox.conf.

To understand why, think of the ways this feature can be abused. I'd rather not see a future where users are tricked into running DOSBox-X setups with malicious DOS code that runs a game while sniffing the clipboard for passwords or sensitive information, or other abuses.

It's the same reason the Integration Device interface provides a call to release mouse capture, but will never provide a call to capture the mouse. Only the user can capture the mouse to the emulator window.

**Comment by Wengier** [comment] 2020-03-12 18:04
@joncampbell123 I have now added the device access permission as you suggested. "dos clipboard device enable = read' will only enable READ access, and "dos clipboard device enable = write" will only enable WRITE access. "dos clipboard device enable = full" or "dos clipboard device enable = true" will enable both access; "dos clipboard device enable = dummy" will disable both access and "dos clipboard device enable = false" will disable the device altogether.

The new diff file for commit e12a7dd is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-e12a7dd-patch-new-linux.diff

A pre-compiled Windows 64-bit build is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-clip.zip

Tested to ensure it works properly.

This feature seems to have been finalized by now (the core clipboard code was used in vDosPlus so I know it is very stable; but since vDosPlus handled the naming part regarding such device differently from DOSBox-X, I could not copy this part to DOSBox-X directly, which was why I sought feedback from DOSBox-X users in my first post before finalizing it).

**Comment by joncampbell123** [comment] 2020-03-12 18:09
Patch applied. I think this is significant enough to mention in the CHANGELOG. What would you like me to add?

**Comment by Wengier** [comment] 2020-03-12 18:47
@joncampbell123 I think perhaps something like this:

Added support for DOS programs to communicate with the clipboard in Windows builds. If the "dos clipboard device enable" setting in dosbox.conf is set to "true" or "full", a DOS device (default name: CLIP$) will be added to allow bidirectional communications with the clipboard (e.g. "DIR >CLIP$" will write the output to the clipboard, and "TYPE CLIP$" will show the clipboard contents). Alternatively, you can set it to "read" or "write" to allow only read or write access for security reasons. The DOS device name can also be changed with the "dos clipboard device name" setting in dosbox.conf.

**Comment by emendelson** [comment] 2020-03-12 19:50
This is very impressive and very helpful. Thank you both! Is there any chance that the unicode support in this patch could now also be applied to the PasteClipboard feature already in the code for SDL1? At the moment, it supports ASCII text only; in my build, I change that to OEMTEXT, but it would be ideal if something like this could be done:

DOSBox-X would test for the current code page inside DOSBox-X (which might be 437, 850, 1252, etc.) and then translate Unicode text from the Windows clipboard into the correct codepage for DOS or 16-bit Windows.

I haven't read the diff closely enough to try to figure out what will happen when copying into DOSBox-X using CLIP$, but will experiment when I'm back at my working machine.

**Comment by Wengier** [comment] 2020-03-13 16:57
@emendelson It is not very difficult to modify the existing PasteClipboard feature to translate Unicode text according to the DOS codepage as in this patch, but (unlike clipboard communications via CLIP$) the existing PasteClipboard feature also relies on the code that does the keyboard handling, which needs to be modified as well in order for non-ASCII characters to be properly pasted. Since I will be away from my home computer for a while, maybe I will look at this part later.

**Comment by emendelson** [comment] 2020-03-13 17:04
@Wengier - Excellent! It will be good to have whenever you have some time. Thank you.

**Comment by Wengier** [comment] 2020-03-14 21:18
@joncampbell123 I have now also updated the existing PasteClipboard feature to support Unicode text translations as in this CLIP$ patch. It is achieved by calling to some of the functions in the CLIP$ patch from the existing PasteClipboard feature for the Unicode text translations in addition to modifications to the keyboard code that feeds the converted text to the guest. Also made some changes to the dosbox.conf reference file for the new feature. The diff file for the latest commit 01675de is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-01675de-patch.diff

A pre-compiled Windows 64-bit build is also available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-clip.zip

The updated PasteClipboard feature is considered stable now. Tested myself, and also confirmed with Edward Mendelson via email that pasting upper-ASCII characters via the updated PasteClipboard feature now works very well.

**Comment by Wengier** [comment] 2020-03-14 22:08
I also updated the CHANGELOG file in diff this time to reflect the update (improvements to the existing PasteClipboard feature in this case).

**Comment by Wengier** [comment] 2020-04-22 20:26
@joncampbell123 I have made a (small) patch that improved the CLIP$ feature to allow the clipboard text to be *appended* in addition to read and write (overwrite). For example, you can now use the >> operator to append content to the clipboard via CLIP$:

``ECHO This is the first line >CLIP$``
``ECHO This is the second line >>CLIP$``

Then the Windows clipboard will contain the two lines:
``This is the first line``
``This is the second line``

This also allows the COPY command to combine two or more files to CLIP$ to work, e.g.

``COPY FILE1.TXT+FILE2.TXT CLIP$``

So that the clipboard will contain the contents from both FILE1.TXT and FILE2.TXT.

Note the append operation requires both read and write accesses of the CLIP$ device in order to work.

Also added full support for the MS-DOS 7+ EDIT.COM tool to edit the clipboard content via CLIP$. The EDIT.COM from MS-DOS 7+ required some special handling in order to properly save to the CLIP$ device. On the other hand, DOSBox-X's built-in EDIT command (as well as EDIT.COM from MS-DOS 6.x) did not require this special handling.

In addition, I changed a welcome sentence "For more information read the README file in the DOSBox-X directory" to "For more information read the online guide in the DOSBox-X Wiki", because there is no such file with the name "README" in the DOSBox-X directory for end-users indeed. On the other hand, the DOSBox-X Wiki now contains various information that will probably helpful for users.

The diff file for the latest commit 2782946 is available from:

http://individual.utoronto.ca/wengier/files/dosbox-x-2782946-patch.diff

**Closed** 2020-06-01 22:10 UTC
Labels: topic: hardware
