### ISSUE TITLE
Fails to link against FluidSynth 1.1.9

### ISSUE THREAD

**Issue by heftig** [joncampbell123/dosbox-x#497] opened 2018-02-08 22:43 UTC
FluidSynth's parser is not public API. FluidSynth has been using `-fvisibility=hidden` since 1.1.7 so the parser symbols are no longer exposed. DOSBox-X will fail to link or run with newer versions of FluidSynth.

See https://github.com/FluidSynth/fluidsynth/commit/51cc2656e1b4a36c13f81ad838c4f520adc3d776 for an explanation.

Maybe copy the event parser from GStreamer's FluidSynth plugin?
https://github.com/GStreamer/gst-plugins-bad/blob/master/ext/fluidsynth/gstfluiddec.c#L390-L470

**Comment by heydojo** [comment] 2018-04-03 13:30
fluidsynth devs need to work on that code or link to or create a parser lib that people can use.
The parser has been used by quite a lot of projects using fluidsynth for their midi in the past and it's frustrating that they just decided that they changed their mind about it and went wontfix.

In the meantime, patch your copy of fluidsynth's source with https://github.com/FluidSynth/fluidsynth/commit/4568e551b93c5c7fc90992a7edd5b8ce932c5b94 and it should work.

In the long term, do you have a patch for the gstreamer parser which could be used instead?

**Comment by heydojo** [comment] 2018-04-04 20:24
Actually, looking into this I found that the fluidsynth parser is missing any kind of ring buffer, so audio and messages just go straight out without any pre-processing. This means that audio can glitch as there is no queue.
Probably best not to use the Dosbox-X fluid synth plugin for now and connect an external running copy of the main fluidsynth application to Dosbox-X's midi output until the issue is resolved.
Just select gm for the bank and load a sound font (in fluidsynth) once the correct midi device is set within the mididevice= configuration option. The easiest way to set that all up is by using qsynth.

**Comment by heftig** [comment] 2018-04-04 20:48
What kind of pre-processing are you expecting? It seems to work well enough.

**Closed** 2018-04-05 14:32 UTC

**Comment by heydojo** [comment] 2018-04-06 06:05
> the fluidsynth parser is missing any kind of ring buffer

Thanks.
