### ISSUE TITLE
Audio speech issues in SpaceQuest 4 v1.3

### ISSUE THREAD

**Issue by scrutinizer80** [joncampbell123/dosbox-x#2909] opened 2021-09-13 07:16 UTC
When running Space Quest IV v1.3 (Rising Sun) the speech begins to stutter in the intro sequence only when reaching a specific scene (inside the bar). 
From then on, the speech is incomprehensible in all parts of the game. 
If I skip the intro, the speech seems fine.
It's unknown whether the issue exists in other CD versions of the game.

The issue repeats on every launch and does NOT occur using DOSBox 0.74-3 with the same files.

**To Reproduce**
1. Watch the intro sequence to the end, audio skipping starts in the bar scene

**Environment:**
 - Windows 10 x64
 - DOSBox-X 0.83.17 SDL2
 - sb16 emulation

**Comment by grapeli** [comment] 2021-09-13 19:14
I confirm something is wrong.
dosbox-x sample
[SP4-dosbox-x.flac.txt](https://github.com/joncampbell123/dosbox-x/files/7156825/SP4-dosbox-x.flac.txt)

dosbox-SVN sample
[SP4-dosbox-svn.flac.txt](https://github.com/joncampbell123/dosbox-x/files/7156826/SP4-dosbox-svn.flac.txt)

**Comment by grapeli** [comment] 2021-09-14 13:12
I think the correct setting for this game is `sbtype=sbpro2`.

https://user-images.githubusercontent.com/452325/133263593-631383e2-3d7c-4379-b4c6-e4d5c92040b2.mp4

When running with `log sblaster=debug`, `sbtype=sb16`
messages of this content appear
`SBLASTER:Guest is using non-SB16 playback commands after using SB16 commands to set sample rate`
with `sbpro2` they are not there.

**Comment by rderooy** [comment] 2021-09-14 13:14
dosbox-staging made a nice overview of DOS games that **actually** support 16bit audio, of which there are surprisingly few.
https://github.com/dosbox-staging/dosbox-staging/wiki/Games-that-play-16-bit-audio

SQ4 is not one of them.

**Comment by scrutinizer80** [comment] 2021-09-14 13:29
> I think the correct setting for this game is `sbtype=sbpro2`.
> 
>  SQ4-dosbox-x-sbpro2.mp4 
> When running with `log sblaster=debug`, `sbtype=sb16`
> messages of this content appear
> `SBLASTER:Guest is using non-SB16 playback commands after using SB16 commands to set sample rate`
> with `sbpro2` they are not there.

True. But if it works on plain DOSBox it should also work on DOSBox-X regardless of the possibility of more "optimal" settings.
Also the game works fine on real SB16 hardware

**Comment by scrutinizer80** [comment] 2022-03-06 16:36
I was hoping the recently resolved bug in Freddy Pharkas would also fix this issue with SQ. But No.
Issue still exists.

**Comment by joncampbell123** [comment] 2022-03-06 19:39
Freddy Pharkas plays 16-bit audio if sbtype=sb16 but it still uses DSP command 0x48 to set the DSP block size. The fix for Pharkas was that that DSP command specifies the block size in BYTES, while internally DMA is counted in samples, and therefore converting the value when using that DSP command. It happens to work with SB Pro though because Pro counts DMA in individual samples, meaning samples times two if stereo. It's confusing, I know :)

Perhaps SQ4 is another such case of mixing SB Pro and SB16 commands like that.

**Comment by grapeli** [comment] 2022-03-15 15:36
@Jkapp76 
You can justify it in a specific way. Show off that perfect sound. Enter the exact configuration you used. Is it just purely subjective feelings.

I tested and compared the dosbox-staging and dosbox-SVN sounds quite accurately. There is no major difference between sbpro2 and sb16.

What could the difference between sb, sbpro2, sb16. If these audio samples are 8-bit 11025Hz.
After all, it is clearly visible on the spectrogram. The frequency limit of the sound samples is about 6000Hz, which means that the bandwidth is twice as high - 11025Hz.

Yes, various unwanted artifacts are audible under each of them.
Four different samples. Exactly the same three clicks heard on each of them. In the same places.

s1 - `dosbox-x -set sbtype=sbpro2 -set "sblaster disable filtering=false" -set rate=44100`

[s1.flac.txt](https://github.com/joncampbell123/dosbox-x/files/8254843/s1.flac.txt)

![s1](https://user-images.githubusercontent.com/452325/158413560-65d382f6-878d-4f1f-ad32-e461687f854d.jpg)

s2 - dosbox-staging (default config)

[s2.flac.txt](https://github.com/joncampbell123/dosbox-x/files/8254844/s2.flac.txt)

![s2](https://user-images.githubusercontent.com/452325/158413640-d438f5f7-5268-4ec7-b8b7-4d5584c0c1fd.jpg)

s3 - youtube gqWZJj35TO8 - dosbox ???

[s3.flac.txt](https://github.com/joncampbell123/dosbox-x/files/8254849/s3.flac.txt)

![s3](https://user-images.githubusercontent.com/452325/158413702-02693b16-1fc3-4e32-9841-da2d7ef84208.jpg)

s4 - youtube RIcP65N1TQg - dosbox daum

[s4.flac.txt](https://github.com/joncampbell123/dosbox-x/files/8254854/s4.flac.txt)

![s4](https://user-images.githubusercontent.com/452325/158413776-250b39b3-5951-4afa-8a8d-b62440ee44e2.jpg)

The fact that someone does not want to use the `sbtype=sbpro2` configuration does not mean a bug in dosbox-x.

**Comment by Jkapp76** [comment] 2022-03-15 20:29
I'm not talking about a suggestive feeling about the sound. I can't understand the words of the man speaking. it sounds like he is hiccupping. It's not mt opinion, the sound is no good.

I changed the sq4 setting from mt32 to adlib and it's still bad. Tried others too.

These settings all sound good on other dosbox builds, and 86Box which I just tried.

I'm here because I wanted to test this bug for myself and it surely seems like a bug in -x to me. I can't get any other build of dosbox to glitch the speech.

And, to answer your question above... there is no place in the sq4 installer to change sound from sb16 to sbpro2. I was talking about the dosbox soundcard setting. I have tried different rates too 44100 and so on.

**Comment by grapeli** [comment] 2022-03-15 23:12
@Jkapp76 
**I only compare the sound quality of digitized sound samples.** Not mt32, gm.

The quality of sbpro2 in dosbox-x in SQ4 is the same (or close to) as sb16 in dosbox-staging.
If you find differences. Showcase these samples.
I can't hear them.
`dosbox-x -set sbtype=sbpro2 -set "sblaster disable filtering=false"`

https://user-images.githubusercontent.com/452325/158486698-0b14f77a-6c2b-4fdb-8657-bcb0450f2417.mp4

dosbox-staging  sbtype=sb16

https://user-images.githubusercontent.com/452325/158486676-9b830949-bf1b-48de-8613-889ec7d33137.mp4

Scummvm. Surprise cuts the sample.
https://youtu.be/JvGV0z2lEKg


https://user-images.githubusercontent.com/452325/158486913-731b1895-7314-4415-88c4-bb659d29be04.mp4

This little bit is missing here.


https://user-images.githubusercontent.com/452325/158486941-e53d2b39-4877-451e-9d50-af077eed6999.mp4

https://youtu.be/KSrGGcH34hk

https://user-images.githubusercontent.com/452325/158486976-b82da95e-9c2d-4b14-b18b-4ae97fd00efd.mp4

In the second recording, even longer.


https://user-images.githubusercontent.com/452325/158487010-0156bc0f-36ee-48f2-886d-66a953efed59.mp4

It's hard to find the ideal.
I listened to 15 samples on the yt, all with the same clicks.

**Comment by Jkapp76** [comment] 2022-03-16 03:14
No matter which setting I use the music sounds great. Only the speech seems to be chunky with any setting. But the speech seems to be perfect for me with any setting using another dosbox build. The speech jumps and is completely incomprehensible.

**Comment by grapeli** [comment] 2022-03-16 13:02
I don't know how it should sound perfect. In order for me to have access to such a source, I could then refer to it.

**I emphasize once again there is no major or even smaller difference between dosboxes in terms of sound quality** (this applies to the sb16 vs sbpro2 settings).

**It all comes down to finding the correct and proper dosbox configuration settings.**

Let's take an episode in the bar under the microscope. Previously dosbox settings were cycles=8000.
Let's change to 1500.
`dosbox-x -set sbtype=sbpro2 -set "sblaster disable filtering=false" -set cycles=1500`
So this rag-talk extends to 34 seconds.

https://user-images.githubusercontent.com/452325/158595467-fb577c3b-9cde-4a43-a6bd-578178dff4a2.mp4

Let's increase it to 20000.
`dosbox-x -set sbtype=sbpro2 -set "sblaster disable filtering=false" -set cycles=20000`
The same conversation is shortened to 12 seconds.

https://user-images.githubusercontent.com/452325/158595417-fe7d51f0-5abe-4c8b-91fa-8fada8393385.mp4

**Comment by Jkapp76** [comment] 2022-03-16 17:28
Are you saying you can't reproduce the speech problem? What we are saying is we can understand what the character, Roger Wilco is saying in every version of DOSBox... but in DOSBox-x his speech is garbled and skips and therefore we cannot make out his words.

You keep saying you're looking for the ideal sound, and you can't see a difference in a visual sound wave. but we're saying the music is fine, we just can't make out the speech.

All of your speech samples sound good.

**Comment by grapeli** [comment] 2022-03-16 18:32
I will quote because it seems you forgot what you wrote.

>I tried the (sbpro2) setting in dosbox-x and it is better but still buggy with hiccups. Certainly not perfect.

Present the perfect version from another dosbox.
I will compare it to the dosbox-x version.

**Comment by grapeli** [comment] 2022-03-16 18:50
SQ4 is full of bugs.
It has 10 different versions of the game.
I found 4 different versions of the `AUDBLAST.DRV` driver (maybe there are more).
There are probably 10 patches available.
The list of errors is quite large.
http://www.sierrahelp.com/Games/SpaceQuest/SQ4Help.html

It's easy to get lost here. It is not known who is using what version exactly. Hence the large discrepancies in assessment.

**Comment by Jkapp76** [comment] 2022-03-16 19:25
I'm using the same version as the guy who made this post is using. 1.3
I don't hear any issues with the speech in any of your sound samples.

I only hear issues in speech using dosbox-x.

https://user-images.githubusercontent.com/89743985/158671716-68c8beac-6bb3-4ceb-9c8a-3910258488bc.mp4

Here's a sample of the audio for you. I get this result with any audio setting. The music changes with different music device settings but the speech is always garbled.

**Comment by Jkapp76** [comment] 2022-03-16 19:27
Notice how the music plays perfectly behind the speech. The speech is garbled, but the music always plays right on through it great. This speech plays perfect with dosbox-staging and ece.

**Comment by grapeli** [comment] 2022-03-16 19:55
> I'm using the same version as the guy who made this post is using. 1.3 I don't hear any issues with the speech in any of your sound samples.
> 
> I only hear issues in speech using dosbox-x.

My dosbox-x signed samples just come from **DOSBox-X**.

**Comment by Jkapp76** [comment] 2022-03-16 20:18
memoryDrv = ARM.DRV
 audioSize = 16k
 minHunk   = 206K

**Comment by grapeli** [comment] 2022-03-16 20:47
For me, this value is 32k.

I downloaded this patch.
https://www.spacequest.net/downloads/sq4patch13.zip

It includes changing the `audioSize` value, among other things. As well as the fix for the AUDBLAST.DRV driver.
There are about 700 corrections there. You need two floppy and cdrom versions.

Unfortunately, I do not have this version.
This is the SQ4 developer update?

**Comment by Jkapp76** [comment] 2022-03-16 22:04
This is the most up to-to-date version there is. I'm using it, and the guy who posted this bug.

I could zip my copy and send you a download link if that helps?

**Comment by grapeli** [comment] 2022-03-16 22:50
> I could zip my copy and send you a download link if that helps?

I don't think so. I just copied the `AUDBLAST.DRV` driver (9451 bytes) and changed the `audioSize` to 16k.

I actually have to agree with you. For SQ4 1.3, it must be a dosbox-x bug.

In a bar sequence, the quality of these digatilized samples is completely unacceptable. Also in the next longer scene. I still stopped following. This is true for both `sbtype=sb16` and `sbpro2`.

I checked under dosbox-staging (sb16). Everything sounds very good.

**Comment by Jkapp76** [comment] 2022-03-16 22:57
That's everything I saw. I hope it's not a difficult fix.

**Comment by grapeli** [comment] 2022-03-16 23:16
> That's everything I saw. I hope it's not a difficult fix.

I don't know, I'm not a dosbox-x developer.

This message was displayed in the dosbox-x log while this bar sequence was running - using non-SB16 playback.
Multiple - 251 times.

>DEBUG SBLASTER:Guest is using non-SB16 playback commands after using SB16 commands to set sample rate
>      SBLASTER:DMA unmasked,starting output, auto 1 block 16383
>      SBLASTER:Raising IRQ
>DEBUG DOSMISC:Executing interrupt 21, ah=3f, al=e4
>DEBUG FILES:Reading 8192 bytes from SQ4\RESOURCE.AUD
>...

**Comment by grapeli** [comment] 2022-03-17 20:50
SQ4 v1.3 sounds correct with `sb16` under **dosbox-0.65** (March 2006). A really long time.

Out of curiosity, I started to check if this version of the game sounded good under dosbox-x (with `sbpro2` of course).
So far I have found one certain such version. This is the first tagged version of dosbox-x. Even the logo of the original dosbox remains.
d1f2b1c69f593f5de9979ec613fb6b08a8f35695 untagged-3f29f16778ab28a1a69e 2014-07-19

![dosbox-x-untagged-3f29f16778ab28a1a69e](https://user-images.githubusercontent.com/452325/158892727-0bc990b4-b036-4743-9a4c-7129f953898c.png)

So it broke in the meantime.

**Comment by Jkapp76** [comment] 2022-03-17 21:01
good work, grapeli!
This should give the devs something to work with.

**Comment by grapeli** [comment] 2022-03-18 00:00
I ran a git bisect.

good f986c6c <v0.801>
good b6cd8c9 <dosbox-x-b6cd8c9fff59f5bf9703ac33b6b1521fa232c504>
good a1dd39e good bugfix: don't reset IO handlers on RESET signal. this fixes non-functional Sound Blaster.
good cce9b6b good I just realized the BIOS POST routine has to deal with the fact that the DOS kernel was in
bad 7becbf1 bugfix for "Jump" demo: always assign total count even if forced auto-init. prior to this fix,
bad 210d9e9 keyboard: reset function needs to remove... 
bad 9057697 <dosbox-x-windows-v0.801.newyears.b3>

In my opinion, this commit 7becbf1 for the "Jump" demo broke the sound in SQ4 v1.3 for sbpro2.
At least for those historic versions of dosbox-x.

I withdrew this commit on the current version of sblaster.cpp.
Unfortunately, I did not get a satisfactory result. The sound quality (sbpro2) in the bar scene is bad.
Of course I am not sure if I am going to change this code correctly. I am not a programmer.

**Comment by grapeli** [comment] 2022-03-18 01:08
Well, previously I made a bad change to `sblaster.cpp`.

After such a change in the latest code, the sound in SQ4 v1.3 is correct. This applies to `sbpro2`. Most likely and `sb1`, `sb2` and other versions **except** `sb16`.

```
--- src/hardware/sblaster.cpp
+++ src/hardware/sblaster.cpp
@@ -1072,7 +1072,7 @@
     if (sb.dma.force_autoinit)
         autoinit = true;

-    sb.dma.total=1u+(unsigned int)sb.dsp.in.data[0]+(unsigned int)(sb.dsp.in.data[1] << 8u);
+    if (!autoinit) sb.dma.total=1u+(unsigned int)sb.dsp.in.data[0]+(unsigned int)(sb.dsp.in.data[1] << 8u);
     sb.dma.autoinit=autoinit;
```

**Comment by Jkapp76** [comment] 2022-03-18 03:25
I personally would consider a Sierra game a higher priority than any demo.

**Comment by Jkapp76** [comment] 2022-03-21 03:14
Maybe someone can create a pull request from this information? It seems necessary.

**Closed** 2022-03-22 06:06 UTC
Labels: topic: input, DOS gaming

**Comment by Jkapp76** [comment] 2022-03-31 19:47
I just wanted to come back here to say two things...

1. This last patch fixed the SQ4 issue perfectly.
2. I used the old buggy version of -X and had a really interesting thing happen. In the place where roger has the speech issue and soon after gets interrupted by the police and stops talking... One time I had a different issue where the police took a very long time to arrive... but Roger kept on talking, and he continued his story recapping SQ2 all the way to where he said he climbed into the sleep chamber and closed the lid. Very cool to know the game has that much audio available there. I wish we could delay the police and always hear this in entirety.

**Comment by scrutinizer80** [comment] 2022-04-11 14:37
Just noticed this issue has been fixed in the latest version.
Kudos to everyone involved & Thanks.
