### ISSUE TITLE
x86 virtualization for better Windows support

### ISSUE THREAD

**Issue by goergf** [joncampbell123/dosbox-x#2514] opened 2021-05-08 10:35 UTC
**Observed problem**
The emulated cpu offers less performance and stability than a virtualized cpu like in VirtualBox

**Alternative that I already use**
Until now I use wine or VirtualBox and I am absolutely happy about cpu performance there. On Windows 98SE at least, I notice a remarkable boost when using the VT-x/AMD-V function with nested paging.

**Solution that I like**
I would prefer to use DOSBox-X as it has other positive features and Windows 9x is shown to be supported. I also prefer DOSBox-X over PCem because I appreciate its balance between performance and accuracy. So far the emulated CPU keeps me away, although I think it's great for DOS applications.

I like to have the option to select a virtualized cpu and I wonder if this feature could be taken from VirtualBox. I also would like to test any early implementation of such a feature.

**Additional context**
I think virtualisation would also fit the demand of Pentium II support   https://github.com/joncampbell123/dosbox-x/issues/2435

**Comment by Wengier** [comment] 2021-05-09 04:13
Thanks for your suggestion. I agree that the general stability and performance for Windows 9x are likely better in a virtual machine like VirtualBox at this time. DOSBox-X does intend to "add full support for Windows 95, 98, and ME emulation and acceleration" as part of its goal, but this of course does require significant amount of work, so please stay tuned.

**Comment by joncampbell123** [comment] 2021-05-09 05:46
This is a duplicate of https://github.com/joncampbell123/dosbox-x/issues/1089.

I've already thought of this, though at least for the Linux KVM interface for the same.

By the way, I also happen to know that VirtualBox has some issues with virtualization extensions and Windows 95 (and sometimes 98). My experience has been that you actually have to turn OFF the virtualization extensions to run Windows 95/98 to avoid problems.

**Closed by joncampbell123** 2021-05-09 05:46 UTC
Labels: topic: Windows
