### ISSUE TITLE
Puzzle Bobble 2x and SF2T CD issue

### ISSUE THREAD

**Issue by petran79** [joncampbell123/dosbox-x#3638] opened 2022-07-19 05:43 UTC
### Describe the bug

In Puzzle Bobble 2x DOS version, keyboard does not respond at all. Other DOSbox versions do not have this issue

In Street Fighter 2 Turbo, if you mount the CD image, game refuses to install to mounted C: drive due to lack of space

### Steps to reproduce the behaviour

for Puzzle Bobble : run the file bam2. bat
for sf2t: mount any directory as c: drive and mount the cd Iso, then try to install to c: 

### Expected behavior

tried the same games in dosbox svn, ece and staging and they did not have these issues

### What operating system(s) this bug have occurred on?

Windows 10 64bit 19403

### What version(s) of DOSBox-X have this bug?

0.84.1

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by rderooy** [comment] 2022-07-19 06:37
If you have a DOS game/program complaining about lack of free space, and there is actually enough space available, limit the amount of space reported to DOS programs by using the `-freesize xx` option with the `mount` command.

e.g. to limit freesize reporting to 100MB for an folder mounted HDD.

```
mount c: /home/myuser/myfolder -freesize 100
```

**Comment by grapeli** [comment] 2022-07-19 20:01
Regarding the first title, I confirm the problem described. This game in the DOS version is probably titled Bust-A-Move 2.
I tested on this particular version.
https://archive.org/details/bustamove2dos

**This is regression.** Works fine under dosbox-x up to 0.83.19.
The game stops responding to calls from the keyboard exactly from this change in the ce936e8 code.

**Comment by Allofich** [comment] 2022-10-16 12:44
@petran79, did @rderooy's suggestion about the -freesize option work? If so, the PR I just sent in for the keyboard problem should resolve this issue.

**Comment by petran79** [comment] 2022-10-27 21:37
freesize option works but unfortunately BAM2 keyboard does not work yet and I tried the recent build from 13 October.

**Comment by grapeli** [comment] 2022-10-27 22:16
@petran79 
>...but unfortunately BAM2 keyboard does not work yet and I tried the recent build from 13 October.

It is not surprising.
Pull request #3786 has not been attached to the main repository yet.
You can apply this patch yourself and compile or download a ready [test build](https://github.com/joncampbell123/dosbox-x/actions?query=branch%3Aport61fix+is%3Asuccess
) with this code.

**Comment by grapeli** [comment] 2022-10-28 09:20
I can confirm. It works.

[bust-a-move-2.dosbox-x.webm](https://user-images.githubusercontent.com/452325/198552663-31f12140-9b16-4694-8c5f-5b27f97b8221.webm)

**Comment by petran79** [comment] 2022-10-28 10:22
now I noticed that for a strange reason dosbox switched to Japanese settings after using the dev build (¥ sign appears instead of \:). Probably this affects the input.

**Comment by Allofich** [comment] 2022-10-28 10:57
@petran79
Thanks for confirmation that the -freesize option worked for SF2T. I'll mark the PR to automatically close this issue on merge, then.

> now I noticed that for a strange reason dosbox switched to Japanese settings after using the dev build (¥ sign appears instead of \ : Probably this affects the input.

If this turns out to be a problem, please make a new issue for it.

**Comment by rderooy** [comment] 2022-10-28 11:23
> now I noticed that for a strange reason dosbox switched to Japanese settings after using the dev build (¥ sign appears instead of \ : Probably this affects the input.

That is normal. It is because the Japanese codepage has the Yen symbol at the location of the \. This even happens on real Japanese legacy systems. DOS will show `C:¥>` as the prompt

**Closed** 2022-10-29 03:52 UTC
Labels: bug
