### ISSUE TITLE
This program cannot be run in DOS mode

### ISSUE THREAD

**Issue by Arthur3032** [joncampbell123/dosbox-x#3169] opened 2021-12-22 00:06 UTC
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar question(s) already exists?

- [X] I have searched and didn't find any similar issues.

### Question

dear sir,
I execute the command in the DOSBOX-X command mode,
For example: winet.exe
Will appear
This program cannot be run in DOS mode.
After all, it is still executed, and it is executed normally.
However, I am in Clipper 5.3b and call winet.exe
It only appears
This program cannot be run in DOS mode.
There is no more 

ps. 
DoxBox-X 0.83.21
DOS v7.1
country: 886,995
language: zh_TW

**Comment by joncampbell123** [comment] 2021-12-22 00:29
EXE files will print that message when you execute the "MS-DOS stub" of a Windows application.

Real MS-DOS will do the same.

DOSBox-X will always run executables through the MS-DOS header, same as DOSBox SVN and any other fork, and any real MS-DOS system.

**Comment by joncampbell123** [comment] 2021-12-22 00:31
This is the MS-DOS EXE header originally defined since MS-DOS 2.0:

http://www.delorie.com/djgpp/doc/exe/

**Comment by joncampbell123** [comment] 2021-12-22 00:33
The Windows or OS/2 header is placed elsewhere in the EXE file, and a DWORD at offset 0x3C points at it. The signature at that offset indicates what kind it is.

"NE" Windows 3.x 16-bit executable or OS/2 16-bit executable
"PE" 32-bit/64-bit Windows executable, common in use still today
"LE" Linear executable, which is used by OS/2 32-bit, VXD drivers, and 32-bit MS-DOS programs loaded by DOS4GW or CWSDPMI

https://docs.microsoft.com/en-us/windows/win32/debug/pe-format?redirectedfrom=MSDN#ms-dos-stub-image-only

**Comment by joncampbell123** [comment] 2021-12-22 00:35
This design allows the EXE to contain code for both MS-DOS and Windows. By default, Microsoft's Linker will attach a small "stub" program that prints that message, however you can put anything you like in the MS-DOS portion.

**Comment by Arthur3032** [comment] 2021-12-22 00:43
Understand, thanks for the detailed explanation

**Comment by Arthur3032** [comment] 2021-12-22 00:50
Can the DosBox-X window be resize, in runtime? 

in English mode , it's ok, but Chinese mode, cannot be.
ps.
DoxBox-X 0.83.21
DOS v7.1
country: 886,995
language: zh_TW

**Comment by Wengier** [comment] 2021-12-22 00:53
You can increase or decrease the window size in Chinese TTF mode with the menu options "Increase TTF font size" / "Decrease TTF font size", or using the keyboard shortcuts F11 + Up/Down.

P.S. DOSBox-X emulates the behaviors of "pure" DOS mode by default, so the message "This program cannot be run in DOS mode" is expected when you run PE apps. There is a GUI for DOS known as Windows 9x which does allow you to run PE apps outside the DOS command prompt, and you can run such applications if you enable START command with `startcmd=true` in DOSBox-X. Windows XP and later, however, are not DOS-based so they are no longer GUIs for DOS.

**Comment by Arthur3032** [comment] 2021-12-22 01:01
The response is really fast, thank you very much

**Comment by Arthur3032** [comment] 2021-12-22 01:05
But windows EXE, in DOSBOX-X command mode
can Directly give instructions (without CA-Clipper), how it to do.

**Comment by Arthur3032** [comment] 2021-12-22 01:07
![image](https://user-images.githubusercontent.com/93595854/147017646-47c1759e-a4ca-41d6-95e6-084641f8901e.png)

**Comment by Wengier** [comment] 2021-12-22 01:09
@Arthur3032 I don't have the Clipper program that you mentioned. Can you upload it so that I can test it as well?

**Comment by Arthur3032** [comment] 2021-12-22 01:15
[Test.rar.zip](https://github.com/joncampbell123/dosbox-x/files/7759214/Test.rar.zip)

**Comment by Arthur3032** [comment] 2021-12-22 01:17
in Dosbox-X command mode
type 
WINPRINT TT.PRG 
( or another text file)

in Dosbox-X command mode
type 
TT.exe    (This is Clipper exe file, tt.prg is source code)

**Comment by Wengier** [comment] 2021-12-22 01:53
@Arthur3032 Thanks for the program. I could reproduce the issue, and have hopefully fixed in the updated Windows build below. Please check it out:

* [dosbox-x-update.zip](http://cndos.fam.cx/dosware/dosbox-x-update.zip)

**Comment by Arthur3032** [comment] 2021-12-22 02:01
Too strong, can't believe it, am I dreaming? (It was actually executed normally)
Thank You very much.

**Comment by Arthur3032** [comment] 2021-12-22 02:02
So, in later versions, is that the same?

**Comment by Wengier** [comment] 2021-12-22 02:04
@Arthur3032 Sure, it is fixed for the later version.

**Comment by Arthur3032** [comment] 2021-12-22 02:19
That's great

**Comment by Wengier** [comment] 2021-12-24 02:07
Closing the issue.

**Closed by Wengier** 2021-12-24 02:07 UTC
Labels: bug, topic: Windows, topic: MS-DOS
