### ISSUE TITLE
macOS: Clipboard paste keyboard shortcut doesn't paste the first few characters into WPDOS

### ISSUE THREAD

**Issue by emendelson** [joncampbell123/dosbox-x#2136] opened 2020-12-30 20:12 UTC
This occurs in macOS, not under Windows, and with SDL1 and SDL2 builds.

Running either WPDOS 5.1 or 6.2, when I use the DOSBox-X menu's clipboard-paste feature, the entire string in the clipboard is pasted in correctly.

But when I use a mapped keyboard shortcut, the first few characters in the string are dropped, and only the rest of the string gets pasted. The number of characters dropped seems to be random - between 5 and 15 - and this problem occurs even if I increase the clip_paste_speed setting to 100.

The problem does not occur at the command line or in the WP ED.EXE editor program. Is there anything that can be done with this, or should I just disable the keyboard shortcut in macOS builds designed for WPDOS?

**Comment by Wengier** [comment] 2020-12-30 20:39
What if you change the keyboard shortcut for the keyboard paste function to something that does not use the Host key? E.g. something like Ctrl+F6?

**Comment by emendelson** [comment] 2020-12-30 21:48
@Wengier That's very interesting! I can't use Ctrl-F6, because WPDOS uses all combinations of Ctrl/Alt/Shift and the F keys, but I have Mod 3 mapped to the Cmd key (instead of the standard Shift - I don't remember how I did that), and if I use Cmd-F4 or Cmd-Option-F4, the clipboard is pasted correctly. This is very strange. 

If Ctrl-Alt (my host key) can't be used, this is an alternative, but I hope it might be possible to fix the host key to avoid this problem. Meanwhile, thank you for this suggestion, which I can certainly use!

**Comment by Wengier** [comment] 2020-12-30 21:54
@emendelson The problem is not really with the host key itself, but that since the pasting uses the keyboard method, and the host key is currently pressed, so these first keys will be trapped into host key combinations, and I don’t think there is an easy fix for this at this time. You do not need to use Ctrl+F6, which is just an example, but other combinations without the host key should work too. Hope this helps.

**Comment by emendelson** [comment] 2020-12-30 23:02
@Wengier - That helps enormously. Again, this doesn't seem to be a problem in Windows, only on macOS, but this solution will help enormously. I'll close this now.

**Closed** 2020-12-30 23:02 UTC
Labels: platform: Mac, topic: clipboard

**Comment by Wengier** [comment] 2020-12-31 00:07
I am modifying the default shortcut for pasting too, as the default shortcut Host+V can indeed cause problems.
